- platform: template
  sensors:
    lux_measurement:
      friendly_name: "Faux Lux Measurement"
      value_template: >-
        {{ is_state('sun.sun', 'above_horizon')
        and states('sun.sun.attributes.elevation') | float < 17.0
        and states('sensor.dark_sky_cloud_coverage') |float > 65.0}}
      icon_template: >-
        {% if is_state('sun.sun', 'below_horizon') %}
        mdi:brightness-2
        {% elif is_state("binary_sensor.lux_measurement", "true") %}
        mdi:weather-cloudy
        {% else %}
        mdi:brightness-5
        {% endif %}
