homeassistant:
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages
  customize: !include customize.yaml

http:
  server_port: 80

default_config:
bluetooth:
cloud:
stream:
wake_on_lan:
logbook:
  exclude:
    entities:
      - automation.update_tesla_location_as_mqtt_location_updates

prometheus:
  namespace: hass

automation config: !include_dir_merge_list automation
automation ui: !include automations.yaml
group: !include config/groups.yaml
input_boolean: !include config/input_boolean.yaml
notify: !include config/notify.yaml
script: !include_dir_merge_named scripts/
