system_health:

# Enables the frontend
frontend:

# Enables configuration UI
config:

cloud:

mobile_app:

weather:
  - platform: environment_canada

homeassistant:
  auth_providers:
    - type: homeassistant

http:
  server_port: 80

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

device_tracker:

wemo:
  static:
    - 172.16.0.53
    - 172.16.0.54

automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
camera: !include config/camera.yaml
cover: !include config/covers.yaml
group: !include config/groups.yaml
homekit: !include config/homekit.yaml
input_boolean: !include config/input_boolean.yaml
ios: !include config/ios.yaml
notify: !include config/notify.yaml
scene: !include config/scenes.yaml
sensor: !include_dir_merge_list sensor

stream:

wake_on_lan: