homeassistant:
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages
  customize:
    zone.home:
      radius: 450

http:
  server_port: 80

wemo:
  static:
    - 172.16.0.53
    - 172.16.0.54

default_config:
cloud:
discovery:
stream:
wake_on_lan:
logbook:
  exclude:
    entities:
      - automation.update_tesla_location_as_mqtt_location_updates

recorder:
  db_url: !secret db_url

prometheus:
  namespace: hass

automation config: !include_dir_merge_list automation
automation ui: !include automations.yaml
camera: !include config/camera.yaml
group: !include config/groups.yaml
google: !include config/google.yaml
homekit: !include config/homekit.yaml
input_boolean: !include config/input_boolean.yaml
notify: !include config/notify.yaml
script: !include_dir_merge_named scripts/
