system_health:

# Enables the frontend
frontend:

# Enables configuration UI
config:

homekit:
  filter:
    include_domains:
      - light
      - switch
      - cover
      - lock

cloud:

mobile_app:

weather:
  - platform: environment_canada

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 172.16.0.0/24
        - 172.16.1.0/24

http:
  server_port: 80

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

device_tracker:

wemo:
  static:
    - 172.16.0.53
    - 172.16.0.54

input_boolean:
  pupper_home:
    name: Puppy Home
    initial: on
    icon: mdi:dog
  nap_mode:
    name: Nap Mode
    initial: on
    icon: mdi:sleep

automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
cover: !include covers.yaml
group: !include groups.yaml
ios: !include ios.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensor

stream:

camera:
  - platform: generic
    name: Streaming
    still_image_url: !secret baby_cam_snap
    stream_source: !secret baby_cam_stream
