system_health:

# Enables the frontend
frontend:

# Enables configuration UI
config:

cloud:

http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies: "127.0.0.1"
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

device_tracker:

wemo:
  static:
    - 172.16.1.4
    - 172.16.1.5
    - 172.16.1.6
    - 172.16.1.7

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: liftmaster

# Wifi Tracking
unifi:
  controllers:
    - host: !secret unifi_host
      site: default
      ssid_filter:
        - 'Core'

notify:
  - platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

input_boolean:
  pupper_home:
    name: Puppy Home
    initial: on
    icon: mdi:dog

shell_command:
  healthchecks_io: !secret healthchecks_io_cmd

automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
sensor: !include_dir_merge_list sensor
group: !include groups.yaml
