homeassistant:
  auth_providers:
    - type: homeassistant

http:
  server_port: 80

wemo:
  static:
    - 172.16.0.53
    - 172.16.0.54

default_config:
cloud:
device_tracker:
discovery:
stream:
wake_on_lan:

alert: !include config/alert.yaml
automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
camera: !include config/camera.yaml
cover: !include config/covers.yaml
group: !include config/groups.yaml
homekit: !include config/homekit.yaml
input_boolean: !include config/input_boolean.yaml
ios: !include config/ios.yaml
notify: !include config/notify.yaml
scene: !include config/scenes.yaml
sensor: !include_dir_merge_list sensor
weather: !include config/weather.yaml