homeassistant:
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages
  customize: !include customize.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24 # Addon Subnet
    - 127.0.0.1 # Addon proxy

default_config:
bluetooth:
cloud:
stream:
wake_on_lan:
logbook:
  exclude:
    entities:
      - automation.update_tesla_location_as_mqtt_location_updates

prometheus:
  namespace: hass

automation ui: !include automations.yaml
group: !include config/groups.yaml
input_boolean: !include config/input_boolean.yaml
notify: !include config/notify.yaml
script: !include_dir_merge_named scripts/
