homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

  customize: !include customize.yaml
  customize_glob:
    "*nest*health":
      hidden: true
    "*nest*status":
      hidden: true
    "*nest*online":
      hidden: true
    "*thermostat*leaf":
      hidden: true
    "*thermostat*locked":
      hidden: true
    "*thermostat*emergency*":
      hidden: true
    "*hvac*":
      hidden: true

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

panel_iframe:
    terminal:
        title: Terminal
        icon: mdi:console
        url: http://hass:7681

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Wifi Tracking
device_tracker:
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_user
    password: !secret unifi_pass
    verify_ssl: False
    site_id: default
    port: 8443
    new_device_defaults:
        track_new_devices: False
        hide_if_away: False

# Lights
light:
  - platform: hue
    host: 172.16.0.192

wemo:
  static:
    - 172.16.1.4
    - 172.16.1.5
    - 172.16.1.6
    #- 172.16.1.7

# Weather prediction
sensor:
  - platform: darksky
    api_key: !secret darksky_api
    monitored_conditions:
      - summary
      - icon
      - precip_probability
      - temperature
      - humidity
      - nearest_storm_distance
    units: ca

media_player:
    - platform: cast
    - platform: kodi
      host: finn

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

apcupsd:
  host: 172.16.0.1

group: !include groups.yaml
# Automations
automation: !include automations.yaml
