water_leak:
  name: Water Leak Detected
  done_message: "clear_notification"
  entity_id: group.leak_sensors
  state: "on"
  can_acknowledge: true
  repeat: 30
  data:
    uri: /lovelace/leak-sensors
    tag: "water-leak-alert"
    actions:
      - action: "ACK_LEAK"
        title: "Acknowledge Leak"
        activationMode: "background"
        authenticationRequired: true
        destructive: true
        behavior: "default"
    push:
      sound:
        name: "US-EN-Alexa-Water-Detected-Generic.wav"
        critical: 1
        volume: 1.0
  notifiers:
    - mobile_app_michaels_iphone