water_leak:
  name: Water Leak Detected
  done_message: All Dry!
  entity_id: group.leak_sensors
  state: "on"
  can_acknowledge: true
  repeat: 30
  data:
    url: /lovelace/leak-sensors
    push:
      category: "acknowledge_leak"
      sound:
        name: "US-EN-Alexa-Water-Detected-Generic.wav"
        critical: 1
        volume: 1.0
  notifiers:
    - mobile_app_michaels_iphone

garage_open:
  name: Garage Door left open
  done_message: Door closed!
  entity_id: cover.garage
  state: "open"
  can_acknowledge: true
  repeat: 15
  skip_first: true
  data:
    push:
      category: "garage_alert"
  notifiers:
    - mobile_app_michaels_iphone