water_leak:
  name: Water Leak Detected
  done_message: All Dry!
  entity_id: group.leak_sensors
  state: "on"
  repeat: 30
  can_acknowledge: true
  data:
    url: /lovelace/leak-sensors
    push:
      category: "acknowledge_leak"
      sound:
        name: "US-EN-Alexa-Water-Detected-Generic.wav"
        critical: 1
        volume: 1.0
  notifiers:
    - mobile_app_michaels_iphone

