- platform: template
  covers:
    esp_garage_door_template:
      device_class: garage
      unique_id: esp_garage_door
      friendly_name: "ESP Garage Door"
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.esp_garage_door
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.esp_garage_door
      position_template: "{{ is_state('binary_sensor.esp_garage_door_state', 'on') }}"
