adults:
  name: Adults
  entities:
    - person.mike
    - person.tiff

exterior_lights:
  name: Exterior Lights
  entities:
    - switch.front_porch
    - switch.side_door

leak_sensors:
  name: Leak Sensors
  entities:
    - binary_sensor.leak_detector
    - binary_sensor.water_leak_laundry
    - binary_sensor.water_leak_kitchen
    - binary_sensor.water_leak_furnace_room