pupper_home:
  name: Puppy Home
  initial: on
  icon: mdi:dog

nap_mode:
  name: Nap Mode
  initial: on
  icon: mdi:sleep

quite_mode:
  name: Quite Mode
  initial: off
  icon: mdi:bell-off

vacation_mode:
  name: Vacation Mode
  initial: off
  icon: mdi:palm-tree