pupper_home:
  name: Puppy Home
  initial: on
  icon: mdi:dog

quite_mode:
  name: Quite Mode
  initial: off
  icon: mdi:bell-off

vacation_mode:
  name: Vacation Mode
  initial: off
  icon: mdi:palm-tree