- name: nursery_led_on
  entities:
    light.nursery_led_strip:
      state: on
      brightness_pct: 100
      rgb_color: [255, 191, 0]
      color_temp: 311

- name: nursery_led_on_low
  entities:
    light.nursery_led_strip:
      state: on
      brightness_pct: 80
      rgb_color: [255, 127, 0]

- name: baby_nap_on
  entities:
    switch.nursery_white_noise: on
    light.nursery_led_strip: off
    light.nursery_light: off

- name: baby_nap_off
  entities:
    switch.nursery_white_noise: off
    switch.nursery_fan: off
    switch.nursery_humidifier: off
