- alias: Water Leak
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.leak_detector
      - binary_sensor.water_leak_furnace_room
      - binary_sensor.water_leak_kitchen
      - binary_sensor.water_leak_laundry
    to:  'on'
  action:
    - service: notify.mobile_app_michaels_iphone
      data:
        title: 'Water Leak Detected'
        message: >
          Leak detected in {{ trigger.to_state.name }}
        data:
          url: /lovelace/leak-sensors
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0