- alias: Presence Notifications Home
  trigger:
    platform: state
    entity_id: person.tiff
  condition:
    - condition: state
      entity_id: person.mike
      state: 'not_home'
  action:
    service: notify.mobile_app_michaels_iphone
    data:
      title: "HASS Presence Notification"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} is {% if trigger.to_state.state == 'home' %}back{% else %}away{% endif %}.

- alias: Weather Alert
  trigger:
    platform: state
    entity_id:
      - sensor.warnings
      - sensor.watches
      - sensor.advisories
      - sensor.statements
      - sensor.endings
    from: ""
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ trigger.to_state.state != '' }}"
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    service: notify.mobile_app_michaels_iphone
    data:
      title: "Weather Alert: {{ trigger.to_state.state }}"
      message: >
          {{ trigger.to_state.attributes['alert detail'] }}