- alias: Presence Notifications Home
  id: presence_notification_home
  trigger:
    - platform: state
      entity_id: person.tiff
      from: "not_home"
      to: "home"
    - platform: state
      entity_id: person.tiff
      from: "home"
      to: "not_home"
  condition:
    - condition: state
      entity_id: person.mike
      state: "not_home"
  action:
    service: notify.mobile_app_michaels_iphone
    data:
      title: "HASS Presence Notification"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} is {% if trigger.to_state.state == 'home' %}back{% else %}away{% endif %}.

- alias: Weather Alert
  id: weather_alert
  trigger:
    platform: state
    entity_id:
      - sensor.warnings
      - sensor.watches
      - sensor.advisories
      - sensor.statements
      - sensor.endings
    from: ""
  condition:
    condition: and
    conditions:
      - "{{ trigger.to_state.state != '' }}"
      - "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    service: notify.mobile_app_michaels_iphone
    data:
      title: "Weather Alert: {{ trigger.to_state.state }}"
      message: >
        {{ trigger.to_state.attributes['alert detail'] }}

- alias: Doorbell activated
  id: doorbell_activated
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: group.adults
      state: "home"
  action:
    - service: notify.adults
      data:
        title: "Ding Dong"
        message: "Someone is at the front door"
    - service: media_player.media_pause
      entity_id: media_player.living_room_tv
    - choose:
        # Halloween Condition
        - conditions:
            - condition: template
              value_template: "{{ now().month == 10 and now().day == 31 }}"
            - condition: state
              entity_id: group.adults
              state: "home"
          sequence:
            - service: script.sonos_say
              data:
                sonos_entity: media_player.sonos_living_room
                volume: 0.25
                message: "Trick or treat!"
                delay:
                  seconds: 4
        # General Condition
        - conditions:
            - condition: state
              entity_id: input_boolean.nap_mode
              state: "on"
          sequence:
            - service: script.sonos_group_say
              data:
                sonos_master: media_player.sonos_living_room
                sonos_entities: media_player.sonos_basement
                volume: 0.25
                message: "Someone is at the door"
                delay:
                  seconds: 4
    - delay:
        # Debounce this from happening
        # again quickly.
        seconds: 30

- alias: Return Home Annoucement
  id: return_home_annoucement
  trigger:
    platform: zone
    entity_id: person.mike
    zone: zone.arriving_home
    event: enter
  condition:
    - condition: state
      entity_id: person.tiff
      state: "home"
    - condition: state
      entity_id: sensor.michaels_iphone_activity
      state: "Automotive"
    - condition: state
      entity_id: input_boolean.nap_mode
      state: "off"
  action:
    - service: notify.mobile_app_tiffanys_iphone
      data:
        title: "Mike is almost home"

- alias: Tiff Returning Home Notification
  id: tiff_return_home_notification
  trigger:
    platform: zone
    entity_id: person.tiff
    zone: zone.home
    event: enter
  condition:
    - condition: state
      entity_id: person.mike
      state: "home"
      for:
        minutes: 10
  action:
    - service: notify.mobile_app_michaels_iphone
      data:
        title: "Tiff is returning home"
        message: "Tiff has entered the home zone"

- alias: Update notification
  id: update_notification
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: "off"
      to: "on"
  action:
    - service: notify.mobile_app_michaels_iphone
      data:
        message: "There is a new Home Assistant release available."
