- alias: Presence Notifications Home
  trigger:
    platform: state
    entity_id: device_tracker.tiffs_phone
    from: 'not_home'
    to: 'home'
  action:
    service: notify.mobile_app_michaels_iphone
    data_template:
      title: "HASS Presence Notification"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} is {% if trigger.to_state.state == 'home' %}back{% else %}away{% endif %}.

- alias: Presence Notifications Away
  trigger:
    platform: state
    entity_id: device_tracker.tiffs_phone
    from: 'home'
    to: 'not_home'
  action:
    service: notify.mobile_app_michaels_iphone
    data_template:
      title: "HASS Presence Notification"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} is {% if trigger.to_state.state == 'home' %}back{% else %}away{% endif %}.

- alias: Weather Alert
  trigger:
    platform: state
    entity_id:
      - sensor.warnings
      - sensor.watches
      - sensor.advisories
      - sensor.statements
      - sensor.endings
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != '' }}"
  action:
    service: notify.mobile_app_michaels_iphone
    data_template:
      title: "Weather Alert: {{ trigger.to_state.state }}"
      message: >
          {{ trigger.to_state.attributes['alert detail'] }}

- alias: Bedroom Comfort when arrival past bedtime
  trigger:
    platform: state
    entity_id: group.adults
    from: 'not_home'
    to: 'home'
  condition:
    - condition: time
      after: '22:00:00'
      before: '05:00:00'
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.switch3
      - switch.switch4

- alias: Bedroom Humidifer On Evenings
  trigger:
    - platform: time
      at: '19:45:00'
  condition:
    - condition: state
      entity_id: group.adults
      state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.switch3
      - switch.switch4

- alias: Humidifier Off Weekday Morning
  trigger:
    - platform: time
      at: '08:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.switch3
      - switch.switch4

- alias: Humidifier Off Weekend Morning
  trigger:
    - platform: time
      at: '08:00:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.switch3
      - switch.switch4

- alias: Healthchecks Cron Job
  trigger:
    platform: time_pattern
    minutes: '/15'
  action:
    service: shell_command.healthchecks_io

- alias: Turn of space heater after working
  trigger:
    - platform: time
      at: '17:00:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.switch1
