- alias: Presence Notifications Home
  trigger:
    platform: state
    entity_id: device_tracker.tiffs_phone
    from: 'not_home'
    to: 'home'
  action:
    service: notify.mobile_app_michaels_iphone
    data_template:
      title: "HASS Presence Notification"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} is {% if trigger.to_state.state == 'home' %}back{% else %}away{% endif %}.

- alias: Presence Notifications Away
  trigger:
    platform: state
    entity_id: person.tiff
    from: 'home'
    to: 'not_home'
  condition:
    - condition: state
      entity_id: person.mike
      state: 'not_home'
  action:
    service: notify.mobile_app_michaels_iphone
    data_template:
      title: "HASS Presence Notification"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} is {% if trigger.to_state.state == 'home' %}back{% else %}away{% endif %}.

- alias: Lock Status Change
  trigger:
      - platform: state
        entity_id: lock.front_door
        from: 'unlocked'
        to: 'locked'
      - platform: state
        entity_id: lock.front_door
        from: 'locked'
        to: 'unlocked'
  condition:
    - condition: state
      entity_id: person.mike
      state: 'not_home'
  action:
    service: notify.mobile_app_michaels_iphone
    data_template:
      title: "Front Lock"
      message: >
        {% set user_slot = states("sensor.front_door_lock_last_user_code") %}
        {% if user_slot == "1" %}
        {% set user = "Mike" %}
        {% elif user_slot == "2" %}
        {% set user = "Dad" %}
        {% elif user_slot == "3" %}
        {% set user = "Brendan" %}
        {% elif user_slot == "4" %}
        {% set user = "Tiff" %}
        {% elif user_slot == "5" %}
        {% set user = "Lisa" %}
        {% endif %}
        {{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}{% if user is defined %} by {{user}}{% endif %}

- alias: Secure House Evenings
  trigger:
    - platform: time
      at: '22:00:00'
  action:
    - service: cover.close_cover
      entity_id: cover.garage
    - service: lock.lock
      entity_id: lock.front_door

- alias: Weather Alert
  trigger:
    platform: state
    entity_id:
      - sensor.warnings
      - sensor.watches
      - sensor.advisories
      - sensor.statements
      - sensor.endings
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != '' }}"
  action:
    service: notify.mobile_app_michaels_iphone
    data_template:
      title: "Weather Alert: {{ trigger.to_state.state }}"
      message: >
          {{ trigger.to_state.attributes['alert detail'] }}

- alias: Bedroom Comfort when arrival past bedtime
  trigger:
    platform: state
    entity_id: group.adults
    from: 'not_home'
    to: 'home'
  condition:
    - condition: time
      after: '22:00:00'
      before: '05:00:00'
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.master_white_noise

- alias: Bedroom White Noise On Evenings
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: state
      entity_id: group.adults
      state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.master_white_noise

- alias: Bedroom White Noise Off Morning
  trigger:
    - platform: time
      at: '08:30:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.master_white_noise

- alias: Nursery White Noise Off Morning
  trigger:
    - platform: time
      at: '07:30:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.nursery_white_noise

- alias: Healthchecks Cron Job
  trigger:
    platform: time_pattern
    minutes: '/15'
  action:
    service: shell_command.healthchecks_io

- alias: Spare Bedroom Fan Toggle
  trigger:
    platform: event
    event_type: zha_event
    event_data:
        device_ieee: "00:15:8d:00:03:ce:96:86"
        command: "click"
        args:
          click_type: "single"
          #attribute_name: "on_off",
          #value: true
  action:
    service: homeassistant.toggle
    entity_id:
      - switch.bedroom_fan
