- alias: Presence Notifications Home
  trigger:
    platform: state
    entity_id: person.tiff
  condition:
    - condition: state
      entity_id: person.mike
      state: 'not_home'
    - "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    service: notify.mobile_app_michaels_iphone
    data:
      title: "HASS Presence Notification"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} is {% if trigger.to_state.state == 'home' %}back{% else %}away{% endif %}.

- alias: Weather Alert
  trigger:
    platform: state
    entity_id:
      - sensor.warnings
      - sensor.watches
      - sensor.advisories
      - sensor.statements
      - sensor.endings
    from: ""
  condition:
    condition: and
    conditions:
      - "{{ trigger.to_state.state != '' }}"
      - "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    service: notify.mobile_app_michaels_iphone
    data:
      title: "Weather Alert: {{ trigger.to_state.state }}"
      message: >
          {{ trigger.to_state.attributes['alert detail'] }}

- alias: Doorbell activated
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: group.adults
      state: 'home'
  action:
    - service: notify.adults
      data:
        title: "Ding Dong"
        message: "Someone is at the front door"
    - choose:
      - conditions:
        - condition: state
          entity_id: input_boolean.nap_mode
          state: 'on'
        sequence:
          - service: script.sonos_say
            data:
              sonos_entity: media_player.sonos_living_room
              volume: 0.20
              message: "Someone is at the door"
              delay: 4
          - service: script.sonos_say
            data:
              sonos_entity: media_player.sonos_basement
              volume: 0.20
              message: "Someone is at the door"
              delay: 4
    - delay:
        # Debounce this from happening
        # again quickly.
        minutes: 3