- alias: Presence Notifications Home
  id: presence_notification_home
  trigger:
    - platform: state
      entity_id: person.tiff
      to: ~
  condition:
    - condition: state
      entity_id: person.mike
      state: "not_home"
      for:
        minutes: 10
  action:
    service: notify.mobile_app_michaels_iphone
    data:
      title: "HASS Presence Notification"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} is {% if trigger.to_state.state == 'home' %}back{% else %}away{% endif %}.
      data:
        tag: "tiff-presence-notification"
        group: "presence-notification"

- alias: Weather Alert
  id: weather_alert
  trigger:
    platform: state
    entity_id:
      - sensor.warnings
      - sensor.watches
      - sensor.advisories
      - sensor.statements
      - sensor.endings
    from: ""
  condition:
    and:
      - "{{ trigger.to_state.state != '' }}"
      - "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    service: notify.mobile_app_michaels_iphone
    data:
      title: "Weather Alert: {{ trigger.to_state.state }}"
      message: >
        {{ trigger.to_state.attributes['alert detail'] }}

- alias: Doorbell activated
  id: doorbell_activated
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: group.adults
      state: "home"
  action:
    - choose:
        - conditions:
            - condition: state
              state: "home"
              entity_id: group.adults
          sequence:
            - repeat:
                for_each: >
                  {{ states.person | selectattr('state', 'eq', 'home') | map(attribute='attributes.notifier') | list}}
                sequence:
                  - service: "{{ repeat.item }}"
                    data:
                      title: "Ding Dong"
                      message: "Someone is at the front door"
                      data:
                        tag: "doorbell-notification"
                        group: "doorbell-group"
    - service: media_player.media_pause
      entity_id: media_player.living_room_tv
    - choose:
        # Halloween Condition
        - conditions:
            - condition: template
              value_template: "{{ now().month == 10 and now().day == 31 }}"
            - condition: state
              entity_id: input_boolean.nap_mode
              state: "off"
          sequence:
            - service: script.sonos_say
              data:
                sonos_entity: media_player.sonos_living_room
                volume: 0.25
                message: "Trick or treat!"
                delay:
                  seconds: 4
    - delay:
        # Debounce this from happening
        # again quickly.
        seconds: 30

- alias: Return Home Annoucement
  id: return_home_annoucement
  trigger:
    platform: zone
    entity_id: device_tracker.tesla_location
    zone: zone.home
    event: enter
  condition:
    - condition: state
      entity_id: person.tiff
      state: "home"
    - condition: state
      entity_id: input_boolean.nap_mode
      state: "on"
  action:
    - service: notify.mobile_app_tiffanys_iphone
      data:
        title: "Mike is almost home"
        message: "Keep Stella Quiet"

- alias: Tiff Returning Home Notification
  id: tiff_return_home_notification
  trigger:
    platform: zone
    entity_id: person.tiff
    zone: zone.home
    event: enter
  condition:
    - condition: state
      entity_id: person.mike
      state: "home"
      for:
        minutes: 10
  action:
    - service: notify.mobile_app_michaels_iphone
      data:
        title: "Tiff is returning home"
        message: "Tiff has entered the home zone"
        data:
          tag: "tiff-return-home"
          group: "presence-notification"

- alias: Update notification
  id: update_notification
  trigger:
    - platform: state
      entity_id: binary_sensor.docker_hub_update_available
      to: "on"
  action:
    - service: notify.mobile_app_michaels_iphone
      data:
        message: "There is a new Home Assistant release available."

- alias: Presence Arriving
  id: general_presence_notification_home
  trigger:
    - platform: state
      entity_id:
        - person.bumpa
        - person.lisa
      from: "not_home"
      to: "home"
  condition:
    - condition: state
      entity_id: person.mike
      state: "home"
  action:
    service: notify.mobile_app_michaels_iphone
    data:
      title: "HASS Presence Notification"
      message: >
        {{ trigger.to_state.attributes.friendly_name }} is arriving
      data:
        tag: "person-presence-notification"
        group: "presence-notification"
