- alias: Night light Tradfri Trigger On
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:0d:6f:ff:fe:a6:af:1d"
      command: "on"
  action:
    - wait_template: '{{ not is_state("light.nursery_led_strip", "unavailable") }}'
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.nap_mode
              state: "off"
          sequence:
            - service: scene.turn_on
              entity_id: scene.nursery_led_on
        - conditions:
            - condition: state
              entity_id: input_boolean.nap_mode
              state: "on"
          sequence:
            - service: scene.turn_on
              entity_id: scene.nursery_led_on_low

- alias: Night light Tradfri Trigger Off
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:0d:6f:ff:fe:a6:af:1d"
      command: "off"
  action:
    - wait_template: '{{ not is_state("light.nursery_led_strip", "unavailable") }}'
    - service: light.turn_off
      data:
        entity_id:
          - light.nursery_led_strip

- alias: Baby light off at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id:
      - light.nursery_led_strip

- alias: Nap Mode Button Toggle
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: "00:15:8d:00:03:50:26:b5"
        command: "attribute_updated"
        args:
          value: 1
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionID: nap_time
        sourceDeviceID: michaels_iphone
  action:
    - service: homeassistant.toggle
      entity_id:
        - input_boolean.nap_mode
    - delay:
        seconds: 1

- alias: Nap Accessories On
  trigger:
    platform: state
    entity_id: input_boolean.nap_mode
    from: "off"
    to: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.baby_nap_on

- alias: Nap Accessories Off
  trigger:
    platform: state
    entity_id: input_boolean.nap_mode
    from: "on"
    to: "off"
  action:
    - choose:
        - conditions:
            - condition: sun
              before: sunrise
          sequence:
            - service: scene.turn_on
              entity_id: scene.baby_nap_off
            - wait_template: '{{ not is_state("light.nursery_led_strip", "unavailable") }}'
            - service: scene.turn_on
              entity_id: scene.nursery_led_on
      default:
        - service: scene.turn_on
          entity_id: scene.baby_nap_off
        - service: homeassistant.turn_on
          entity_id: light.nursery_light

- alias: Nursery Humidifer on evenings
  trigger:
    platform: state
    entity_id: input_boolean.nap_mode
    from: "off"
    to: "on"
  condition:
    - condition: and
      conditions:
        - condition: time
          after: " 17:00:00"
        - condition: template
          # Only care about November - March
          value_template: "{{ now().month >= 11 or now().month <= 3 }}"
  action:
    - service: homeassistant.turn_on
      entity_id: switch.nursery_humidifier

- alias: Nursey Fan On if needed
  trigger:
    platform: state
    entity_id: input_boolean.nap_mode
    from: "off"
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: switch.nursery_fan
  condition:
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.temperature # Outside forecast
          above: 20
        - condition: numeric_state
          entity_id: sensor.kid_s_room_temperature #Acutal Room Temp
          above: 25

- alias: Nursey Fan on if temperature rises
  trigger:
    platform: numeric_state
    entity_id: sensor.kid_s_room_temperature
    above: 25
  condition:
    - condition: state
      entity_id: input_boolean.nap_mode
      state: "on"
    - condition: state
      entity_id: switch.nursery_fan
      state: "off"
  action:
    - service: homeassistant.turn_on
      entity_id: switch.nursery_fan
    - service: notify.mobile_app_michaels_iphone
      data:
        title: "Nursery Event"
        message: "Nursey Temperature Fan Trigger"

- alias: Nursey Low Temperature Warning
  trigger:
    platform: numeric_state
    entity_id: sensor.kid_s_room_temperature
    below: 18
  condition:
    - condition: state
      entity_id: input_boolean.nap_mode
      state: "on"
  action:
    - service: notify.adults
      data:
        title: "Nursery Low Temperature Warning"
        message: "Temperature droped to {{ states('sensor.kid_s_room_temperature') }}"
    - service: homeassistant.turn_off
      entity_id: switch.nursery_fan

- alias: Turn nursery off if forgotten
  trigger:
    - platform: state
      entity_id: binary_sensor.kid_s_room
      from: "on"
      to: "off"
  condition:
    - condition: time
      after: "08:30:00"
    - condition: state
      entity_id: input_boolean.nap_mode
      state: "off"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.nap_mode
    - service: homeassistant.turn_off
      entity_id: light.nursery_led_strip
    - delay: 10
    - service: homeassistant.turn_off
      entity_id: light.nursery_light

- alias: Turn off nap mode via light switch
  trigger:
    - platform: state
      entity_id: light.nursery_light
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.nap_mode
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.nap_mode
