- alias: Night light Tradfri Trigger On
  trigger:
    platform: event
    event_type: zha_event
    event_data:
        device_ieee: "00:0d:6f:ff:fe:a6:af:1d"
        command: "on"
  action:
    - wait_template: '{{ not is_state("light.quotra_led_strip_1", "unavailable") }}'
    - service: scene.turn_on
      entity_id: scene.baby_night_full

- alias: Night light Tradfri Trigger Off
  trigger:
    platform: event
    event_type: zha_event
    event_data:
        device_ieee: "00:0d:6f:ff:fe:a6:af:1d"
        command: "off"
  action:
    - wait_template: '{{ not is_state("light.quotra_led_strip_1", "unavailable") }}'
    - service: light.turn_off
      data:
        entity_id:
        - light.baby_led_strip

- alias: Baby light off at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id:
      - light.baby_led_strip

- alias: Nap Mode Button Toggle
  trigger:
    platform: event
    event_type: zha_event
    event_data:
        device_ieee: "00:15:8d:00:03:50:26:b5"
        command: "attribute_updated"
        args:
          value: 1
  action:
    - service: homeassistant.toggle
      entity_id:
        - input_boolean.nap_mode
    - delay:
        seconds: 1

- alias: Nap Accessories On
  trigger:
    platform: state
    entity_id: input_boolean.nap_mode
    from:  'off'
    to:  'on'
  action:
    - service: scene.turn_on
      entity_id: scene.baby_nap_on

- alias: Nap Accessories Off
  trigger:
    platform: state
    entity_id: input_boolean.nap_mode
    from:  'on'
    to:  'off'
  action:
    - service: scene.turn_on
      entity_id: scene.baby_nap_off
    - service: homeassistant.turn_off
      entity_id: switch.nursery_fan

- alias: Nursey Fan On if needed
  trigger:
    platform: state
    entity_id: input_boolean.nap_mode
    from:  'off'
    to:  'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.nursery_fan
  condition:
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.temperature # Outside forecast
          above: 20
        - condition: numeric_state
          entity_id: sensor.kid_s_room_temperature #Acutal Room Temp
          above: 25

- alias: Nursey Fan on if temperature rises
  trigger:
    platform: numeric_state
    entity_id: sensor.kid_s_room_temperature
    above: 25
  condition:
    - condition: state
      entity_id: input_boolean.nap_mode
      state: 'on'
    - condition: state
      entity_id: switch.nursery_fan
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.nursery_fan
    - service: notify.mobile_app_michaels_iphone
      data:
        title: "Nursery Event"
        message: "Nursey Temperature Fan Trigger"

- alias: Nursey Low Temperature Warning
  trigger:
    platform: numeric_state
    entity_id: sensor.kid_s_room_temperature
    below: 21
  condition:
    - condition: state
      entity_id: input_boolean.nap_mode
      state: 'on'
  action:
    - service: notify.adults
      data:
        title: "Nursery Low Temperature Warning"
        message: "Temperature droped to {{ states('sensor.kid_s_room_temperature') }}"
        clickAction: '/lovelace/nursery'
    - service: homeassistant.turn_off
      entity_id: switch.nursery_fan

- alias: Nursery White Noise Off Morning
  trigger:
    - platform: time
      at: '07:30:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - input_boolean.nap_mode