- alias: Exterior Christmas Lights on Sunset
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: and
      conditions:
        - condition: template
          # Only care about November - January
          value_template: "{{ now().month >= 11 or now().month <= 1 }}"
  action:
    service: homeassistant.turn_on
    entity_id: switch.exterior_xmas_lights

- alias: Exterior Christmas Lights off evenings
  trigger:
    - platform: time
      at: "23:30:00"
    - platform: sun
      event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: switch.exterior_xmas_lights

- alias: Tree lights on when living room occupied
  trigger:
    platform: state
    entity_id: binary_sensor.living_room
  condition:
    condition: time
    after: "06:30:00"
    before: "23:30:00"
  action:
    service: homeassistant.turn_{{ trigger.to_state.state }}
    entity_id: switch.christmas_tree
