- alias: Bedroom Comfort when arrival past bedtime
  trigger:
    platform: state
    entity_id: group.adults
    from: 'not_home'
    to: 'home'
  condition:
    - condition: time
      after: '22:00:00'
      before: '07:00:00'
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.master_white_noise

- alias: Bedroom White Noise On Evenings
  trigger:
    - platform: time
      at: '22:00:00'
  condition:
    - condition: state
      entity_id: group.adults
      state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.master_white_noise

- alias: Bedroom Comfort if in bed early
  trigger:
    - platform: state
      entity_id: sensor.tiffanys_iphone_battery_state
      to: 'charging'
  condition:
    - "{{ trigger.to_state.state != 'charging' }}"
    - condition: time
      after: '21:00:00'
    - condition: state
      entity_id: binary_sensor.bedroom
      state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.master_white_noise

- alias: Bedroom White Noise Off Morning
  trigger:
    - platform: time
      at: '08:30:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.master_white_noise

- alias: Spare Bedroom Fan Toggle
  trigger:
    platform: event
    event_type: zha_event
    event_data:
        device_ieee: "00:15:8d:00:03:ce:96:86"
        command: "click"
        args:
          click_type: "single"
  action:
    service: homeassistant.toggle
    entity_id:
      - switch.bedroom_fan
