- alias: Exterior Lights on Evenings
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.exterior_lights

- alias: Exterior Lights off Night, or sunrise
  trigger:
    - platform: time
      at: "23:30:00"
    - platform: sun
      event: sunrise
  action:
    - service: homeassistant.turn_off
      entity_id: group.exterior_lights

- alias: Keep Exterior Lights off overnight if turned on outside normal hours
  trigger:
    - platform: state
      entity_id: group.exterior_lights
      to: "on"
      for:
        hours: 1
  condition:
    - condition: and
      conditions:
        - condition: time
          after: "23:30:00"
          before: "10:00:00" # Time condition to span midnight reset
        - condition: sun
          before: sunrise
  action:
    - service: homeassistant.turn_off
      entity_id: group.exterior_lights

- alias: Keep Exterior Lights off during daylight
  trigger:
    platform: state
    entity_id: group.exterior_lights
    to: "on"
    for:
      minutes: 30
  condition:
    - condition: state
      entity_id: sun.sun
      state: "above_horizon"
  action:
    - service: homeassistant.turn_off
      entity_id: group.exterior_lights

- alias: Sync Exterior Lights
  trigger:
    platform: state
    to: "on"
    entity_id:
      # If the front porch goes on/off update the rest
      # of the group
      - switch.front_porch
  action:
    service: >
      homeassistant.turn_on
    entity_id: group.exterior_lights

- alias: Turn on external lights, multiple triggers
  trigger:
    - platform: state
      entity_id: cover.garage
      to: "open"
    - platform: state
      entity_id: lock.front_door
      to: "unlocked"
    - platform: zone
      entity_id:
        - person.mike
        - person.tiff
      zone: zone.home
      event: enter
  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
  action:
    - service: homeassistant.turn_on
      entity_id: group.exterior_lights
