- alias: Exterior Lights on Evenings
  trigger:
      platform: sun
      event: sunset
  action:
      service: homeassistant.turn_on
      entity_id: group.exterior_lights

- alias: Exterior Lights off Night
  trigger:
    platform: time
    at: '23:30:00'
  action:
    - service: homeassistant.turn_off
      entity_id: group.exterior_lights

- alias: Keep Exterior Lights of overnight if turned on
  trigger:
    platform: state
    entity_id: group.exterior_lights
    to: 'on'
    for:
      hours: 1
  condition:
    - condition: and
      conditions:
        - condition: time
          after: "00:00:00"
          before: "10:00:00" # Time condition to span midnight reset
        - condition: sun
          before: sunrise
  action:
    - service: homeassistant.turn_off
      entity_id: group.exterior_lights

- alias: Keep Exterior Lights off during daylight
  trigger:
    platform: state
    entity_id: group.exterior_lights
    to: 'on'
    for:
      minutes: 30
  condition:
    condition: sun
    before: sunset
  action:
    - service: homeassistant.turn_off
      entity_id: group.exterior_lights

- alias: Sync Exterior Lights
  trigger:
    platform: state
    entity_id:
      # If the front porch goes on/off update the rest
      # of the group
      - switch.front_porch
  action:
    service: >
      homeassistant.turn_{{ trigger.to_state.state }}
    entity_id: group.exterior_lights

- alias: Turn on external lights if garage opens after sunset
  trigger:
    - platform: state
      entity_id: cover.garage
      to: open
  condition:
    - condition: sun
      after: sunset
  action:
    - service: homeassistant.turn_on
      entity_id: group.exterior_lights
  