- alias: iOS Toggle Garage
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionID: A006F7CC-AA85-4CFC-982D-8456FFB7F042
      sourceDeviceID: michaels_iphone
  action:
    service: cover.toggle
    entity_id:
      - cover.garage

- alias: iOS Lock Front Door
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionID: F11CF38C-60A6-42FD-B506-42DB188E040D
      sourceDevicePermanentID: F9567FD2-507A-4878-93C2-319D48F3BE0C
  action:
    service: lock.lock
    entity_id:
      - lock.front_door

- alias: iOS Unlock Front Door
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionID: A3D3D16D-A66B-40E2-B9CD-E993AD1503C0
      sourceDevicePermanentID: F9567FD2-507A-4878-93C2-319D48F3BE0C
  action:
    service: lock.unlock
    entity_id:
      - lock.front_door

- alias: iOS Toggle Nap Mode
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionID: C233029C-B43E-4ECF-A5FB-FCEE2D362B03
      sourceDeviceID: michaels_iphone
  action:
    service: homeassistant.toggle
    entity_id: input_boolean.nap_mode