- alias: iOS Toggle Garage
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionID: 8426A6D1-BB9D-4778-8190-93C29E7B3263
      sourceDeviceID: michaels_iphone
  action:
    service: cover.toggle
    entity_id:
      - cover.garage

- alias: iOS Lock Front Door
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionID: 99853176-4FEB-4DFD-9C77-99082C072A01
      sourceDeviceID: michaels_iphone
  action:
    service: lock.lock
    entity_id:
      - lock.front_door

- alias: iOS Unlock Front Door
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionID: 8B96F36B-4865-48BA-A9F9-45B5D76AE84A
      sourceDeviceID: michaels_iphone
  action:
    service: lock.unlock
    entity_id:
      - lock.front_door

- alias: Trigger sensor updates for Tiff's phone during bedtime period
  trigger:
    platform: time_pattern
    hours: "21"
    minutes: "/5"
  condition:
    - condition: state
      entity_id: person.tiff
      state: 'home'
    - condition: time
      after: '21:30'
      before: '22:00'
  action:
    - service: notify.mobile_app_tiffanys_iphone
      data:
        message: "request_location_update"