- alias: External Lights on Evenings
  trigger:
     platform: sun
     event: sunset
  action:
     service: scene.turn_on
     entity_id:
       - scene.exterior_lights_on

- alias: Front Porch Off Night
  trigger:
    platform: time
    at: '23:30:00'
  action:
    - service: scene.turn_on
      entity_id:
        - scene.exterior_lights_off
