- alias: External Lights on Evenings
  trigger:
     platform: sun
     event: sunset
  action:
     service: scene.turn_on
     entity_id:
       - scene.exterior_lights_on

- alias: External Lights off Night
  trigger:
    platform: time
    at: '23:30:00'
  action:
    - service: scene.turn_on
      entity_id:
        - scene.exterior_lights_off

- alias: Keep External Lights of During Daty
  trigger:
    platform: state
    entity_id:
      - switch.front_porch
      - switch.side_door
    to: 'on'
    for:
      minutes: 30
  condition:
    condition: state
    entity_id: sun.sun
    state: 'above_horizon'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - switch.front_porch
        - switch.side_door