- alias: Exterior Lights on Evenings
  trigger:
     platform: sun
     event: sunset
  action:
     service: homeassistant.turn_on
     entity_id: group.exterior_lights

- alias: Exterior Lights off Night
  trigger:
    platform: time
    at: '23:30:00'
  action:
    - service: homeassistant.turn_off
      entity_id: group.exterior_lights

- alias: Keep Exterior Lights off during daylight
  trigger:
    platform: state
    entity_id: group.exterior_lights
    to: 'on'
    for:
      minutes: 30
  condition:
    condition: state
    entity_id: sun.sun
    state: 'above_horizon'
  action:
    - service: homeassistant.turn_off
      entity_id: group.exterior_lights

- alias: Sync Exterior Lights
  trigger:
    platform: state
    entity_id:
      # If the front porch goes on/off update the rest
      # of the group
      - switch.front_porch
  action:
    service: >
      homeassistant.turn_{{ trigger.to_state.state }}
    entity_id: group.exterior_lights