- alias: Lights ON when sunsets -1 hr earlier and anyone home
  trigger:
     platform: sun
     event: sunset
     offset: "-01:00:00"
  condition:
     condition: state
     entity_id: group.all_devices
     state: 'home'
  action:
     service: light.turn_on
     entity_id:
         - light.living
         - switch.switch2

- alias: Lights OFF when bedtime work day
  trigger:
     platform: time
     at: '23:15:00'
  action:
     - service: homeassistant.turn_off
       entity_id:
           - group.all_lights
           - switch.switch2
  condition:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu

- alias: Lights OFF weekend bedtime
  trigger:
    platform: state
    entity_id: media_player.family_room_tv
    to: 'unavailable'
  condition:
    - condition: time
      after: '23:00:00'
      before: '03:00:00'
      weekday:
        - fri
        - sat
        - sun
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights
        - switch.front_hall
        - switch.kitchen_light
        - switch.switch2

- alias: OFF nobody home, no pupper
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.pupper_home
      state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.all_lights
        - switch.switch1
        - switch.switch2
        - switch.switch3

- alias: OFF nobody home, pupper home
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.pupper_home
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.front_hall
        - light.kitchen
        - light.right_bottom
        - light.tv_light
        - switch.switch1
        - switch.switch2
        - switch.switch3
    - service: homeassistant.turn_on
      entity_id:
        - light.right_top
        - light.left_top

- alias: Lights ON when arrival past sunset
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-1:00:00"
      - condition: sun
        before: sunrise
  action:
      service: homeassistant.turn_on
      entity_id:
        - group.all_lights
        - switch.front_hall
        - switch.kitchen_light
        - switch.switch2

- alias: Christmas Tree on evenings
  trigger:
    platform: time
    at: '18:00:00'
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.switch2

- alias: Outdoor Christmas Lights on
  trigger:
     platform: sun
     event: sunset
  action:
      service: homeassistant.turn_on
      entity_id:
        - switch.switch4

- alias: Outdoor Christmas Lights off
  trigger:
      platform: time
      at: '22:45:00'
  action:
      service: homeassistant.turn_off
      entity_id:
        - switch.switch4
