- alias: Ask if Pupper Home after Dark
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    - condition: state
      entity_id: group.adults
      state: 'not_home'
  action:
    service: notify.mobile_app_michaels_iphone
    data:
      message: "Is the puppy home alone?"
      data:
        push:
          category: 'pupper_home'
          
- alias: Pupper Question Event yes
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: 'PUPPER_HOME'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.pupper_home

- alias: Pupper Question Event No
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: 'PUPPER_NOT_HOME'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.pupper_home
