automation:
  - alias: "Faux device tracker for twins"
    id: alarm_device_tracker_for_twins
    trigger:
      - platform: state
        entity_id: input_boolean.girls_home_override
        to: ~
    condition:
      condition: template
      value_template: "{{ trigger.to_state.state in ['off', 'on'] }}"
    action:
      - service: device_tracker.see
        data_template:
          dev_id: faux_girls_home
          location_name: "{{ 'home' if 'on' == trigger.to_state.state else 'not_home' }}"
    mode: single

  - alias: Auto Arm and Disarm System
    id: alarm_arm_based_on_presence
    trigger:
      - platform: state
        entity_id:
          - group.presence_home
        to: ~
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state in ['home', 'not_home'] }}"
      - condition: state
        entity_id: binary_sensor.guests_present
        state: "off"
    action:
      - service: alarm_control_panel.alarm_{{ 'disarm' if 'home' == trigger.to_state.state else 'arm_away' }}
        target:
          entity_id: alarm_control_panel.alarmo
    mode: single

  - alias: Auto Arm Alarm Night
    id: alarm_auto_arm_night_mode
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: state
        entity_id:
          - person.mike
          - person.tiff
        state: "home"
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "disarmed"
    action:
      - service: alarm_control_panel.alarm_arm_night
        target:
          entity_id: alarm_control_panel.alarmo

  - alias: Disable Armed Night on iOS alarm wakeup
    id: alarm_disable_armed_night_ios_wakeup
    trigger:
      - platform: event
        event_type: "ios_wakeup_event"
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "armed_night"
    action:
      - service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.alarmo

  - alias: iOS Alarm Away
    id: alarm_ios_alarm_arm_away
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionID: alarm_arm_away
    action:
      - service: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.alarmo

  - alias: iOS Alarm Disarm
    id: alarm_ios_alarm_arm_disarm
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionID: alarm_disarm
    action:
      - service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.alarmo

  - alias: Lock all doors when alarm armed
    id: alarm_lock_all_doors_armed
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to:
          - armed_night
          - armed_vacation
          - armed_away
    action:
      - service: lock.lock
        entity_id:
          - lock.front_door
          - lock.side_door

  - alias: Alert armed state and garage open
    id: alarm_alert_garage_left_open
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to:
          - armed_night
          - armed_vacation
          - armed_away
    condition:
      - condition: state
        entity_id: cover.garage
        state: "open"
    action:
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "Garage Door Left Open"
          data:
            tag: "alarmo-garage-open-alert"
            actions:
              - action: "CLOSE_GARAGE"
                title: "Close Garage"
                activationMode: "background"
                authenticationRequired: true
                destructive: true
                behavior: "default"
            push:
              sound:
                name: "default"
                critical: 1
                volume: 1.0

  - alias: Save power when not home
    id: alarm_energy_saver_not_home
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to:
          - armed_night
          - armed_vacation
        id: alarm_armed
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to:
          - armed_away
        for:
          minutes: 30
        id: alarm_armed
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to: disarmed
        id: alarm_disarmed
    action:
      choose:
        - conditions:
            - condition: trigger
              id: alarm_armed
          sequence:
            - service: homeassistant.turn_off
              entity_id: switch.entertainment_switch_relay
        - conditions:
            - condition: trigger
              id: alarm_disarmed
          sequence:
            - service: homeassistant.turn_on
              entity_id: switch.entertainment_switch_relay
