automation:
  - alias: "Faux device tracker for twins"
    id: alarm_device_tracker_for_twins
    trigger:
      - platform: state
        entity_id: input_boolean.girls_home_override
        to: ~
    condition:
      condition: template
      value_template: "{{ trigger.to_state.state in ['off', 'on'] }}"
    action:
      - service: device_tracker.see
        data_template:
          dev_id: faux_girls_home
          location_name: "{{ 'home' if 'on' == trigger.to_state.state else 'not_home' }}"
    mode: single
    max_exceeded: silent

  - alias: Guests Present Reminder
    id: alarm_guests_present_reminder
    trigger:
      - platform: state
        entity_id: group.presence_home
        to: "not_home"
    condition:
      - condition: state
        entity_id: binary_sensor.guests_present
        state: "on"
    actions:
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "ðŸ›¡ï¸ Guests home, alarm not armed ðŸ›¡ï¸"

  - alias: Reminder to disable guests present
    id: 2c36b0b2-3180-40e1-9cc8-f37660cf62e7
    trigger:
      - platform: state
        entity_id: person.mike
        to: "home"
    conditions:
      - condition: state
        entity_id: binary_sensor.guests_present
        state: "on"
    actions:
      - service: notify.mobile_app_michaels_iphone
        data:
          title: "Guests Present Reminder"
          message: "Need to disable guests present?"
          data:
            url: /dashboard-security/home
            clickAction: /dashboard-security/home

  - alias: Auto Arm and Disarm System
    id: alarm_arm_based_on_presence
    triggers:
      - platform: state
        entity_id:
          - group.presence_home
        not_to:
          - "unavailable"
          - "unknown"
    conditions:
      - condition: state
        entity_id: binary_sensor.guests_present
        state: "off"
      - condition: state
        entity_id: device_tracker.faux_girls_home
        state: "not_home"
    actions:
      - service: calendar.get_events
        target:
          entity_id: calendar.house_planning
        data:
          duration:
            hours: 8
        response_variable: cal
      - if:
          - condition: template
            value_template: "{{ cal['calendar.house_planning'].events | selectattr('summary', 'contains', 'Cleaners') | list | length == 0 }}"
        then:
          - service: alarm_control_panel.alarm_{{ 'disarm' if 'home' == trigger.to_state.state else 'arm_away' }}
            target:
              entity_id: alarm_control_panel.alarmo
      - if:
          - condition: template
            value_template: "{{ trigger.to_state.state  == 'home' }}"
        then:
          - service: select.select_option
            entity_id: select.my_ecobee_current_mode
            data:
              option: home
    mode: single
    max_exceeded: silent

  - alias: Auto Arm Alarm Night
    id: alarm_auto_arm_night_mode
    triggers:
      - platform: time
        at: "00:00:00"
      - platform: time
        at: "01:00:00"
      - platform: event
        event_type: "goodnight_event"
    conditions:
      - condition: state
        entity_id:
          - person.mike
          - person.tiff
        match: any
        state: "home"
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "disarmed"
    actions:
      - parallel:
          - service: light.turn_off
            target:
              floor_id:
                - basement
                - main_floor
          - service: cover.close_cover
            entity_id: cover.garage
          - service: lock.lock
            entity_id:
              - lock.locks
      - wait_template: "{{ is_state('cover.garage', 'closed') }}"
      - service: homeassistant.turn_off
        entity_id: media_player.living_room_tv
      - wait_template: "{{ is_state('binary_sensor.basement_presence', 'off') }}"
      - service: alarm_control_panel.alarm_arm_night
        target:
          entity_id: alarm_control_panel.alarmo

  - alias: Disable Armed Night on iOS alarm wakeup
    id: alarm_disable_armed_night_ios_wakeup
    trigger:
      - platform: event
        event_type: "ios_wakeup_event"
      - platform: time
        at: "05:00:00"
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "armed_night"
    action:
      - service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.alarmo

  - alias: Lock all doors when alarm armed
    id: alarm_lock_all_doors_armed
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to:
          - arming
          - armed_night
          - armed_vacation
          - armed_away
    action:
      - service: lock.lock
        entity_id:
          - lock.front_door
          - lock.side_door

  - alias: Alert armed state and garage open
    id: alarm_alert_garage_left_open
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to:
          - arming
          - armed_night
          - armed_vacation
          - armed_away
    condition:
      - condition: state
        entity_id: cover.garage
        state: "open"
    action:
      # Snapshot the camera
      - service: camera.snapshot
        continue_on_error: true
        target:
          entity_id: camera.garage_low_resolution_channel
        data:
          filename: "/media/garage/snapshot.jpg"
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "ðŸšª Garage Door Left Open ðŸšª"
          data:
            image: "/media/local/garage/snapshot.jpg"
            tag: "alarmo-garage-open-alert"
            actions:
              - action: "CLOSE_GARAGE"
                title: "Close Garage"
                activationMode: "background"
                authenticationRequired: true
                destructive: true
                behavior: "default"
            push:
              sound:
                name: "default"
                critical: 1
                volume: 1.0

  - alias: Turn off all indoor lights when armed
    id: alarm_turn_off_all_lights
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to:
          - armed_vacation
          - armed_away
    action:
      - service: light.turn_off
        target:
          floor_id:
            - basement
            - main_floor
            - top_floor

  - alias: Turn off lights at bedtime
    id: alarm_turn_off_lights_bedtime
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to: armed_night
    action:
      - service: light.turn_off
        target:
          floor_id:
            - basement
            - main_floor

  - alias: Set Switch Status LEDs
    id: alarm_set_switch_status_leds
    mode: queued
    max: 10
    trigger:
      - platform: state
        entity_id:
          - lock.locks
          - cover.garage
          - binary_sensor.doors
        not_from:
          - "unknown"
          - "unavailable"
        not_to:
          - "unknown"
          - "unavailable"
          - "opening"
          - "closing"
      - platform: state
        entity_id: cover.garage
        to: "closing"
        id: "closing"
      - platform: state
        entity_id: cover.garage
        to: "opening"
        id: "opening"
    condition:
      - condition: state
        entity_id: group.adults
        state: "home"
      - condition: template
        value_template: "{{ has_value('cover.garage') and has_value('lock.locks') and has_value('binary_sensor.doors') }}"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: opening
            sequence:
              - service: script.blue_set_led
                data:
                  color: "0"
                  effect: "fast_rising"
                  level: 40
                  duration: "15"
                  entity_id:
                    - light.front_hall
                    - light.kitchen_light
                    - light.back_deck_light
                    - light.main_stairs
                    - light.upstairs_hall
                    - light.main_bath_light
                    - light.basement_stairs
                    - light.basement_hall
          - conditions:
              - condition: trigger
                id: closing
            sequence:
              - service: script.blue_set_led
                data:
                  color: "0"
                  effect: "fast_falling"
                  level: 40
                  duration: "15"
                  entity_id:
                    - light.front_hall
                    - light.kitchen_light
                    - light.back_deck_light
                    - light.main_stairs
                    - light.upstairs_hall
                    - light.main_bath_light
                    - light.basement_stairs
                    - light.basement_hall
        default:
          - variables:
              duration: >-
                {% if is_state('binary_sensor.doors', 'off') and is_state('cover.garage', 'closed') and is_state('lock.locks', 'locked') %}
                  30
                {% else %}
                  255
                {% endif %}
              color: >-
                {# red 0, yellow 20, green 85 #}
                {% if is_state('cover.garage', 'closed') and is_state('binary_sensor.doors', 'off') and is_state('lock.locks', 'locked') %}
                  85
                {% elif is_state('binary_sensor.doors', 'off') and is_state('cover.garage', 'closed') and is_state('lock.locks', 'unlocked') %}
                  20
                {% else %}
                  0
                {% endif %}
          - service: script.blue_set_led
            data:
              color: "{{ color }}"
              effect: "solid"
              level: 40
              duration: "{{ duration }}"
              entity_id:
                - light.front_hall
                - light.kitchen_light
                - light.back_deck_light
                - light.main_stairs
                - light.upstairs_hall
                - light.main_bath_light
                - light.basement_stairs
                - light.basement_hall

  - alias: Notify Water Shutoff Jammed
    id: b08f5491-f6f0-4c03-b8a9-14c4a4b68ac5
    triggers:
      - platform: state
        entity_id: binary_sensor.water_shutoff_valve_jammed
        to: "on"
    actions:
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "ðŸš° Water Shutoff Valve Jammed ðŸš°"
          data:
            tag: "water-shutoff-valve-jammed"
            push:
              sound:
                name: "default"
                critical: 1
                volume: 1.0

  - alias: Shut off water when leak detected and not home or overnight
    id: 7dad3c90-f96f-4976-878c-0ab3d1a6241a
    triggers:
      - platform: state
        entity_id: alarm_control_panel.water
        to:
          - triggered
        not_from:
          - "unknown"
          - "unavailable"
    conditions:
      - condition: template
        value_template: >
          {{ trigger.to_state is defined and
            trigger.to_state.attributes.open_sensors is defined and
            trigger.to_state.attributes.open_sensors.values()
              | select('ne', 'unavailable')
              | list
              | count == 0 }}
      - not:
          - condition: state
            entity_id: alarm_control_panel.alarmo
            state:
              - disarmed
    actions:
      - service: valve.close_valve
        entity_id: valve.water_shutoff

  - alias: Alert on Alarm Trigger
    id: 3fa42dee-e85e-4787-8bdd-4d0db3dd7e59
    triggers:
      - platform: state
        entity_id:
          - alarm_control_panel.master
        to:
          - "triggered"
    actions:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.to_state is defined and
                    trigger.to_state.attributes.open_sensors is defined and
                    trigger.to_state.attributes.open_sensors.values()
                      | select('ne', 'unavailable')
                      | list
                      | count == 0 }}
            sequence:
              - service: notify.mobile_app_michaels_iphone
                data:
                  message: >
                    Cause:
                    {%- for k, v in (trigger.to_state.attributes.open_sensors or {}).items() %}
                    {{ state_attr(k, 'friendly_name') or k }}: {{ v }}
                    {%- endfor %}
                  title: ðŸš¨ Alarmo Alert! ðŸš¨
                  data:
                    url: /dashboard-security/home
                    clickAction: /dashboard-security/home
        default:
          - service: notify.mobile_app_michaels_iphone
            data:
              message: >
                Cause:
                {%- for k, v in (trigger.to_state.attributes.open_sensors or {}).items() %}
                {{ state_attr(k, 'friendly_name') or k }}: {{ 'wet' if state_attr(k, 'device_class') == 'moisture' else v }}
                {%- endfor %}
              title: ðŸš¨ Alarmo Alert! ðŸš¨
              data:
                push:
                  sound:
                    name: default
                    critical: 1
                url: /dashboard-security/home
                clickAction: /dashboard-security/home

  - alias: Alert on Shed Alarm Trigger
    id: f0f49f86-0474-4b51-afcd-75315546e8eb
    trigger:
      - platform: state
        entity_id: alarm_control_panel.shed
        to: triggered
        not_from:
          - "unknown"
          - "unavailable"
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0.25
    actions:
      - service: light.turn_on
        entity_id: light.exterior_lights
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "Shed Alarm Triggered!"
          title: ðŸš¨ Alarmo Alert! ðŸš¨
          data:
            push:
              sound:
                name: default
                critical: 1
            url: /dashboard-security/home
            clickAction: /dashboard-security/home

  - alias: Auto Arm and Disarm Shed
    id: 28a489e9-12db-4ac4-b5ff-26f5c61dfb22
    triggers:
      - platform: state
        entity_id:
          - group.adults
        not_to:
          - "unavailable"
          - "unknown"
    conditions:
      - condition: state
        entity_id: schedule.shed_alarm_schedule
        state: "off"
    actions:
      - service: alarm_control_panel.alarm_{{ 'disarm' if 'home' == trigger.to_state.state else 'arm_away' }}
        target:
          entity_id: alarm_control_panel.alarmo

  - alias: Auto arm shed on schedule
    id: 075a7b5b-0e08-4ec8-80f9-5a43f765ee80
    trigger:
      - platform: state
        entity_id: schedule.shed_alarm_schedule
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: schedule.shed_alarm_schedule
                state: "on"
            sequence:
              - service: alarm_control_panel.alarm_arm_away
                target:
                  entity_id: alarm_control_panel.shed
          - conditions:
              - condition: state
                entity_id: schedule.shed_alarm_schedule
                state: "off"
              - condition: state
                entity_id: alarm_control_panel.alarmo
                state: "disarmed"
            sequence:
              - service: alarm_control_panel.alarm_disarm
                target:
                  entity_id: alarm_control_panel.shed
