automation:
  - alias: Water Softener Salt Bin Low
    id: appliances_water_softener_salt_bin_low
    triggers:
      - platform: numeric_state
        entity_id: sensor.salt_sensor_salt_level
        below: 20
        for:
          hours: 24
      - platform: time
        at: "10:30:00"
    conditions:
      - condition: numeric_state
        entity_id: sensor.salt_sensor_salt_level
        below: 20
    actions:
      - service: notify.mobile_app_michaels_iphone
        data:
          title: "Water Softener Salt Low"
          message: "{{ states('sensor.salt_sensor_salt_level') }} / {{ states('sensor.salt_sensor_salt_level') }}"
          data:
            tag: "water-softener-salt-low"

  - alias: Water Softener Level Status LED
    id: c80912a7-a0bd-482a-9013-693a0bc8a2b2
    mode: single
    triggers:
      - platform: state
        entity_id: sensor.salt_sensor_salt_level
    actions:
      - if:
          - condition: numeric_state
            entity_id: sensor.salt_sensor_salt_level
            above: 25
        then:
          - service: light.turn_on
            target:
              entity_id: light.salt_sensor_status_light
            data:
              brightness_pct: 65
              # Green
              rgb_color:
                - 0
                - 255
                - 0
      - if:
          - condition: numeric_state
            entity_id: sensor.salt_sensor_salt_level
            below: 25
            above: 10
        then:
          - service: light.turn_on
            target:
              entity_id: light.salt_sensor_status_light
            data:
              flash: short
              brightness_pct: 65
              # Yellow
              rgb_color:
                - 255
                - 255
                - 0
      - if:
          - condition: numeric_state
            entity_id: sensor.salt_sensor_salt_level
            below: 10
        then:
          - service: light.turn_on
            target:
              entity_id: light.salt_sensor_status_light
            data:
              flash: long
              brightness_pct: 100
              # Red
              rgb_color:
                - 255
                - 0
                - 0
      - delay:
          minutes: 1
