automation:
  - alias: Water Softener Salt Bin Low
    id: appliances_water_softener_salt_bin_low
    triggers:
      - platform: numeric_state
        entity_id: sensor.salt_sensor_salt_level
        below: 20
        for:
          hours: 24
      - platform: time
        at: "10:30:00"
    conditions:
      - condition: numeric_state
        entity_id: sensor.salt_sensor_salt_level
        below: 20
    actions:
      - service: notify.mobile_app_michaels_iphone
        data:
          title: "Water Softener Salt Low"
          message: "{{ states('sensor.salt_sensor_salt_level') | round(2) }}% / {{ states('sensor.salt_sensor_vl53l0x_distance') | round(2) }}m"
          data:
            tag: "water-softener-salt-low"
