timer:
  basement_lights_off:
    name: Turn off basement lights
    duration: 00:15:00
    restore: true

automation:
  - alias: Basement Light Presence Control On
    id: basement_light_presence_controls_on
    mode: queued
    max: 25
    trigger:
      - platform: state
        entity_id: binary_sensor.basement_presence
        to: "on"
        id: lights_on
      - platform: state
        entity_id: sensor.basement_fp1_presence_event
        to:
          - "enter"
          - "approach"
        id: lights_on
      - platform: state
        entity_id: binary_sensor.basement_presence
        to: "off"
        id: timer_start
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.basement_lights_off
        id: timer_lights_off
    action:
      choose:
        - conditions:
            - condition: trigger
              id: lights_on
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "on"
            - condition: state
              entity_id: input_boolean.nap_mode
              state: "off"
          sequence:
            - service: timer.cancel
              target:
                entity_id: timer.basement_lights_off
            - if:
                - condition: state
                  entity_id: light.basement_room_light_dimmer
                  state: "off"
              then:
                - service: light.turn_on
                  entity_id:
                    - light.basement_hall
                    - light.basement_room_light_dimmer
        - conditions:
            - condition: trigger
              id: timer_start
            - condition: state
              entity_id: light.basement_lights
              state: "on"
          sequence:
            - service: timer.start
              entity_id: timer.basement_lights_off
        - conditions:
            - condition: trigger
              id: timer_lights_off
          sequence:
            - wait_template: "{{ (states('sensor.mike_apple_watch_estimated_distance') |float(0) > 0.5) or states('device_tracker.mike_apple_watch_ble', 'not_home') }}"
              timeout:
                minutes: 10
              continue_on_timeout: true
            - service: light.turn_off
              entity_id:
                - light.basement_hall
                - light.basement_room_light_dimmer

  - alias: Dim Light Over 15 Minutes at Sundown
    id: basement_dim_light_at_sundown
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 5.0
    condition:
      - condition: state
        entity_id: light.basement_room_light_dimmer
        state: "on"
    action:
      - service: light.turn_on
        target:
          entity_id:
            - light.basement_room_light_dimmer
        data:
          transition: 900
          brightness_pct: 60

  - alias: Set default dimmer value based on sun elevation
    id: basement_dimmer_set_restore_value_sun_angle
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 5.0
        id: below
        variables:
          default_level: 60
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 5.0
        id: above
        variables:
          default_level: 90
    action:
      - service: zwave_js.set_config_parameter
        target:
          entity_id: light.basement_room_light_dimmer
        data:
          parameter: 9
          value: "{{ default_level }}"
      - service: zwave_js.set_config_parameter
        target:
          entity_id: light.basement_room_light_dimmer
        data:
          parameter: 10
          value: "{{ default_level }}"

  - alias: Sync Basement Hall Light to Basement Room Light
    id: basement_sync_hall_room_lights
    trigger:
      - platform: state
        to: ~
        entity_id: switch.basement_hall
    condition:
      condition: template
      value_template: "{{ trigger.to_state.state in ['off', 'on'] }}"
    action:
      - service: homeassistant.turn_{{ trigger.to_state.state }}
        entity_id: light.basement_room_light_dimmer

  - alias: Basement Lights off Night
    id: basement_night_auto_off
    trigger:
      - platform: time
        at: "23:00:00"
    action:
      service: homeassistant.turn_off
      entity_id:
        - light.basement_room_light_dimmer
        - switch.basement_hall

  - alias: Status Light Basement switches
    id: basement_light_status_switches
    trigger:
      - platform: state
        entity_id: cover.garage
        to: "open"
        id: "garage_open"
      - platform: state
        entity_id: cover.garage
        to: "closed"
        id: "garage_closed"
      - platform: state
        entity_id: group.locks
        to: "locked"
        id: "doors_locked"
      - platform: state
        entity_id: group.locks
        to: "unlocked"
        id: "doors_unlocked"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "garage_open"
            sequence:
              # Set LED to Red
              - service: script.lzw31_set_led
                data:
                  entity: light.basement_room_light_dimmer
                  led_colour: 0
                  led_brightness: 10
          - conditions:
              - condition: trigger
                id: "garage_closed"
            sequence:
              # Set LED to Blue
              - service: script.lzw31_set_led
                data:
                  entity: light.basement_room_light_dimmer
                  led_colour: 170
                  led_brightness: 5
          - conditions:
              - condition: trigger
                id: "doors_unlocked"
            sequence:
              # Set LED to Red
              - service: script.lzw30_set_led
                data:
                  entity: switch.basement_hall
                  led_colour: 0
                  led_brightness: 10
          - conditions:
              - condition: trigger
                id: "doors_locked"
            sequence:
              # Set LED to blue
              - service: script.lzw30_set_led
                data:
                  entity: switch.basement_hall
                  led_colour: 170
                  led_brightness: 5

  - alias: Top of basement stairs action control
    id: basement_top_of_stairs_action_control
    trigger:
      - platform: state
        entity_id: sensor.basement_light_action
        to: "up_double"
        id: turn_on
      - platform: state
        entity_id: sensor.basement_light_action
        to: "down_double"
        id: turn_off
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: turn_on
            sequence:
              - service: light.turn_on
                target:
                  floor_id:
                    - basement
          - conditions:
              - condition: trigger
                id: turn_off
            sequence:
              - service: light.turn_off
                target:
                  floor_id:
                    - basement
