timer:
  basement_lights_off:
    name: Turn off basement lights
    duration: 00:10:00
    restore: true

automation:
  - alias: Basement Light on pir entrance
    id: basement_light_on_pir_entrance
    triggers:
      - platform: state
        entity_id: binary_sensor.basement_stairs_motion_occupancy
        from: "off"
        to: "on"
    conditions:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "disarmed"
    actions:
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.basement_hall_motion_occupancy
            to: "on"
        timeout:
          minutes: 5
        continue_on_timeout: false
      - service: light.turn_on
        entity_id: light.basement_lights

  - alias: Basement Light Presence Control On
    id: basement_light_presence_controls_on
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.basement_presence
        to: "on"
        id: lights_on
      - platform: state
        entity_id: sensor.basement_fp1_presence_event
        to:
          - "enter"
          - "approach"
        id: lights_on
      - platform: state
        entity_id: binary_sensor.basement_presence
        to: "off"
        id: timer_start
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.basement_lights_off
        id: timer_lights_off
    action:
      choose:
        - conditions:
            - condition: trigger
              id: lights_on
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "on"
            - condition: state
              entity_id: input_boolean.nap_mode
              state: "off"
          sequence:
            - service: timer.cancel
              target:
                entity_id: timer.basement_lights_off
            - if:
                - condition: state
                  entity_id: light.basement_room_light_dimmer
                  state: "off"
              then:
                - service: light.turn_on
                  entity_id:
                    - light.basement_hall
                    - light.basement_room_light_dimmer
        - conditions:
            - condition: trigger
              id: timer_start
            - condition: state
              entity_id: light.basement_lights
              state: "on"
          sequence:
            - service: timer.start
              entity_id: timer.basement_lights_off
        - conditions:
            - condition: trigger
              id: timer_lights_off
            - condition: state
              entity_id: binary_sensor.basement_presence
              state: "off"
          sequence:
            - service: light.turn_off
              entity_id:
                - light.basement_lights

  - alias: Sync Basement Hall Light to Basement Room Light
    id: basement_sync_hall_room_lights
    trigger:
      - platform: state
        to: ~
        entity_id: light.basement_hall
    condition:
      condition: template
      value_template: "{{ trigger.to_state.state in ['off', 'on'] }}"
    action:
      - service: homeassistant.turn_{{ trigger.to_state.state }}
        entity_id: light.basement_room_light_dimmer

  - alias: Basement Lights off Night
    id: basement_night_auto_off
    trigger:
      - platform: time
        at: "23:00:00"
    action:
      service: homeassistant.turn_off
      entity_id:
        - light.basement_room_light_dimmer
        - light.basement_hall

  - alias: Top of basement stairs action control
    id: basement_top_of_stairs_action_control
    trigger:
      - platform: state
        entity_id:
          - sensor.basement_stairs_light_action
          - sensor.basement_hall_action
          - sensor.basement_room_action
        to: "up_double"
        id: turn_on
      - platform: state
        entity_id:
          - sensor.basement_stairs_light_action
          - sensor.basement_hall_action
          - sensor.basement_room_action
        to: "down_double"
        id: turn_off
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: turn_on
            sequence:
              - service: light.turn_on
                target:
                  area_id: basement
          - conditions:
              - condition: trigger
                id: turn_off
            sequence:
              - service: light.turn_off
                target:
                  floor_id: basement
              - service: switch.turn_off
                entity_id: switch.basement_space_heater

  - alias: Basement Space Heater Control
    id: basement_space_heater_control
    triggers:
      - platform: state
        entity_id: binary_sensor.basement_presence
        to: "on"
        id: turn_on
      - platform: state
        entity_id: binary_sensor.basement_presence
        to: "off"
        id: turn_off
        for:
          minutes: 5
      - platform: template
        value_template: "{{ 'armed_' in states('alarm_control_panel.alarmo') }}"
        id: turn_off
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id: turn_on
              - condition: state
                entity_id: alarm_control_panel.alarmo
                state: "disarmed"
            sequence:
              - service: switch.turn_on
                entity_id: switch.basement_space_heater
          - conditions:
              - condition: trigger
                id: turn_off
            sequence:
              - service: switch.turn_off
                entity_id: switch.basement_space_heater

  - alias: Basement Stairs Light Motion Control
    id: basement_stairs_light_motion_control
    triggers:
      - platform: state
        entity_id: binary_sensor.basement_stairs_motion_occupancy
        from: "off"
        to: "on"
        id: turn_on
      - platform: state
        entity_id: binary_sensor.basement_stairs_motion_occupancy
        to: "off"
        for:
          minutes: 10
        id: turn_off
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: group.adults
                state: "home"
              - condition: state
                entity_id: alarm_control_panel.alarmo
                state: "disarmed"
              - condition: trigger
                id: turn_on
              - condition: time
                after: "07:45:00"
            sequence:
              - service: light.turn_on
                entity_id: light.basement_stairs
        default:
          - service: light.turn_off
            entity_id: light.basement_stairs
