input_boolean:
  basement_auto_lights:
    name: Basement Auto Lights
    icon: mdi:lightbulb-auto

timer:
  basement_lights_off:
    name: Turn off basement lights
    duration: 00:10:00
    restore: true

automation:
  - alias: Basement Auto Lights Enable/Disable
    id: 643e3840-0a08-4883-a940-4a6f1b957387
    trigger:
      # Basement Room
      - trigger: device
        domain: mqtt
        device_id: e3bc901892c55fbcaa6dd42876632c35
        type: action
        subtype: config_double
        id: disable_auto
      # Basement Hall
      - trigger: device
        domain: mqtt
        device_id: 4fd03b2b6cc39b1cc034f88e88f749d6
        type: action
        subtype: config_double
        id: disable_auto
      - platform: time
        at: "00:00:00"
        id: enable_auto
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: disable_auto
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.basement_auto_lights
          - conditions:
              - condition: trigger
                id: enable_auto
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.basement_auto_lights

  - alias: Basement Hall Light on pir entrance
    id: basement_light_on_pir_entrance
    triggers:
      - platform: state
        entity_id: binary_sensor.basement_stairs_motion_occupancy
        from: "off"
        to: "on"
    conditions:
      - condition: state
        entity_id: input_boolean.basement_auto_lights
        state: "on"
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "disarmed"
      - not:
          - condition: state
            entity_id: media_player.basement
            state: "playing"
    actions:
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.basement_hall_motion_occupancy
            to: "on"
          - platform: state
            entity_id: sensor.basement_fp1_presence_event
            to:
              - "enter"
              - "approach"
        timeout:
          minutes: 5
        continue_on_timeout: false
      - service: light.turn_on
        entity_id: light.basement_hall

  - alias: Basement Light Presence Control
    id: 4d5f4993-7ff3-4473-9917-615148d7d676
    trace:
      stored_traces: 30
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.group_basement_presence
        from: "off"
        to: "on"
        id: lights_on
      - platform: state
        entity_id: sensor.basement_fp1_presence_event
        to:
          - "enter"
          - "approach"
        id: lights_on
      - platform: state
        entity_id: binary_sensor.group_basement_presence
        to: "off"
        id: timer_start
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.basement_lights_off
        id: timer_lights_off
    conditions:
      - condition: state
        entity_id: input_boolean.basement_auto_lights
        state: "on"
    action:
      choose:
        - conditions:
            - condition: trigger
              id: lights_on
            - condition: state
              entity_id: binary_sensor.group_basement_presence
              state: "off"
              for:
                minutes: 6
            - not:
                - condition: state
                  entity_id: media_player.basement
                  state: "playing"
          sequence:
            - service: timer.cancel
              target:
                entity_id: timer.basement_lights_off
            - if:
                - condition: state
                  entity_id: light.basement_room
                  state: "off"
              then:
                - service: light.turn_on
                  target:
                    label_id: basement_room_lights
                  data:
                    transition: 3
        - conditions:
            - condition: trigger
              id: timer_start
            - condition: state
              entity_id: light.basement_lights
              state: "on"
          sequence:
            - service: timer.start
              entity_id: timer.basement_lights_off
        - conditions:
            - condition: trigger
              id: timer_lights_off
            - condition: state
              entity_id: binary_sensor.group_basement_presence
              state: "off"
          sequence:
            - service: light.turn_off
              target:
                label_id: basement_lights

  - alias: Basement Lights off Night
    id: basement_night_auto_off
    trigger:
      - platform: time
        at: "23:00:00"
    action:
      - wait_template: "{{ is_state('binary_sensor.group_basement_presence', 'off') }}"
      - service: light.turn_off
        target:
          label_id: basement_lights

  - alias: Top of basement stairs action control
    id: basement_top_of_stairs_action_control
    trigger:
      # Basement Stairs
      - trigger: device
        domain: mqtt
        device_id: db7cbb2e9f9508cfb87c54e915766ff3
        type: action
        subtype: up_double
        id: turn_on
      - trigger: device
        domain: mqtt
        device_id: db7cbb2e9f9508cfb87c54e915766ff3
        type: action
        subtype: down_double
        id: turn_off
      # Basement Room
      - trigger: device
        domain: mqtt
        device_id: e3bc901892c55fbcaa6dd42876632c35
        type: action
        subtype: up_double
        id: turn_on
      - trigger: device
        domain: mqtt
        device_id: e3bc901892c55fbcaa6dd42876632c35
        type: action
        subtype: down_double
        id: turn_off
      # Basement Hall
      - trigger: device
        domain: mqtt
        device_id: 4fd03b2b6cc39b1cc034f88e88f749d6
        type: action
        subtype: up_double
        id: turn_on
      - trigger: device
        domain: mqtt
        device_id: 4fd03b2b6cc39b1cc034f88e88f749d6
        type: action
        subtype: down_double
        id: turn_off
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: turn_on
            sequence:
              - service: light.turn_on
                target:
                  area_id: basement
          - conditions:
              - condition: trigger
                id: turn_off
            sequence:
              - service: light.turn_off
                target:
                  floor_id: basement
              - service: switch.turn_off
                entity_id: switch.basement_space_heater

  - alias: Basement Space Heater Control
    id: basement_space_heater_control
    triggers:
      - platform: state
        entity_id: binary_sensor.group_basement_presence
        to: "on"
        id: turn_on
      - platform: state
        entity_id: binary_sensor.group_basement_presence
        to: "off"
        id: turn_off
        for:
          minutes: 5
      - platform: template
        value_template: "{{ 'armed_' in states('alarm_control_panel.alarmo') }}"
        id: turn_off
    condition:
      - condition: state
        entity_id: sensor.season
        state:
          - "winter"
          - "autumn"
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id: turn_on
              - condition: state
                entity_id: alarm_control_panel.alarmo
                state: "disarmed"
              - condition: state
                entity_id: binary_sensor.home_grid_status
                state: "on"
            sequence:
              - service: switch.turn_on
                entity_id: switch.basement_space_heater
          - conditions:
              - condition: trigger
                id: turn_off
            sequence:
              - service: switch.turn_off
                entity_id: switch.basement_space_heater

  - alias: Basement Stairs Light Motion Control
    id: basement_stairs_light_motion_control
    triggers:
      - platform: state
        entity_id: binary_sensor.basement_stairs_motion_occupancy
        from: "off"
        to: "on"
        id: turn_on
      - platform: state
        entity_id: binary_sensor.basement_stairs_motion_occupancy
        to: "off"
        for:
          minutes: 10
        id: turn_off
    conditions:
      - condition: state
        entity_id: input_boolean.basement_auto_lights
        state: "on"
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.basement_auto_lights
                state: "on"
              - condition: state
                entity_id: group.adults
                state: "home"
              - condition: state
                entity_id: alarm_control_panel.alarmo
                state: "disarmed"
              - condition: trigger
                id: turn_on
              - condition: time
                after: "07:30:00"
            sequence:
              - service: light.turn_on
                entity_id: light.basement_stairs
          - conditions:
              - condition: trigger
                id: turn_off
            sequence:
              - service: light.turn_off
                entity_id: light.basement_stairs

  - alias: Basement Lights off when fully unoccupised
    id: e7e9dbe0-fb22-4dbe-bd0c-cbebb854339a
    mode: single
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.full_basement_presence
        from: "on"
        to: "off"
        for:
          minutes: 10
    actions:
      - action: light.turn_off
        data:
          transition: 90
        target:
          label_id: basement_lights
