automation:
  - alias: Basement Dimmer Control
    id: basement_dimmer_auto_control
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
      - platform: state
        entity_id: light.basement_room_light_dimmer
        from: "off"
        to: "on"
      - platform: homeassistant
        event: start
    action:
      choose:
        - conditions:
            - condition: sun
              after: sunset
              after_offset: "-00:35:00"
            - condition: state
              entity_id: light.basement_room_light_dimmer
              state: "on"
          sequence:
            - service: light.turn_on
              entity_id: light.basement_room_light_dimmer
              data:
                brightness_pct: 60
        - conditions:
            - condition: state
              entity_id: light.basement_room_light_dimmer
              state: "on"
          sequence:
            - service: light.turn_on
              entity_id: light.basement_room_light_dimmer
              data:
                brightness_pct: 90

  - alias: Sync Basement Hall Light to Basement Room Light
    id: basement_sync_hall_room_lights
    trigger:
      - platform: state
        entity_id: switch.basement_hall
    action:
      - service: homeassistant.turn_{{ trigger.to_state.state }}
        entity_id: light.basement_room_light_dimmer

  - alias: Basement Lights off Night
    id: basement_night_auto_off
    trigger:
      - platform: time
        at: "23:00:00"
    action:
      service: homeassistant.turn_off
      entity_id:
        - light.basement_room_light_dimmer
        - switch.basement_hall
