automation:
  - alias: Basement Dimmer Control
    id: basement_dimmer_auto_control
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
      - platform: state
        entity_id: light.basement_room_light_dimmer
        from: "off"
        to: "on"
      - platform: homeassistant
        event: start
    action:
      choose:
        - conditions:
            - condition: sun
              after: sunset
              after_offset: "-00:35:00"
            - condition: state
              entity_id: light.basement_room_light_dimmer
              state: "on"
          sequence:
            - service: light.turn_on
              entity_id: light.basement_room_light_dimmer
              data:
                brightness_pct: 60
        - conditions:
            - condition: state
              entity_id: light.basement_room_light_dimmer
              state: "on"
          sequence:
            - service: light.turn_on
              entity_id: light.basement_room_light_dimmer
              data:
                brightness_pct: 90

  - alias: Sync Basement Hall Light to Basement Room Light
    id: basement_sync_hall_room_lights
    trigger:
      - platform: state
        entity_id: switch.basement_hall
    action:
      - service: homeassistant.turn_{{ trigger.to_state.state }}
        entity_id: light.basement_room_light_dimmer

  - alias: Basement Lights off Night
    id: basement_night_auto_off
    trigger:
      - platform: time
        at: "23:00:00"
    action:
      service: homeassistant.turn_off
      entity_id:
        - light.basement_room_light_dimmer
        - switch.basement_hall

  - alias: Status Light Basement switches
    id: basement_light_status_switches
    trigger:
      - platform: state
        entity_id: cover.garage
        to: "open"
        id: "garage_open"
      - platform: state
        entity_id: cover.garage
        to: "closed"
        id: "garage_closed"
      - platform: state
        entity_id: group.locks
        to: "locked"
        id: "doors_locked"
      - platform: state
        entity_id: group.locks
        to: "unlocked"
        id: "doors_unlocked"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "garage_open"
            sequence:
              # Set LED to Red
              - service: script.lzw31_set_led
                data:
                  entity: light.basement_room_light_dimmer
                  led_colour: 0
                  led_brightness: 10
          - conditions:
              - condition: trigger
                id: "garage_closed"
            sequence:
              # Set LED to Blue
              - service: script.lzw31_set_led
                data:
                  entity: light.basement_room_light_dimmer
                  led_colour: 170
                  led_brightness: 5
          - conditions:
              - condition: trigger
                id: "doors_unlocked"
            sequence:
              # Set LED to Red
              - service: script.lzw30_set_led
                data:
                  entity: switch.basement_hall
                  led_colour: 0
                  led_brightness: 10
          - conditions:
              - condition: trigger
                id: "doors_locked"
            sequence:
              # Set LED to blue
              - service: script.lzw30_set_led
                data:
                  entity: switch.basement_hall
                  led_colour: 170
                  led_brightness: 5
