input_boolean:
  sleeping_in:
    name: Sleeping In
    icon: mdi:alarm-snooze

automation:
  - alias: Bedroom Comfort On Evenings
    id: 6b49967c-0167-4f4f-ba1e-5abaeb5fdcb5
    trigger:
      - platform: time
        at: "22:30:00"
      - platform: state
        entity_id: sensor.tiffanys_iphone_battery_state
        from: "Not Charging"
        to:
          - "Charging"
          - "Full"
      - platform: state
        entity_id: group.adults
        from: "not_home"
        to: "home"
    conditions:
      - condition: time
        after: "22:00:00"
        before: "04:00:00"
      - condition: state
        entity_id: group.adults
        state: "home"
    actions:
      - service: switch.turn_on
        entity_id:
          - switch.master_white_noise
      - if:
          - condition: numeric_state
            entity_id: input_number.outside_min_temperature_next_8_hours
            above: -13
        then:
          - service: switch.turn_on
            entity_id: switch.master_humidifier

  - alias: Bedroom off mornings
    id: bedroom_off_mornings_nursery_active
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.bedroom_ecobee_motion
          - binary_sensor.bedroom_ecobee_occupancy
          - light.main_bath_light
        to: "on"
      - platform: time
        at: "07:30:00"
      - platform: state
        entity_id:
          - switch.master_white_noise
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.sleeping_in
        state: "off"
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "off"
      - condition: time
        after: "07:00:00"
      - condition: time
        before: "08:00:00"
    actions:
      - service: homeassistant.turn_off
        entity_id:
          - switch.master_white_noise
          - switch.master_humidifier

  - alias: Spare Bedroom Fan Toggle
    id: spare_bedroom_fan_toggle
    trigger:
      - platform: event
        event_type: "ios_bedtime_event"
    condition:
      - condition: state
        entity_id: person.mike
        state: "home"
    action:
      service: homeassistant.turn_on
      entity_id:
        - switch.spare_bedroom_fan

  - alias: Reset Sleeping in
    id: bedroom_reset_sleeping_in
    trigger:
      - platform: time
        at: "12:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.sleeping_in
        state: "on"
    action:
      service: homeassistant.turn_off
      entity_id: input_boolean.sleeping_in

  - alias: Front Bedroom Morning Wake Up Sequence
    id: bedroom_morning_wake_up_sequence
    trigger:
      - platform: event
        event_type: "ios_wakeup_event"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.spare_bedroom_fan
