binary_sensor:
  - platform: template
    sensors:
      guests_present:
        friendly_name: "Guests Home"
        value_template: "{{ (states('sensor.coreguest') | int) > 0 or states('input_boolean.guests_present') }}"
      waste_dashboard:
        value_template: >-
          {% set garbage_day=states('sensor.waste_current_pickup') | as_datetime -%}
          {%- if now().day == (garbage_day - timedelta(days=1)).day or
          now().day == garbage_day.day and now().hour < 10 -%}
          on
          {%- else -%}
          off
          {%-endif-%}
