automation:
  - alias: Exterior Christmas Lights On
    id: xmas_exteior_lights_on
    triggers:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0.25
    conditions:
      - condition: template
        value_template: "{{ now().month in [11, 12, 1, 2] }}"
    actions:
      service: homeassistant.turn_on
      entity_id: light.exterior_christmas_lights

  - alias: Exterior Christmas Lights Off
    id: xmas_exterior_lights_off
    triggers:
      - platform: time
        at: "23:30:00"
      - platform: sun
        event: sunrise
    actions:
      service: homeassistant.turn_off
      entity_id: light.exterior_christmas_lights

  - alias: Christmas Tree lights on when living room occupied
    id: xmas_lights_room_occupied
    triggers:
      - platform: state
        entity_id: binary_sensor.living_room_occupancy
        to: "on"
        id: turn_on
      - platform: state
        entity_id: binary_sensor.living_room_occupancy
        to: "off"
        for:
          minutes: 30
        id: turn_off
      - platform: event
        event_type: "ios_wakeup_event"
        id: turn_on
      - platform: zone
        entity_id:
          - person.mike
          - person.tiff
        zone: zone.home
        event: enter
        id: turn_on
      - platform: state
        entity_id: alarm_control_panel.master
        to:
          - armed_night
          - armed_vacation
          - armed_away
        id: turn_off
    condition:
      - condition: template
        value_template: "{{ now().month in [11, 12, 1, 2] }}"
      - condition: time
        after: "06:00:00"
        before: "22:30:00"
      - condition: state
        entity_id: alarm_control_panel.master
        state: "disarmed"
    actions:
      choose:
        - conditions:
            - condition: trigger
              id: turn_on
          sequence:
            - service: homeassistant.turn_on
              entity_id: light.christmas_tree
        - conditions:
            - condition: trigger
              id: turn_off
          sequence:
            - service: homeassistant.turn_off
              entity_id: light.christmas_tree

  - alias: Christmas Tree off at bedtime
    id: xmas_tree_lights_off_night
    triggers:
      platform: time
      at: "22:30:00"
    actions:
      service: homeassistant.turn_off
      entity_id: light.christmas_tree

  - alias: Exterior Christmas Lights on arriving home
    id: external_xmas_lights_on_arrive_home
    triggers:
      - platform: zone
        entity_id:
          - person.mike
          - person.tiff
        zone: zone.home
        event: enter
    condition:
      - condition: template
        value_template: "{{ now().month in [11, 12, 1, 2] }}"
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 3.35
      - condition: time
        after: "15:30:00"
    actions:
      service: homeassistant.turn_on
      entity_id: light.exterior_christmas_lights
