group:
  exterior_christmas_lights:
    name: Exterior Christmas Lights
    entities:
      - light.front_christmas_lights
      - light.deck_christmas_lights

automation:
  - alias: Exterior Christmas Lights On
    id: xmas_exteior_lights_on
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_on
      entity_id: group.exterior_christmas_lights

  - alias: Exterior Christmas Lights Off
    id: xmas_exterior_lights_off
    trigger:
      - platform: time
        at: "23:30:00"
      - platform: sun
        event: sunrise
    action:
      service: homeassistant.turn_off
      entity_id: group.exterior_christmas_lights

  - alias: Christmas Tree lights on when living room occupied
    id: xmas_lights_room_occupied
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room
        to: "on"
      - platform: state
        entity_id: binary_sensor.living_room
        to: "off"
        for:
          minutes: 60
      - platform: event
        event_type: "ios_wakeup_event"
      - platform: zone
        entity_id:
          - device_tracker.tesla_location
          - person.mike
          - person.tiff
        zone: zone.home
        event: enter
    condition:
      - condition: time
        after: "06:30:00"
        before: "22:30:00"
      - condition: template
        value_template: "{{ trigger.to_state.state in ['off', 'on'] }}"
    action:
      service: homeassistant.turn_{{ trigger.to_state.state }}
      entity_id: light.christmas_tree

  - alias: Christmas Tree off at bedtime
    id: xmas_tree_lights_off_night
    trigger:
      platform: time
      at: "22:30:00"
    action:
      service: homeassistant.turn_off
      entity_id: light.christmas_tree

  - alias: Exterior Christmas Lights on arriving home
    id: external_xmas_lights_on_arrive_home
    trigger:
      - platform: zone
        entity_id:
          - device_tracker.tesla_location
          - person.mike
          - person.tiff
        zone: zone.home
        event: enter
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 3.0
    action:
      service: homeassistant.turn_on
      entity_id: group.exterior_christmas_lights
