automation:
  - alias: Exterior Christmas Lights On
    id: xmas_exteior_lights_on
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_on
      entity_id: switch.exterior_xmas_lights

  - alias: Exterior Christmas Lights Off
    id: xmas_exterior_lights_off
    trigger:
      - platform: time
        at: "23:30:00"
      - platform: sun
        event: sunrise
    action:
      service: homeassistant.turn_off
      entity_id: switch.exterior_xmas_lights

  - alias: Christmas Tree lights on when living room occupied
    id: xmas_lights_room_occupied
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room
        to: "on"
      - platform: state
        entity_id: binary_sensor.living_room
        to: "off"
        for:
          minutes: 60
      - platform: homeassistant
        event: start
    condition:
      - condition: time
        after: "06:30:00"
        before: "22:30:00"
    action:
      service: homeassistant.turn_{{ trigger.to_state.state }}
      entity_id: switch.christmas_tree

  - alias: Christmas Tree off at bedtime
    id: xmas_tree_lights_off_night
    trigger:
      platform: time
      at: "22:30:00"
    action:
      service: homeassistant.turn_off
      entity_id: switch.christmas_tree
