automation:
  - alias: Disable Climate If Door Ajar
    id: disable_climate_door_ajar
    trigger:
      - platform: state
        id: "notification_door_open"
        entity_id: binary_sensor.front_door
        to: "on"
        for:
          minutes: 5
    action:
      - variables:
          climate_restore_state: "{{ states('climate.my_ecobee') }}"
      - service: notify.adults
        data:
          message: "Front Door Left Open"
          data:
            tag: "front-door-open-warning"
            push:
              name: "default"
              critical: 1
      - service: climate.turn_off
        target:
          entity_id: climate.my_ecobee
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.front_door
            to: "off"
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.my_ecobee
        data:
          hvac_mode: "{{ climate_restore_state }}"
      - service: notify.adults
        data:
          message: "clear_notification"
          data:
            tag: "front-door-open-warning"
            push:
              name: "default"
              critical: 1
