automation:
  - alias: Disable Climate If Door or Window Ajar
    id: disable_climate_door_ajar
    trigger:
      - platform: state
        id: "notification_door_open"
        entity_id:
          - binary_sensor.doors
          - binary_sensor.windows
        to: "on"
        for:
          minutes: 5
    condition:
      - not:
          - condition: state
            entity_id: climate.my_ecobee
            state: "off"
    action:
      - variables:
          climate_restore_state: "{{ states('climate.my_ecobee') }}"
      - service: notify.adults
        data:
          title: "A Door or window has been left open"
          message: "Disabling thermostat"
          data:
            tag: "front-door-open-warning"
            push:
              name: "default"
              critical: 1
      - service: climate.turn_off
        target:
          entity_id: climate.my_ecobee
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.doors
            to: "off"
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.my_ecobee
        data:
          hvac_mode: "{{ climate_restore_state }}"
      - service: notify.adults
        data:
          message: "clear_notification"
          data:
            tag: "front-door-open-warning"

  - alias: Furnace on if left off and cold forecast
    id: furnace_on_if_left_off_cold_forecast
    trigger:
      - platform: time
        at: "22:00:00"
      - platform: time
        at: "00:00:00"
    condition:
      - condition: state
        entity_id: climate.my_ecobee
        state:
          - "off"
    action:
      - service: weather.get_forecasts
        target:
          entity_id: weather.tomorrow_io_home_nowcast
        data:
          type: hourly
        response_variable: forecast
      - condition: template
        value_template: "{{ forecast['weather.tomorrow_io_home_nowcast'].forecast | map(attribute='temperature')| list | min < 10 }}"
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "Furnace enabled, cold weather forecast"
          data:
            tag: "furnace-enabled-cold-notification"
            group: "furnace-notification"
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        target:
          entity_id: climate.my_ecobee

  - alias: CO2 High Notification
    id: comfort_co2_high_notification
    trigger:
      - platform: numeric_state
        entity_id: sensor.airthings_wave_111512_carbon_dioxide
        above: 850
        for:
          hours: 1
    condition:
      - condition: state
        entity_id: group.adults
        state: "home"
    action:
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "CO2 is high, is HRV on?"
          data:
            tag: "comfort-co2-high-notification"
