automation:
  - alias: Disable Climate If Door Ajar
    id: disable_climate_door_ajar
    trigger:
      - platform: state
        id: "notification_door_open"
        entity_id: binary_sensor.front_door
        to: "on"
        for:
          minutes: 5
    action:
      - variables:
          climate_restore_state: "{{ states('climate.my_ecobee') }}"
      - service: notify.adults
        data:
          message: "Front Door Left Open"
          data:
            tag: "front-door-open-warning"
            push:
              name: "default"
              critical: 1
      - service: climate.turn_off
        target:
          entity_id: climate.my_ecobee
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.front_door
            to: "off"
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.my_ecobee
        data:
          hvac_mode: "{{ climate_restore_state }}"
      - service: notify.adults
        data:
          message: "clear_notification"
          data:
            tag: "front-door-open-warning"
            push:
              name: "default"
              critical: 1

  - alias: Furnace on if left off and cold forecast
    id: furnace_on_if_left_off_cold_forecast
    trigger:
      - platform: time
        at: "21:00:00"
      - platform: time
        at: "23:00:00"
    condition:
      - condition: state
        entity_id: climate.my_ecobee
        state:
          - "off"
    action:
      - service: weather.get_forecast
        target:
          entity_id: weather.tomorrow_io_home_nowcast
        data:
          type: hourly
        response_variable: forecast
      - condition: template
        value_template: "{{ forecast.forecast | map(attribute='temperature')| list | min < 10 }}"
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "Furnace enabled, cold weather forecast"
          data:
            tag: "furnace-enabled-cold-notification"
            group: "furnace-notification"
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        target:
          entity_id: climate.my_ecobee
