schedule:
  doorbell_do_not_distrub:
    name: "Doorbell do not disturb schedule"
    monday:
      # Dinner
      - from: "16:45"
        to: "18:00"
    tuesday:
      # Dinner
      - from: "16:45"
        to: "18:00"
    wednesday:
      # Dinner
      - from: "16:45"
        to: "18:00"
    thursday:
      # Dinner
      - from: "16:45"
        to: "18:00"
    friday:
      # Dinner
      - from: "16:45"
        to: "18:00"
    saturday:
      # Dinner
      - from: "16:45"
        to: "18:00"
    sunday:
      # Dinner
      - from: "16:45"
        to: "18:00"

automation:
  - alias: Set Doorbell Chime State
    id: doorbell_set_doorbell_chime_state
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - input_boolean.nap_mode
          - input_boolean.quite_mode
          - switch.master_white_noise
        not_to:
          - "unavailable"
          - "unknown"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id:
                  - input_boolean.nap_mode
                  - input_boolean.quite_mode
                  - switch.master_white_noise
                state: "off"
            sequence:
              - service: select.select_option
                target:
                  entity_id: select.front_door_chime_type
                data:
                  option: Mechanical
              - delay:
                  seconds: 10
              - wait_template: "{{ is_state('select.front_door_chime_type', 'Mechanical') }}"
                timeout:
                  minutes: 10
              - if:
                  - "{{ not wait.completed }}"
                then:
                  - service: select.select_option
                    target:
                      entity_id: select.front_door_chime_type
                    data:
                      option: Mechanical
                  - service: notify.mobile_app_michaels_iphone
                    data:
                      message: "Check Doorbell Mechanical State"
        default:
          - service: select.select_option
            target:
              entity_id: select.front_door_chime_type
            data:
              option: None

  - alias: Doorbell notification Message
    id: doorbell_notification_message
    mode: single
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: binary_sensor.front_door_doorbell
      from: "off"
      to: "on"
    action:
      - delay:
          seconds: 1
      # Snapshot the camera
      - service: camera.snapshot
        continue_on_error: true
        target:
          entity_id: camera.front_door_low
        data:
          filename: "/media/doorbell/snapshot.jpg"
      # Notify Everyone
      - service: notify.adults
        data:
          title: "Ding Dong"
          message: "Someone is at the front door"
          data:
            image: "/media/local/doorbell/snapshot.jpg"
            tag: "doorbell-notification"
            group: "doorbell-group"

  - alias: Doorbell activated
    id: doorbell_activated
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_doorbell
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: group.adults
        state: "home"
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "disarmed"
    action:
      - parallel:
          # Pause the TV
          - service: media_player.media_pause
            entity_id: media_player.living_room_tv
          # If it's halloween do fun things
          - choose:
              # Halloween Condition
              - conditions:
                  - condition: template
                    value_template: "{{ now().month == 10 and now().day == 31 and now().hour > 17 }}"
                  - condition: state
                    entity_id: input_boolean.nap_mode
                    state: "off"
                sequence:
                  - service: script.sonos_say
                    data:
                      entity_id:
                        - media_player.sonos_living_room
                      message: "Trick or treat!"
            default:
              - service: script.sonos_say
                data:
                  entity_id:
                    - media_player.sonos_basement
                    - media_player.sonos_living_room
                  message: "Someone is at the door"
                  volume: 30
          - service: script.blue_set_led
            data:
              color: "150" # White
              effect: "fast_blink"
              level: 70
              duration: 60 # 60 Seconds
              entity_id:
                - light.front_hall
                - light.living_room_light
                - light.back_deck_light
                - light.main_stairs
                - light.upstairs_hall
                - light.main_bath_light
                - light.basement_stairs
      - delay:
          # Debounce this from happening
          # again quickly.
          seconds: 30

  - alias: Halloween Doorbell Audio
    id: doorbell_halloween_audio_message
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_doorbell
        from: "off"
        to: "on"
    condition:
      - condition: time
        after: "16:00:00"
        before: "21:00:00"
      - condition: template
        value_template: "{{ now().month == 10 and now().day == 31 }}"
      - condition: numeric_state
        entity_id: sensor.home_nearest_distance
        below: 500
    action:
      - service: tts.cloud_say
        data:
          entity_id: media_player.front_door_speaker
          message: "Boo! Happy Halloween!"
          cache: true
      - delay:
          seconds: 60

  - alias: Doorbell package detected
    id: doorbell_package_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_package_detected
        to: "on"
    action:
      - service: camera.snapshot
        target:
          entity_id: camera.g4_doorbell_high
        data:
          filename: "/media/doorbell/package.jpg"
      - service: notify.adults
        data:
          title: "Package Detected"
          message: "Check the front porch"
          data:
            image: "/media/local/doorbell/package.jpg"
            tag: "doorbell-package-notification"
            group: "doorbell-package"

  - alias: Set doorbell message
    id: doorbell_set_message
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - switch.nap_mode
          - input_boolean.quite_mode
          - switch.master_white_noise
          - schedule.doorbell_do_not_distrub
        to:
          - "on"
          - "off"
        id: standard
      - platform: time
        at: "17:00:00"
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ now().month == 10 and now().day == 31 }}"
              - condition: numeric_state
                entity_id: sensor.home_nearest_distance
                below: 500
              - condition: time
                after: "17:00:00"
                before: "21:00:00"
            sequence:
              - service: text.set_value
                target:
                  entity_id: text.front_door_doorbell
                data:
                  value: "Trick or Treat!"
          - conditions:
              - condition: trigger
                id: standard
              - condition: state
                entity_id:
                  - switch.nap_mode
                  - input_boolean.quite_mode
                  - switch.master_white_noise
                  - schedule.doorbell_do_not_distrub
                match: any
                state: "on"
            sequence:
              - service: select.select_option
                data:
                  option: DO NOT DISTURB
                target:
                  entity_id: select.front_door_doorbell_text
        default:
          - service: select.select_option
            data:
              option: Default Message (WELCOME)
            target:
              entity_id: select.front_door_doorbell_text
