template:
  - sensor:
      - name: Current Hydro Time of Use State
        unique_id: energy_hydro_tou_state
        icon: mdi:transmission-tower
        state: >-
          {# Holidays and weekends #}
          {% if states('binary_sensor.workday_sensor') == 'off' %}
            Off Peak
          {% else %}
          {# Everything else #}
            {% if now().hour < 7 or now().hour >= 19 %}
              Off Peak
            {% elif now().hour >= 7 and now().hour < 11 %}
              {% if now().month >= 5 and now().month <= 10 %}
                Mid Peak
              {% else %}
                On Peak
              {% endif %}
            {% elif now().hour >= 11 and now().hour < 17 %}
              {% if now().month >= 5 and now().month <= 10 %}
                On Peak
              {% else %}
                Mid Peak
              {% endif %}
            {% elif now().hour >= 17 and now().hour < 19 %}
              {% if now().month >= 5 and now().month <= 10 %}
                Mid Peak
              {% else %}
                On Peak
              {% endif %}
            {% endif %}
          {% endif %}

      - name: Current Hydro TOU Rate
        unique_id: energy_hydro_tou_rate
        icon: mdi:currency-usd
        unit_of_measurement: CAD/kWh
        state: >-
          {% if states('sensor.current_hydro_time_of_use_state') == 'Off Peak' %}
            {{ states('sensor.enova_hydro_off_peak_rate') }}
          {% elif states('sensor.current_hydro_time_of_use_state') == 'Mid Peak' %}
            {{ states('sensor.enova_hydro_mid_peak_rate') }}
          {% elif states('sensor.current_hydro_time_of_use_state') == 'On Peak' %}
            {{ states('sensor.enova_hydro_on_peak_rate') }}
          {% endif %}

sensor:
  - platform: rest
    name: Enova Hydro Off Peak Rate
    unique_id: rest_enova_off_peak_rate
    icon: mdi:currency-usd
    resource: https://www.oeb.ca/_html/calculator/data/BillData.xml
    unit_of_measurement: CAD/kWh
    value_template: >-
      {% set data = value_json['BillDataTable']['BillDataRow'] %}
      {{ data | selectattr('Dist', 'eq', 'Enova Power Corp.-Kitchener-Wilmot Hydro Rate Zone') | map(attribute='RPPOffP') | first }}
  - platform: rest
    name: Enova Hydro Mid Peak Rate
    unique_id: rest_enova_mid_peak_rate
    icon: mdi:currency-usd
    resource: https://www.oeb.ca/_html/calculator/data/BillData.xml
    unit_of_measurement: CAD/kWh
    value_template: >-
      {% set data = value_json['BillDataTable']['BillDataRow'] %}
      {{ data | selectattr('Dist', 'eq', 'Enova Power Corp.-Kitchener-Wilmot Hydro Rate Zone') | map(attribute='RPPMidP') | first }}
  - platform: rest
    name: Enova Hydro On Peak Rate
    unique_id: rest_enova_on_peak_rate
    icon: mdi:currency-usd
    resource: https://www.oeb.ca/_html/calculator/data/BillData.xml
    unit_of_measurement: CAD/kWh
    value_template: >-
      {% set data = value_json['BillDataTable']['BillDataRow'] %}
      {{ data | selectattr('Dist', 'eq', 'Enova Power Corp.-Kitchener-Wilmot Hydro Rate Zone') | map(attribute='RPPOnP') | first }}
