template:
  - sensor:
      - name: Current Hydro Time of Use State
        unique_id: energy_hydro_tou_state
        icon: mdi:transmission-tower
        state: >-
          {# Holidays and weekends #}
          {% if states('binary_sensor.workday_sensor') == 'off' %}
            Off Peak
          {% else %}
          {# Everything else #}
            {% if now().hour < 7 or now().hour >= 19 %}
              Off Peak
            {% elif now().hour >= 7 and now().hour < 11 %}
              {% if now().month >= 5 and now().month <= 10 %}
                Mid Peak
              {% else %}
                On Peak
              {% endif %}
            {% elif now().hour >= 11 and now().hour < 17 %}
              {% if now().month >= 5 and now().month <= 10 %}
                On Peak
              {% else %}
                Mid Peak
              {% endif %}
            {% elif now().hour >= 17 and now().hour < 19 %}
              {% if now().month >= 5 and now().month <= 10 %}
                Mid Peak
              {% else %}
                On Peak
              {% endif %}
            {% endif %}
          {% endif %}

      - name: Current Hydro TOU Rate
        unique_id: energy_hydro_tou_rate
        icon: mdi:currency-usd
        unit_of_measurement: CAD/kWh
        state: >-
          {% if states('sensor.current_hydro_time_of_use_state') == 'Off Peak' %}
            {{ states('sensor.enova_hydro_off_peak_rate') }}
          {% elif states('sensor.current_hydro_time_of_use_state') == 'Mid Peak' %}
            {{ states('sensor.enova_hydro_mid_peak_rate') }}
          {% elif states('sensor.current_hydro_time_of_use_state') == 'On Peak' %}
            {{ states('sensor.enova_hydro_on_peak_rate') }}
          {% endif %}

sensor:
  - platform: rest
    name: Enova Hydro Off Peak Rate
    unique_id: rest_enova_off_peak_rate
    icon: mdi:currency-usd
    resource: https://www.oeb.ca/_html/calculator/data/BillData.xml
    unit_of_measurement: CAD/kWh
    value_template: >-
      {% set data = value_json['BillDataTable']['BillDataRow'] %}
      {{ data | selectattr('Dist', 'eq', 'Enova Power Corp.-Kitchener-Wilmot Hydro Rate Zone') | map(attribute='RPPOffP') | first }}
  - platform: rest
    name: Enova Hydro Mid Peak Rate
    unique_id: rest_enova_mid_peak_rate
    icon: mdi:currency-usd
    resource: https://www.oeb.ca/_html/calculator/data/BillData.xml
    unit_of_measurement: CAD/kWh
    value_template: >-
      {% set data = value_json['BillDataTable']['BillDataRow'] %}
      {{ data | selectattr('Dist', 'eq', 'Enova Power Corp.-Kitchener-Wilmot Hydro Rate Zone') | map(attribute='RPPMidP') | first }}
  - platform: rest
    name: Enova Hydro On Peak Rate
    unique_id: rest_enova_on_peak_rate
    icon: mdi:currency-usd
    resource: https://www.oeb.ca/_html/calculator/data/BillData.xml
    unit_of_measurement: CAD/kWh
    value_template: >-
      {% set data = value_json['BillDataTable']['BillDataRow'] %}
      {{ data | selectattr('Dist', 'eq', 'Enova Power Corp.-Kitchener-Wilmot Hydro Rate Zone') | map(attribute='RPPOnP') | first }}

automation:
  - alias: Save media power when not home
    id: media_energy_saver_not_home
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to:
          - armed_night
          - armed_vacation
        id: power_off
      - platform: state
        entity_id: sensor.current_hydro_time_of_use_state
        to:
          - Mid Peak
          - On Peak
        from:
          - Off Peak
        id: power_off
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to:
          - armed_away
        for:
          minutes: 30
        id: power_off
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to: disarmed
        not_from: triggered
        id: power_on
      - platform: state
        entity_id: sensor.current_hydro_time_of_use_state
        to: Off Peak
        id: power_on
      - platform: time
        at: "15:30:00"
        id: power_on
    action:
      choose:
        - conditions:
            - condition: trigger
              id: power_off
            - not:
                - condition: state
                  entity_id: media_player.apple_tv_living_room
                  state: "playing"
                - condition: state
                  entity_id: media_player.living_room_tv
                  state: "on"
          sequence:
            - service: homeassistant.turn_off
              entity_id: switch.entertainment_switch_relay
        - conditions:
            - condition: trigger
              id: power_on
            - condition: state
              entity_id: alarm_control_panel.alarmo
              state: disarmed
            - or:
                - condition: state
                  entity_id: schedule.tv_power
                  state: "on"
                - condition: state
                  entity_id: calendar.ontario_holidays
                  state: "on"
          sequence:
            - service: homeassistant.turn_on
              entity_id: switch.entertainment_switch_relay

  - alias: Save powerwall on holidays
    id: energy_save_powerwall_on_holidays
    triggers:
      - platform: state
        entity_id: schedule.holiday_powerwall
        to: "on"
        id: "son"
      - platform: state
        entity_id: schedule.holiday_powerwall
        to: "off"
    conditions:
      - condition: state
        entity_id: calendar.ontario_holidays
        state: "on"
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id: "son"
            sequence:
              - service: number.set_value
                target:
                  entity_id: number.home_backup_reserve
                data:
                  value: 100
              - service: notify.mobile_app_michaels_iphone
                data:
                  message: "Powerwall set for holidays"
                  data:
                    tag: "powerwall"
                    group: "enery"
        default:
          - service: number.set_value
            target:
              entity_id: number.home_backup_reserve
            data:
              value: 20
          - service: notify.mobile_app_michaels_iphone
            data:
              message: "Powerwall holidays off"
              data:
                tag: "powerwall"
                group: "enery"

  - alias: Save power on grid outage
    id: energy_save_power_grid_outage
    triggers:
      - platform: state
        entity_id: binary_sensor.home_grid_status
        from: "on"
        to: "off"
        id: power_loss
    actions:
      - service: homeassistant.turn_off
        target:
          entity_id:
            - switch.basement_space_heater
