homeassistant:
  customize:
    binary_sensor.front_door:
      device_class: door

timer:
  garage_left_open:
    name: Garage Left Open
    duration: 00:15:00
    restore: true

automation:
  - alias: Garage Left Open Notification
    id: exterior_garage_left_open_notification
    trigger:
      - platform: state
        entity_id: cover.garage
        to: "open"
        id: garage_open
      - platform: state
        entity_id: cover.garage
        to: "closed"
        id: garage_closed
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.garage_left_open
        id: timer_fired
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "ACK_GARAGE"
        id: ack_garage
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "CLOSE_GARAGE"
        id: close_garage
    action:
      choose:
        - conditions:
            - condition: trigger
              id: garage_open
          sequence:
            - service: timer.start
              entity_id: timer.garage_left_open
        - conditions:
            - condition: trigger
              id: timer_fired
            - condition: state
              entity_id: cover.garage
              state: "open"
          sequence:
            - service: timer.start
              entity_id: timer.garage_left_open
            - service: notify.mobile_app_michaels_iphone
              data:
                message: Garage Door Left Open
                data:
                  tag: "garage-door-open-alert"
                  entity_id: camera.garage_low
                  actions:
                    - action: "CLOSE_GARAGE"
                      title: "Close Garage"
                      activationMode: "background"
                      authenticationRequired: true
                      destructive: false
                      behavior: "default"
                    - action: "ACK_GARAGE"
                      title: "Acknowledge Garage"
                      activationMode: "background"
                      authenticationRequired: true
                      destructive: true
                      behavior: "default"
        - conditions:
            - or:
                - condition: trigger
                  id: ack_garage
                - condition: trigger
                  id: garage_closed
          sequence:
            - service: timer.cancel
              entity_id: timer.garage_left_open
            - service: notify.mobile_app_michaels_iphone
              data:
                message: "clear_notification"
                data:
                  tag: "garage-door-open-alert"
        - conditions:
            - condition: trigger
              id: close_garage
          sequence:
            - service: timer.cancel
              entity_id: timer.garage_left_open
            - service: cover.close_cover
              entity_id: cover.garage

  - alias: Exterior Lights on Evenings
    id: exterior_lights_on_evenings
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0.25
      - platform: state
        entity_id: binary_sensor.front_door_person_detected
        to: "on"
        for:
          minutes: 2
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0.25
    action:
      service: light.turn_on
      entity_id: light.exterior_lights

  - alias: Keep Exterior Lights on Evenings
    id: exterior_keep_lights_on_evenings
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - switch.front_porch
          - switch.side_door
        to: "off"
        for:
          minutes: 2
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0.25
      - condition: time
        after: "15:00:00"
        before: "23:30:00"
    action:
      service: light.turn_on
      entity_id: light.exterior_lights

  - alias: Exterior Lights off Night, or sunrise
    id: exterior_lights_off_overnight
    trigger:
      - platform: time
        at: "23:30:00"
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 0.25
    action:
      - service: light.turn_off
        entity_id: light.exterior_lights

  - alias: Keep Exterior Lights off overnight if turned on outside normal hours
    id: exterior_lights_off_outside_normal_hours
    trigger:
      - platform: state
        entity_id: light.exterior_lights
        to: "on"
        for:
          hours: 1
    condition:
      - and:
          - condition: time
            after: "23:30:00"
            before: "06:00:00" # Time condition to span midnight reset
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: 0.25
    action:
      - wait_template: '{{ is_state("binary_sensor.front_door_person_detected", "off") }}'
      - service: light.turn_off
        entity_id: light.exterior_lights

  - alias: Keep Exterior Lights off during daylight
    id: exterior_lights_off_daylight
    trigger:
      - platform: state
        entity_id: light.exterior_lights
        to: "on"
        for:
          minutes: 10
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 0.25
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 0.25
    action:
      - service: light.turn_off
        entity_id: light.exterior_lights

  - alias: Sync Exterior Lights
    id: exterior_sync_exterior_lights
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        to: ~
        entity_id:
          - light.front_porch
          - light.side_door
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.state in ["off", "on"] }}'
    action:
      service: light.turn_{{ trigger.to_state.state }}
      entity_id: light.exterior_lights

  - alias: Turn on external lights, multiple triggers
    id: exterior_exterior_lights_on_triggers
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: cover.garage
        to: "open"
      - platform: state
        entity_id: lock.locks
        to: "unlocked"
      - platform: zone
        entity_id:
          - person.mike
          - person.tiff
          - device_tracker.tesla_location
        zone: zone.home
        event: enter
      - platform: state
        entity_id: binary_sensor.doors
        to: "on"
      - platform: state
        entity_id: binary_sensor.front_door_doorbell
        from: "off"
        to: "on"
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0.25
    action:
      - service: light.turn_on
        entity_id: light.exterior_lights

  - alias: Lock the side door when forgotten feeding the dog
    id: exterior_lock_side_door_dog
    trigger:
      - platform: state
        entity_id: lock.side_door
        to: "unlocked"
        for:
          minutes: 1
      - platform: state
        entity_id: binary_sensor.side_door_open
        to: "off"
        for:
          seconds: 15
    condition:
      or:
        - condition: time
          after: "06:30:00"
          before: "08:00:00"
        - and:
            - condition: time
              after: "16:00:00"
              before: "17:00:00"
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "on"
    action:
      - wait_template: "{{ is_state('binary_sensor.side_door_open', 'off') }}"
      - service: lock.lock
        entity_id: lock.side_door

  - alias: Garage below freezeing warning
    id: exterior_garage_below_freezing
    trigger:
      - platform: numeric_state
        entity_id: sensor.garage_temperature
        below: 2.0
    action:
      - service: notify.mobile_app_michaels_iphone
        data:
          message: 🚨 Garage temperature low! 🚨

  - alias: Unlock front door when arriving home and opening garage
    id: exterior_auto_unlock_front_door_if_garage_opened
    mode: single
    max_exceeded: silent
    trigger:
      - platform: zone
        entity_id:
          - person.mike
          - person.tiff
          - device_tracker.tesla_location
        zone: zone.home
        event: enter
    action:
      - wait_for_trigger:
          - platform: state
            entity_id: cover.garage
            to: "open"
            not_from:
              - "unknown"
              - "unavailable"
        timeout:
          minutes: 15
        continue_on_timeout: false
      - service: lock.unlock
        entity_id: lock.front_door

  - alias: Lock Jammed Notification
    id: exterior_lock_jammed_notification
    mode: queued
    max: 5
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door_lock_jammed
          - binary_sensor.side_door_lock_jammed
        from: "off"
        to: "on"
    action:
      - service: notify.mobile_app_michaels_iphone
        data:
          title: "🔓 Lock Jammed 🔓"
          message: "{{ trigger.to_state.name }}"
          data:
            tag: "exterior-lock-jammed"
            push:
              sound:
                name: "default"
                critical: 1
                volume: 1.0
