alert:
  garage_open:
    name: Garage Door left open
    done_message: "clear_notification"
    entity_id: cover.garage
    state: "open"
    can_acknowledge: true
    repeat: 15
    skip_first: true
    data:
      uri: /lovelace/leak-sensors
      tag: "garage-open-alert"
      actions:
        - action: "CLOSE_GARAGE"
          title: "Close Garage"
          activationMode: "background"
          authenticationRequired: true
          destructive: false
          behavior: "default"
        - action: "ACK_GARAGE"
          title: "Acknowledge Garage"
          activationMode: "background"
          authenticationRequired: true
          destructive: true
          behavior: "default"
    notifiers:
      - mobile_app_michaels_iphone

automation:
  - alias: Exterior Lights on Evenings
    id: exterior_lights_on_evenings
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_on
      entity_id: group.exterior_lights

  - alias: Exterior Lights off Night, or sunrise
    id: exterior_lights_off_overnight
    trigger:
      - platform: time
        at: "23:30:00"
      - platform: sun
        event: sunrise
    action:
      - service: homeassistant.turn_off
        entity_id: group.exterior_lights

  - alias: Keep Exterior Lights off overnight if turned on outside normal hours
    id: exterior_lights_off_outside_normal_hours
    trigger:
      - platform: state
        entity_id: group.exterior_lights
        to: "on"
        for:
          hours: 1
    condition:
      - condition: and
        conditions:
          - condition: time
            after: "23:30:00"
            before: "10:00:00" # Time condition to span midnight reset
          - condition: sun
            before: sunrise
    action:
      - service: homeassistant.turn_off
        entity_id: group.exterior_lights

  - alias: Keep Exterior Lights off during daylight
    id: exterior_lights_off_daylight
    trigger:
      platform: state
      entity_id: group.exterior_lights
      to: "on"
      for:
        minutes: 30
    condition:
      - condition: state
        entity_id: sun.sun
        state: "above_horizon"
    action:
      - service: homeassistant.turn_off
        entity_id: group.exterior_lights

  - alias: Sync Exterior Lights
    id: exterior_sync_exterior_lights
    trigger:
      platform: state
      to: "on"
      entity_id:
        # If the front porch goes on/off update the rest
        # of the group
        - switch.front_porch
    action:
      service: >
        homeassistant.turn_on
      entity_id: group.exterior_lights

  - alias: Turn on external lights, multiple triggers
    id: exterior_exterior_lights_on_triggers
    trigger:
      - platform: state
        entity_id: cover.garage
        to: "open"
      - platform: state
        entity_id: lock.front_door
        to: "unlocked"
      - platform: zone
        entity_id:
          - person.mike
          - person.tiff
        zone: zone.home
        event: enter
    condition:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
    action:
      - service: homeassistant.turn_on
        entity_id: group.exterior_lights

  - alias: Close Garage Door Alert
    id: exterior_close_garage_alert
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "CLOSE_GARAGE"
    action:
      service: cover.close_cover
      entity_id: cover.garage

  - alias: Acknowledge Garage Door Alert
    id: exterior_ack_garage_alert
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "ACK_GARAGE"
    action:
      service: homeassistant.turn_off
      entity_id: alert.garage_open

  - alias: Prompt open when returning home from walk
    id: exterior_prompt_open_walk
    trigger:
      platform: zone
      entity_id: person.mike
      zone: zone.home
      event: enter
    condition:
      - condition: state
        entity_id: sensor.michaels_iphone_activity
        state: "Walking"
    action:
      - variables:
          action_lock: "{{ 'LOCK_' ~ context.id }}"
          action_garage: "{{ 'GARAGE_' ~ context.id }}"
          action_both: "{{ 'BOTH_' ~ context.id }}"
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "Open the house?"
          data:
            actions:
              - action: "{{ action_both }}"
                title: "Open Everything"
                activationMode: "background"
                authenticationRequired: true
                destructive: true
                behavior: "default"
              - action: "{{ action_lock }}"
                title: "Unlock Door"
                activationMode: "background"
                authenticationRequired: true
                destructive: true
                behavior: "default"
              - action: "{{ action_garage }}"
                title: "Open Garage"
                activationMode: "background"
                authenticationRequired: true
                destructive: true
                behavior: "default"
      - wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "{{ action_both }}"
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "{{ action_lock }}"
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "{{ action_garage }}"
        continue_on_timeout: false
        timeout:
          minutes: 10
      - choose:
        - conditions: "{{ wait.trigger.event.data.action == action_both }}"
          sequence:
            - service: lock.unlock
              entity_id: lock.front_door
            - service: cover.open_cover
              entity_id: cover.garage
        - conditions: "{{ wait.trigger.event.data.action == action_garage }}"
          sequence:
            - service: cover.open_cover
              entity_id: cover.garage
        - conditions: "{{ wait.trigger.event.data.action == action_lock }}"
          sequence:
            - service: lock.unlock
              entity_id: lock.front_door
