homeassistant:
  customize:
    binary_sensor.front_door:
      device_class: door

group:
  exterior_lights:
    name: Exterior Lights
    entities:
      - switch.front_porch
      - switch.side_door

alert:
  garage_open:
    name: Garage Door left open
    done_message: "clear_notification"
    entity_id: cover.garage
    state: "open"
    can_acknowledge: true
    repeat: 15
    skip_first: true
    data:
      tag: "garage-open-alert"
      entity_id: camera.garage
      actions:
        - action: "CLOSE_GARAGE"
          title: "Close Garage"
          activationMode: "background"
          authenticationRequired: true
          destructive: false
          behavior: "default"
        - action: "ACK_GARAGE"
          title: "Acknowledge Garage"
          activationMode: "background"
          authenticationRequired: true
          destructive: true
          behavior: "default"
    notifiers:
      - mobile_app_michaels_iphone

automation:
  - alias: Exterior Lights on Evenings
    id: exterior_lights_on_evenings
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0.25
      - platform: state
        entity_id: binary_sensor.front_door_person_detected
        to: "on"
        for:
          minutes: 2
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0.25
    action:
      service: homeassistant.turn_on
      entity_id: group.exterior_lights

  - alias: Keep Exterior Lights on Evenings
    id: exterior_keep_lights_on_evenings
    trigger:
      - platform: state
        entity_id:
          - switch.front_porch
          - switch.side_door
        to: "off"
        for:
          minutes: 2
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0.25
      - condition: time
        after: "15:00:00"
        before: "23:30:00"
    action:
      service: homeassistant.turn_on
      entity_id: group.exterior_lights

  - alias: Exterior Lights off Night, or sunrise
    id: exterior_lights_off_overnight
    trigger:
      - platform: time
        at: "23:30:00"
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 0.25
    action:
      - service: homeassistant.turn_off
        entity_id: group.exterior_lights

  - alias: Keep Exterior Lights off overnight if turned on outside normal hours
    id: exterior_lights_off_outside_normal_hours
    trigger:
      - platform: state
        entity_id: group.exterior_lights
        to: "on"
        for:
          minutes: 30
    condition:
      - and:
          - condition: time
            after: "23:30:00"
            before: "06:00:00" # Time condition to span midnight reset
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: 0.25
    action:
      - wait_template: '{{ is_state("binary_sensor.front_door_person_detected", "off") }}'
      - service: homeassistant.turn_off
        entity_id: group.exterior_lights

  - alias: Keep Exterior Lights off during daylight
    id: exterior_lights_off_daylight
    trigger:
      - platform: state
        entity_id: group.exterior_lights
        to: "on"
        for:
          minutes: 10
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 0.25
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 0.25
    action:
      - service: homeassistant.turn_off
        entity_id: group.exterior_lights

  - alias: Sync Exterior Lights
    id: exterior_sync_exterior_lights
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        to: ~
        entity_id:
          - switch.front_porch
          - switch.side_door
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.state in ["off", "on"] }}'
    action:
      service: homeassistant.turn_{{ trigger.to_state.state }}
      entity_id: group.exterior_lights

  - alias: Turn on external lights, multiple triggers
    id: exterior_exterior_lights_on_triggers
    trigger:
      - platform: state
        entity_id: cover.garage
        to: "open"
      - platform: state
        entity_id:
          - lock.front_door
          - lock.side_door
        to: ~
      - platform: zone
        entity_id:
          - person.mike
          - person.tiff
          - device_tracker.tesla_location
        zone: zone.home
        event: enter
      - platform: state
        entity_id: binary_sensor.front_door_doorbell
        from: "off"
        to: "on"
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0.25
    action:
      - service: homeassistant.turn_on
        entity_id: group.exterior_lights

  - alias: Close Garage Door Alert
    id: exterior_close_garage_alert
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "CLOSE_GARAGE"
    action:
      service: cover.close_cover
      entity_id: cover.garage

  - alias: Acknowledge Garage Door Alert
    id: exterior_ack_garage_alert
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "ACK_GARAGE"
    action:
      service: homeassistant.turn_off
      entity_id: alert.garage_open
