automation:
  - alias: Faux Motion for Nursery Door Event
    id: homekit_faux_event_nursery
    trigger:
      - platform: state
        entity_id: binary_sensor.nursery_door
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "on"
        for:
          minutes: 5
    action:
      - event: homekit_faux_camera_event

template:
  - trigger:
      - platform: event
        event_type: homekit_faux_camera_event
    binary_sensor:
      - name: faux_nursery_homekit_bell
        auto_off: 3
        state: "true"

switch:
  - platform: template
    switches:
      nap_mode:
        friendly_name: "Nap Mode"
        unique_id: "homekit_switch_nap_mode"
        value_template: "{{ is_state('input_boolean.nap_mode', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          target:
            entity_id: input_boolean.nap_mode
        turn_off:
          service: homeassistant.turn_off
          target:
            entity_id: input_boolean.nap_mode

homekit:
  - name: Camera Accessories Bridge
    mode: accessory
    port: 21065
    filter:
      include_entities:
        - camera.baby_high
    entity_config:
      camera.baby_high:
        video_codec: copy
        support_audio: false
        linked_doorbell_sensor: binary_sensor.faux_nursery_homekit_bell

  - name: Front Door Lock
    mode: accessory
    port: 21066
    filter:
      include_entities:
        - lock.front_door

  - name: Side Door Lock
    mode: accessory
    port: 21067
    filter:
      include_entities:
        - lock.side_door

  - name: General Accessories
    port: 21068
    filter:
      include_domains:
        - climate
        - cover
        - light
      include_entities:
        # Nursery
        - switch.nursery_fan
        - switch.nursery_white_noise
        - sensor.kid_s_room_temperature
        - switch.nap_mode
        # Front Bedroom
        - switch.spare_bedroom_fan
        # Bedroom
        - switch.master_white_noise
        - sensor.bedroom_temperature
        - switch.master_humidifier
        # Basement
        - switch.basement_hall
        # Living Room
        - switch.kitchen_island
        - sensor.living_room_temperature
      exclude_entities:
        - light.tagreader_led