script:
  blue_set_led:
    alias: "Inovelli Blue 2-1 LED Script"
    mode: parallel
    max_exceeded: error
    fields:
      color:
        description: "Color to set the color effect"
        example: "0 - red/255 - white"
      effect:
        description: "Effect pattern for LED"
        example: "solid"
      level:
        description: "Brightness level"
        example: "100"
      duration:
        description: "1-60 is in seconds calculated 61-120 is in minutes calculated by(value-60) Example a value of 65 would be 65-60 = 5 minutes - 120-254 Is in hours calculated by(value-120) Example a value of 132 would be 132-120 would be 12 hours. - 255 Indefinitely"
        example: "255"
      entity_id:
        description: "Entities to set the pattern for"
    sequence:
      - repeat:
          for_each: "{{ entity_id }}"
          sequence:
            - variables:
                z2m_id: >-
                  {% set identifiers = device_attr(repeat.item, "identifiers") | first %}
                  {{ identifiers[1].split('_') | last }}
            - service: mqtt.publish
              data:
                topic: "zigbee2mqtt/{{ z2m_id }}/set"
                payload: >-
                  {"led_effect": {"effect": "{{ effect }}",
                   "color": "{{ color }}",
                   "level": "{{ level }}",
                   "duration": "{{ duration }}"}}

  blue_set_default_level:
    alias: "Inovelli Blue Set Default Dimmer Level"
    mode: parallel
    max_exceeded: error
    fields:
      default_level:
        description: "Default Level 0-255Default level for the load when it is turned on at the switch. A setting of 255 means that the switch will return to the level that it was on before it was turned off."
        example: "255"
      entity_id:
        description: "Entities to set default level for"
    sequence:
      - repeat:
          for_each: "{{ entity_id }}"
          sequence:
            - variables:
                z2m_id: >-
                  {% set identifiers = device_attr(repeat.item, "identifiers") | first %}
                  {{ identifiers[1].split('_') | last }}
            - service: mqtt.publish
              data:
                topic: "zigbee2mqtt/{{ z2m_id }}/set"
                payload: >-
                  {"defaultLevelLocal": "{{ default_level | default(200) }}"}
            - service: mqtt.publish
              data:
                topic: "zigbee2mqtt/{{ z2m_id }}/set"
                payload: >-
                  {"defaultLevelRemote": "{{ default_level | default(200) }}"}

automation:
  - alias: Clear Switch LED signals on start
    id: inovelli_clear_led_start
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: script.blue_set_led
        data:
          color: "255" # White
          effect: "clear_effect"
          level: 70
          duration: 65 # 5 minutes
          entity_id: |
            {{ states.light
             | map(attribute="entity_id")
             | select('is_device_attr', 'model', '2-in-1 switch + dimmer (VZM31-SN)')
             | list}}
