automation:
  - alias: "Reset Modem when internet down"
    id: internet_reset_modem_internet_down
    trigger:
      - platform: state
        entity_id: binary_sensor.internet_state
        from: "on"
        to: "off"
        for:
          minutes: 30
    action:
      - service: notify.adults
        data:
          title: "Internet down"
          message: "Attempting to reset modem"
          data:
            tag: "internet-down-notification"
            group: "internet-notification"
      - repeat:
          sequence:
            - service: homeassistant.turn_off
              entity_id: switch.modem_reset
            - delay:
                seconds: 30
            - service: homeassistant.turn_on
              entity_id: switch.modem_reset
            - delay:
                minutes: 15
          until:
            - condition: state
              state: "on"
              entity_id: binary_sensor.internet_state
      - service: notify.adults
        data:
          title: "Internet Restored"
          data:
            tag: "internet-up-notification"
            group: "internet-notification"
