automation:
  - alias: "Reset Modem when internet down"
    id: internet_reset_modem_internet_down
    trigger:
      - platform: state
        entity_id: binary_sensor.internet_state
        from: "on"
        to: "off"
        for:
          minutes: 30
    action:
      - service: notify.adults
        data:
          title: "Internet down"
          message: "Attempting to reset modem"
          data:
            tag: "internet-down-notification"
            group: "internet-notification"
      - repeat:
          sequence:
            - service: homeassistant.turn_off
              entity_id: switch.modem_reset
            - delay:
                seconds: 30
            - service: homeassistant.turn_on
              entity_id: switch.modem_reset
            - service: notify.mobile_app_michaels_iphone
              data:
                message: "Modem Toggled"
            - delay:
                minutes: 15
          until:
            - condition: state
              state: "on"
              entity_id: binary_sensor.internet_state
      - service: notify.adults
        data:
          message: "Internet Restored"
          data:
            tag: "internet-up-notification"
            group: "internet-notification"

  - alias: Internet down notify Inovelli LEDs
    id: internet_notify_leds
    trigger:
      - platform: state
        entity_id: binary_sensor.internet_state
        from: "on"
        to: "off"
        id: internet_down
      - platform: state
        entity_id: binary_sensor.internet_state
        from: "off"
        to: "on"
        id: internet_up
    condition:
      - condition: state
        entity_id: group.adults
        state: "home"
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "disarmed"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: internet_down
            sequence:
              - service: script.blue_set_led
                data:
                  color: 225
                  effect: "pulse"
                  level: 100
                  duration: 255
                  entity_id:
                    - light.front_hall
                    - light.living_room_light
                    - light.back_deck_light
                    - light.main_stairs
                    - light.upstairs_hall
                    - light.basement_stairs
                    - light.basement_room_light_dimmer
          - conditions:
              - condition: trigger
                id: internet_up
            sequence:
              - service: script.blue_set_led
                data:
                  color: 225
                  effect: "clear_effect"
                  level: 100
                  duration: 255
                  entity_id:
                    - light.front_hall
                    - light.living_room_light
                    - light.back_deck_light
                    - light.main_stairs
                    - light.upstairs_hall
                    - light.basement_stairs
                    - light.basement_room_light_dimmer
