input_datetime:
  pickup_girls_reminder:
    name: Pickup Girls Reminder
    has_date: true
    has_time: true

automation:
  - alias: Pick up girls reminder
    id: pick_up_girls_reminder
    mode: single
    max_exceeded: silent
    trigger:
      - platform: zone
        entity_id:
          - device_tracker.michaels_iphone
          - device_tracker.tiffanys_iphone
        zone: zone.school
        event: enter
        id: enter_pickup_zone
      - platform: zone
        entity_id:
          - device_tracker.michaels_iphone
          - device_tracker.tiffanys_iphone
        zone: zone.camp
        event: enter
        id: enter_camp_zone
      - platform: time
        at: input_datetime.pickup_girls_reminder
        id: pickup_reminder
    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: time
        after: "06:00:00"
        before: "16:00:00"
    action:
      - choose:
          - conditions:
              - or:
                  - and:
                      - condition: trigger
                        id: enter_pickup_zone
                      - condition: template
                        value_template: "{{ now().month >= 9 or now().month <= 6 }}"
                  - condition: trigger
                    id: enter_camp_zone
            sequence:
              if:
                - condition: trigger
                  id: enter_camp_zone
              then:
                - service: input_datetime.set_datetime
                  target:
                    entity_id: input_datetime.pickup_girls_reminder
                  data:
                    date: "{{ now().strftime('%Y-%m-%d') }}"
                    time: "{{ states('input_datetime.camp_pickup_time') }}"
              else:
                - service: input_datetime.set_datetime
                  target:
                    entity_id: input_datetime.pickup_girls_reminder
                  data:
                    date: "{{ now().strftime('%Y-%m-%d') }}"
                    time: "15:45:00"
          - conditions:
              - condition: trigger
                id: pickup_reminder
            sequence:
              - service: notify.mobile_app_michaels_iphone
                data:
                  title: "Pickup Reminder"
                  message: "Pickup the twins!"
                  data:
                    tag: "pickup-reminder"
                    group: "pickup-notification"
                    push:
                      sound:
                        name: "default"
                        critical: 1
                        volume: 0.5
