automation:
  - alias: Pick up girls reminder
    id: pick_up_girls_reminder
    mode: single
    max_exceeded: silent
    trigger:
      platform: zone
      entity_id:
        - person.mike
        - device_tracker.tesla_location
      zone: zone.daycare
      event: enter
    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: time
        before: "15:00:00"
    action:
      - wait_for_trigger:
          - platform: numeric_state
            entity_id: proximity.daycare
            above: 500 # m from zone.
      - wait_for_trigger:
          - platform: zone
            entity_id:
              - person.mike
              - device_tracker.tesla_location
            zone: zone.daycare
            event: enter
            id: reentry
          - platform: time
            at: "15:45:00"
            id: "message_send"
        timeout: "10:00:00"
        continue_on_timeout: false
      - choose:
          - conditions: "{{ wait.trigger.id == 'message_send' }}"
            sequence:
              - service: notify.mobile_app_michaels_iphone
                data:
                  title: "Pickup Reminder"
                  message: "Pickup the twins!"
