binary_sensor:
  - platform: bayesian
    name: "Girls Home Bayesian"
    prior: 0.58
    probability_threshold: 0.9
    observations:
      # Not a workday, likely home
      - platform: state
        entity_id: binary_sensor.workday_sensor
        to_state: "off"
        prob_given_true: 0.85
      - platform: template
        value_template: >
          {{ (now().hour > 16 or now().hour < 8) }}
        #and is_state('binary_sensor.workday_sensor', 'on') }}
        prob_given_true: 0.80
        prob_given_false: 0.33
      - platform: state
        entity_id: group.adults
        to_state: "home"
        prob_given_true: 0.7
        prob_given_false: 0.2
      - platform: state
        entity_id: binary_sensor.guests_present
        to_state: "on"
        prob_given_true: 0.85
        prob_given_false: 0.1
      # Did not visit school, likely home
      - platform: template
        value_template: >
          {{ as_local(state_attr('automation.pick_up_girls_reminder', 'last_triggered')).day != now().day}}
        prob_given_true: 0.67
      # Parents not home, sitters home, likely home.
      - platform: template
        value_template: >
          {{ is_state('group.adults', 'not_home') and is_state('group.sitters', 'home') }}
        prob_given_true: 0.99
        prob_given_false: 0.02

automation:
  - alias: Pick up girls reminder
    id: pick_up_girls_reminder
    mode: single
    max_exceeded: silent
    trigger:
      platform: zone
      entity_id:
        - person.mike
        - device_tracker.tesla_location
      zone: zone.daycare
      event: enter
    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: time
        before: "15:00:00"
    action:
      - wait_for_trigger:
          - platform: numeric_state
            entity_id: proximity.daycare
            above: 500 # m from zone.
      - wait_for_trigger:
          - platform: zone
            entity_id:
              - person.mike
              - device_tracker.tesla_location
            zone: zone.daycare
            event: enter
            id: reentry
          - platform: time
            at: "15:45:00"
            id: "message_send"
        timeout: "10:00:00"
        continue_on_timeout: false
      - choose:
          - conditions: "{{ wait.trigger.id == 'message_send' }}"
            sequence:
              - service: notify.mobile_app_michaels_iphone
                data:
                  title: "Pickup Reminder"
                  message: "Pickup the twins!"
