input_datetime:
  pickup_girls_reminder:
    name: Pickup Girls Reminder
    has_date: true
    has_time: true

automation:
  - alias: Pick up girls reminder
    id: pick_up_girls_reminder
    mode: single
    max_exceeded: silent
    trigger:
      - platform: zone
        entity_id:
          - device_tracker.michaels_iphone
          - device_tracker.tiffanys_iphone
        zone: zone.school
        event: enter
        id: enter_pickup_zone
      - platform: time
        at: input_datetime.pickup_girls_reminder
        id: pickup_reminder
    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: time
        after: "06:00:00"
        before: "16:00:00"
    action:
      - choose:
        - conditions:
            - condition: trigger
              id: enter_pickup_zone
          sequence:
            - service: input_datetime.set_datetime
              target:
                entity_id: input_datetime.pickup_girls_reminder
              data:
                date: "{{ now().strftime('%Y-%m-%d') }}"
                time: '15:45:00'
        - conditions:
            - condition: trigger
              id: pickup_reminder
          sequence:
            - service: notify.mobile_app_michaels_iphone
              data:
                title: "Pickup Reminder"
                message: "Pickup the twins!"
                data:
                  tag: "pickup-reminder"
                  group: "pickup-notification"
                  push:
                    sound:
                      name: "default"
                      critical: 1
                      volume: 0.5

  - alias: School Absence Notification
    id: kids_school_absence
    trigger:
      - platform: state
        entity_id: input_button.both_absent
        id: both_absent
        variables:
          name: "Meredith and Vivian O'Driscoll"
      - platform: state
        entity_id: input_button.vivian_absent
        id: vivian_absent
        variables:
          name: "Vivian O'Driscoll"
      - platform: state
        entity_id: input_button.meredith_absent
        id: meredith_absent
        variables:
          name: "Meredith O'Driscoll"
    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: template
        value_template: "{{ (trigger.from_state.state | as_datetime).day != utcnow().day }}"
    action:
      - service: notify.school_absence
        data:
          title: "Absence {{ now().strftime('%h %d, %Y') }} - {{name}}"
          message: "{{ name }} will be absent today. {{trigger.from_state.state}} / {{trigger.to_state.state}} / {{utcnow().day}}"
