sensor:
  - platform: statistics
    name: Washing Machine Power Average
    entity_id: sensor.washing_machine_electric_consumption_w
    state_characteristic: mean
    max_age:
      minutes: 2

template:
  - binary_sensor:
      - name: Washer Status
        unique_id: laundry_binary_sensor_status
        icon: mdi:washing-machine
        state: "{{ states('sensor.washing_machine_power_average') | float(0) | default(0) > 4 }}"
        device_class: running
        delay_on:
          seconds: 60
        delay_off:
          seconds: 120

automation:
  - alias: Laundry Notification
    id: laundry_simple_laundry_notification
    trigger:
      - platform: state
        entity_id: binary_sensor.washer_status
        from: "on"
        to: "off"
    action:
      - wait_template: "{{ is_state('group.adults', 'home') }}"
      - repeat:
          until:
            or:
              - condition: state
                entity_id: binary_sensor.dryer_running
                state: "on"
                for:
                  minutes: 5
              - condition: template
                value_template: "{{ wait.trigger is not none }}"
          sequence:
            - repeat:
                for_each: >
                  {{ states.person | selectattr('state', 'eq', 'home') | map(attribute='attributes.notifier') | list}}
                sequence:
                  - service: "{{ repeat.item }}"
                    data:
                      title: Laundry is done!
                      message: Laundry cycle complete
                      data:
                        tag: "laundry-done-notification"
                        group: "laundry-notification-group"
                        actions:
                          - action: "laundry_moved"
                            title: "Laundry Moved"
                            authenticationRequired: true
                            destructive: true
                            behavior: "default"
            - wait_for_trigger:
                - platform: event
                  event_type: mobile_app_notification_action
                  event_data:
                    action: "laundry_moved"
                - platform: state
                  entity_id: binary_sensor.dryer_running
                  to: "on"
                  for:
                    minutes: 5
                - platform: state
                  entity_id: binary_sensor.washer_status
                  from: "on"
                  to: "off"
                  for:
                    minutes: 15
              timeout:
                minutes: 30
      - service: notify.adults
        data:
          message: "clear_notification"
          data:
            tag: "laundry-done-notification"
