input_datetime:
  laundry_complete:
    has_time: true
    has_date: true
    icon: mdi:washing-machine

automation:
  - alias: Laundry Completed
    trigger:
      - platform: time
        at: input_datetime.laundry_complete
    action:
      - service: notify.mobile_app_tiffanys_iphone
        data:
          title: "Laundry is done!"
          message: "Laundry cycle complete"
