sensor:
  - platform: statistics
    name: Washing Machine Power Average
    entity_id: sensor.washing_machine_electric_consumption_w
    state_characteristic: mean
    max_age:
      minutes: 5

template:
  - binary_sensor:
      - name: Washer Status
        unique_id: laundry_binary_sensor_status
        icon: mdi:washing-machine
        state: "{{ states('sensor.washing_machine_power_average') | float(0) | default(0) > 4 }}"
        device_class: running
        delay_on:
          seconds: 60
        delay_off:
          seconds: 120

automation:
  - alias: Laundry Notification
    id: laundry_simple_laundry_notification
    trigger:
      - platform: state
        entity_id: binary_sensor.washer_status
        to: "off"
    action:
      - service: notify.adults
        data:
          title: Laundry is done!
          message: Landry cycle complete
          data:
            tag: laundry-notification
