alert:
  water_leak:
    name: Water Leak Detected
    done_message: "Leak Cleared"
    entity_id: group.leak_sensors
    state: "on"
    can_acknowledge: true
    repeat: 30
    data:
      uri: /lovelace/leak-sensors
      tag: "water-leak-alert"
      actions:
        - action: "ACK_LEAK"
          title: "Acknowledge Leak"
          activationMode: "background"
          authenticationRequired: true
          destructive: true
          behavior: "default"
      push:
        sound:
          name: "US-EN-Alexa-Water-Detected-Generic.wav"
          critical: 1
          volume: 1.0
    notifiers:
      - mobile_app_michaels_iphone

automation:
  - alias: Acknowledge Leak
    id: leak_ack_leak
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "ACK_LEAK"
    action:
      service: homeassistant.turn_off
      entity_id: alert.water_leak