automation:
  - alias: Set Switch Status LEDs
    id: living_set_switch_status_leds
    trigger:
      - platform: state
        entity_id: group.locks
        to: "locked"
        id: "doors_locked"
      - platform: state
        entity_id: group.locks
        to: "unlocked"
        id: "doors_unlocked"
    action:
      - choose:
          - conditions:
            - condition: trigger
              id: "doors_unlocked"
            sequence:
              # Set red LED
              - service: script.lzw30_set_led
                data:
                  entity: switch.kitchen_island
                  led_colour: 0
                  led_brightness: 10
          - conditions:
            - condition: trigger
              id: "doors_locked"
            sequence:
              # Set blue LED
              - service: script.lzw30_set_led
                data:
                  entity: switch.kitchen_island
                  led_colour: 170
                  led_brightness: 5

