automation:
  - alias: Turn living room lights on when dark
    id: living_room_lights_on_when_dark
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_occupancy
        to: "on"
    condition:
      - condition: state
        entity_id: light.kitchen_island
        state: "off"
        for:
          minutes: 15
      - condition: numeric_state
        entity_id: sensor.living_room_illuminance_lux
        below: 50
      - condition: state
        entity_id: group.adults
        state: "home"
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "disarmed"
    action:
      - service: light.turn_on
        entity_id: light.kitchen_island

  - alias: Garage Control with Kitchen Switch
    id: living_garage_control_kitchen_switch
    trigger:
      - platform: state
        entity_id: sensor.kitchen_light_action
        to: "up_triple"
        id: garage_up_trigger
      - platform: state
        entity_id: sensor.kitchen_light_action
        to: "down_triple"
        id: garage_down_trigger
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "garage_up_trigger"
            sequence:
              - service: cover.open_cover
                entity_id: cover.garage
          - conditions:
              - condition: trigger
                id: "garage_down_trigger"
            sequence:
              - service: cover.close_cover
                entity_id: cover.garage

  - alias: Lock Control with Living Switch
    id: living_front_lock_control_living_switch
    trigger:
      - platform: state
        entity_id: sensor.living_room_action
        to: "up_triple"
        id: door_unlock_trigger
      - platform: state
        entity_id: sensor.living_room_action
        to: "down_triple"
        id: door_lock_trigger
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "door_unlock_trigger"
            sequence:
              - service: lock.unlock
                entity_id: lock.front_door
          - conditions:
              - condition: trigger
                id: "door_lock_trigger"
            sequence:
              - service: lock.lock
                entity_id: lock.front_door

  - alias: Living room light group multitap control
    id: living_room_light_group_multitap_control
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - sensor.living_room_action
          - sensor.kitchen_light_action
        to: "up_double"
        id: turn_on
      - platform: state
        entity_id:
          - sensor.living_room_action
          - sensor.kitchen_light_action
        to: "down_double"
        id: turn_off
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: turn_on
            sequence:
              - service: light.turn_on
                entity_id: light.living_room_light_group
          - conditions:
              - condition: trigger
                id: turn_off
            sequence:
              - service: light.turn_off
                entity_id: light.living_room_light_group

  - alias: Turn on lights when arriving home
    id: living_room_turn_on_lights_arrival_dark
    trigger:
      - platform: state
        entity_id: group.adults
        to: "home"
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 2.0
      - condition: state
        entity_id: binary_sensor.guests_present
        state: "off"
    action:
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.front_door
            to: "on"
        timeout:
          minutes: 30
        continue_on_timeout: false
      - parallel:
          - if:
              - not:
                  - condition: state
                    entity_id: media_player.plex_plex_for_apple_tv_living_room
                    state: "playing"
            then:
              - service: light.turn_on
                entity_id: light.living_room_light_group
                data:
                  brightness_pct: 65
                  transition: 20
          - service: light.turn_on
            entity_id: light.front_hall
            data:
              brightness_pct: 65
              transition: 5

  - alias: Set Main floor Lights default local level
    id: main_floor_light_default_local_level
    mode: single
    max_exceeded: silent
    trigger:
      - platform: sun
        event: sunset
        variables:
          default_level: 80
      - platform: state
        entity_id: input_boolean.nap_mode
        to: "on"
        variables:
          default_level: 80
      - platform: sun
        event: sunrise
        variables:
          default_level: 200
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to: "armed_night"
        variables:
          default_level: 60
    action:
      parallel:
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/Living Room Light/set
            payload: >-
              {"defaultLevelLocal": "{{ default_level | default(100) }}",
               "defaultLevelRemote": "{{ default_level | default(100) }}"}
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/Kitchen Light/set
            payload: >-
              {"defaultLevelLocal": "{{ default_level | default(100) }}",
               "defaultLevelRemote": "{{ default_level | default(100) }}"}
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/Front Hall/set
            payload: >-
              {"defaultLevelLocal": "{{ default_level | default(100) }}",
               "defaultLevelRemote": "{{ default_level | default(100) }}"}
