automation:
  - alias: Set Switch Status LEDs
    id: living_set_switch_status_leds
    trigger:
      - platform: state
        entity_id: group.locks
        to: "locked"
        id: "doors_locked"
      - platform: state
        entity_id: group.locks
        to: "unlocked"
        id: "doors_unlocked"
    action:
      - choose:
          - conditions:
            - condition: trigger
              id: "doors_unlocked"
            sequence:
              # Set red LED
              - service: script.lzw30_set_led
                data:
                  entity: switch.kitchen_island
                  led_colour: 0
                  led_brightness: 10
          - conditions:
            - condition: trigger
              id: "doors_locked"
            sequence:
              # Set blue LED
              - service: script.lzw30_set_led
                data:
                  entity: switch.kitchen_island
                  led_colour: 170
                  led_brightness: 5

  - alias: Garage Control with Kitchen Switch
    id: living_garage_control_kitchen_switch
    trigger:
      - platform: event
        id: garage_up_trigger
        event_type: zha_event
        event_data:
          device_id: acf54e514580d88c801347c10c5355ee
          command: button_2_double
          args:
            button: button_2
            press_type: double
            command_id: 0
      - platform: event
        id: garage_down_trigger
        event_type: zha_event
        event_data:
          device_id: acf54e514580d88c801347c10c5355ee
          command: button_1_double
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "garage_up_trigger"
            sequence:
              - service: cover.open_cover
                entity_id: cover.garage
          - conditions:
              - condition: trigger
                id: "garage_down_trigger"
            sequence:
              - service: cover.close_cover
                entity_id: cover.garage

  - alias: Lock Control with Living Switch
    id: living_front_lock_control_living_switch
    trigger:
      - platform: event
        id: door_unlock_trigger
        event_type: zha_event
        event_data:
          device_id: b2e1fe5291c815d4f340372d29d4cd55
          command: button_2_double
          args:
            button: button_2
            press_type: double
            command_id: 0
      - platform: event
        id: door_lock_trigger
        event_type: zha_event
        event_data:
          device_id: b2e1fe5291c815d4f340372d29d4cd55
          command: button_1_double
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "door_unlock_trigger"
            sequence:
              - service: lock.unlock
                entity_id: lock.front_door
          - conditions:
              - condition: trigger
                id: "door_lock_trigger"
            sequence:
              - service: lock.lock
                entity_id: lock.front_door
