automation:
  - alias: Set Switch Status LEDs
    id: living_set_switch_status_leds
    trigger:
      - platform: state
        entity_id: group.locks
        to: "locked"
        id: "doors_locked"
      - platform: state
        entity_id: group.locks
        to: "unlocked"
        id: "doors_unlocked"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "doors_unlocked"
            sequence:
              # Set red LED
              - service: script.lzw30_set_led
                data:
                  entity: switch.kitchen_island
                  led_colour: 0
                  led_brightness: 10
          - conditions:
              - condition: trigger
                id: "doors_locked"
            sequence:
              # Set blue LED
              - service: script.lzw30_set_led
                data:
                  entity: switch.kitchen_island
                  led_colour: 170
                  led_brightness: 5

  - alias: Garage Control with Kitchen Switch
    id: living_garage_control_kitchen_switch
    trigger:
      - platform: state
        entity_id: sensor.kitchen_light_action
        to: "up_double"
        id: garage_up_trigger
      - platform: state
        entity_id: sensor.kitchen_light_action
        to: "down_double"
        id: garage_down_trigger
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "garage_up_trigger"
            sequence:
              - service: cover.open_cover
                entity_id: cover.garage
          - conditions:
              - condition: trigger
                id: "garage_down_trigger"
            sequence:
              - service: cover.close_cover
                entity_id: cover.garage

  - alias: Lock Control with Living Switch
    id: living_front_lock_control_living_switch
    trigger:
      - platform: state
        entity_id: sensor.living_room_action
        to: "up_double"
        id: door_unlock_trigger
      - platform: state
        entity_id: sensor.living_room_action
        to: "down_double"
        id: door_lock_trigger
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "door_unlock_trigger"
            sequence:
              - service: lock.unlock
                entity_id: lock.front_door
          - conditions:
              - condition: trigger
                id: "door_lock_trigger"
            sequence:
              - service: lock.lock
                entity_id: lock.front_door

  - alias: Turn on living room lights when arriving home
    id: living_room_turn_on_lights_arrival_dark
    trigger:
      - platform: state
        entity_id: group.adults
        to: "home"
      - platform: state
        entity_id: lock.front_door
        to: "unlocked"
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 2.0
      - not:
          - condition: state
            entity_id: media_player.plex_plex_for_apple_tv_living_room
            state: "playing"
      - condition: state
        entity_id: binary_sensor.guests_present
        state: "off"
    action:
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.front_door
            to: "on"
        timeout:
          minutes: 10
        continue_on_timeout: false
      - service: light.turn_on
        target:
          entity_id: light.living_room_lights
        data:
          brightness_pct: 70
          transition: 10
