automation:
  - alias: Turn living room lights on when dark
    id: living_room_lights_on_when_dark
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_occupancy
        to: "on"
    condition:
      - condition: state
        entity_id: light.kitchen_island
        state: "off"
        for:
          minutes: 15
      - condition: numeric_state
        entity_id: sensor.living_room_motion_illuminance
        below: 20
      - condition: state
        entity_id: group.adults
        state: "home"
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "disarmed"
    action:
      - service: light.turn_on
        entity_id: light.kitchen_island

  - alias: Front Hall Lock and Garage Control
    id: living_front_hall_lock_garage_control
    trigger:
      - trigger: device
        domain: mqtt
        device_id: 949dd8fd2c9e4403656fc84e75de9607
        type: action
        subtype: up_triple
        id: lock_unlock
      - trigger: device
        domain: mqtt
        device_id: 949dd8fd2c9e4403656fc84e75de9607
        type: action
        subtype: up_quadruple
        id: garage_up
      - trigger: device
        domain: mqtt
        device_id: 949dd8fd2c9e4403656fc84e75de9607
        type: action
        subtype: down_triple
        id: lock_lock
      - trigger: device
        domain: mqtt
        device_id: 949dd8fd2c9e4403656fc84e75de9607
        type: action
        subtype: down_quadruple
        id: garage_down
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: lock_unlock
            sequence:
              - service: lock.unlock
                entity_id: lock.front_door
          - conditions:
              - condition: trigger
                id: lock_lock
            sequence:
              - service: lock.lock
                entity_id: lock.front_door
          - conditions:
              - condition: trigger
                id: garage_up
            sequence:
              - service: cover.open_cover
                entity_id: cover.garage
          - conditions:
              - condition: trigger
                id: garage_down
            sequence:
              - service: cover.close_cover
                entity_id: cover.garage

  - alias: Garage Control with Kitchen Switch
    id: living_garage_control_kitchen_switch
    trigger:
      - trigger: device
        domain: mqtt
        # Kitchen Light
        device_id: e97867a8181f2b6c5aef264706584f91
        type: action
        subtype: up_triple
        id: garage_up_trigger
      - trigger: device
        domain: mqtt
        # Kitchen Light
        device_id: e97867a8181f2b6c5aef264706584f91
        type: action
        subtype: down_triple
        id: garage_down_trigger
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "garage_up_trigger"
            sequence:
              - service: cover.open_cover
                entity_id: cover.garage
          - conditions:
              - condition: trigger
                id: "garage_down_trigger"
            sequence:
              - service: cover.close_cover
                entity_id: cover.garage

  - alias: Lock Control with Living Switch
    id: living_front_lock_control_living_switch
    trigger:
      - trigger: device
        domain: mqtt
        # Living Room Light
        device_id: c2fce543d85f8ffccd89691a42f784d9
        type: action
        subtype: up_triple
        id: garage_up_trigger
      - trigger: device
        domain: mqtt
        # Living Room Light
        device_id: c2fce543d85f8ffccd89691a42f784d9
        type: action
        subtype: down_triple
        id: garage_down_trigger
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: "door_unlock_trigger"
            sequence:
              - service: lock.unlock
                entity_id: lock.front_door
          - conditions:
              - condition: trigger
                id: "door_lock_trigger"
            sequence:
              - service: lock.lock
                entity_id: lock.front_door

  - alias: Living room light group multitap control
    id: living_room_light_group_multitap_control
    mode: single
    max_exceeded: silent
    triggers:
      # Living Room
      - trigger: device
        domain: mqtt
        device_id: c2fce543d85f8ffccd89691a42f784d9
        type: action
        subtype: up_double
        id: turn_on
      - trigger: device
        domain: mqtt
        device_id: c2fce543d85f8ffccd89691a42f784d9
        type: action
        subtype: down_double
        id: turn_off
      # Kitchen Light
      - trigger: device
        domain: mqtt
        device_id: e97867a8181f2b6c5aef264706584f91
        type: action
        subtype: up_double
        id: turn_on
      - trigger: device
        domain: mqtt
        device_id: e97867a8181f2b6c5aef264706584f91
        type: action
        subtype: down_double
        id: turn_off
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: turn_on
            sequence:
              - service: light.turn_on
                entity_id: light.living_room_light_group
          - conditions:
              - condition: trigger
                id: turn_off
            sequence:
              - service: light.turn_off
                entity_id: light.living_room_light_group

  - alias: Turn on lights when arriving home
    id: living_room_turn_on_lights_arrival_dark
    trigger:
      - platform: state
        entity_id: group.adults
        to: "home"
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 2.0
      - condition: state
        entity_id: binary_sensor.guests_present
        state: "off"
    action:
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.front_door
            to: "on"
        timeout:
          minutes: 30
        continue_on_timeout: false
      - parallel:
          - if:
              - not:
                  - condition: state
                    entity_id: media_player.apple_tv_living_room
                    state: "playing"
            then:
              - service: light.turn_on
                entity_id: light.living_room_light_group
          - service: light.turn_on
            entity_id: light.front_hall

  - alias: Set Main floor Lights default local level
    id: main_floor_light_default_local_level
    mode: single
    max_exceeded: silent
    trigger:
      - platform: sun
        event: sunset
        variables:
          default_level: 80
      - platform: state
        entity_id: input_boolean.nap_mode
        to: "on"
        variables:
          default_level: 80
      - platform: sun
        event: sunrise
        variables:
          default_level: 200
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to: "armed_night"
        variables:
          default_level: 60
    action:
      - service: script.blue_set_default_level
        data:
          default_level: "{{ default_level | default(100) }}"
          entity_id:
            - light.kitchen_light
            - light.living_room_light
            - light.front_hall

  - alias: Front door open turns on front hall light
    id: main_floor_front_door_turn_on_hall_light
    mode: single
    max_exceeded: silent
    triggers:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 5.0
      - condition: time
        before: "21:30:00"
    actions:
      - service: light.turn_on
        entity_id: light.front_hall

  - alias: Turn off front hall lights
    id: main_floor_front_hall_light_off_high_sun_elevation
    triggers:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 10.0
    actions:
      - service: light.turn_off
        entity_id:
          - light.front_hall

  - alias: Set Adaptive on Living Room Late Mornings
    id: cd72c85e-327a-4958-8e2b-fef856573302
    trigger:
      - platform: time
        at: "09:30:00"
    condition:
      - condition: state
        entity_id: light.living_room_light_group
        state: "on"
    action:
      - service: adaptive_lighting.apply
        data:
          entity_id: switch.adaptive_lighting_adapt_brightness_living_room
