automation:
  - alias: Set sonos volume on TV watching
    id: sonos_media_volume
    trigger:
      - platform: state
        entity_id: media_player.plex_plex_for_apple_tv_living_room
        to: "playing"
        id: to_playing
      - platform: state
        entity_id: media_player.plex_plex_for_apple_tv_living_room
        from: "playing"
        for:
          minutes: 5
        id: not_playing
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: to_playing
            sequence:
              - service: media_player.volume_set
                data:
                  volume_level: 0.18
                entity_id: media_player.sonos_living_room
          - conditions:
              - condition: trigger
                id: not_playing
            sequence:
              - service: media_player.volume_set
                data:
                  volume_level: 0.10
                entity_id: media_player.sonos_living_room
