automation:
  - alias: Set sonos volume on TV watching
    id: sonos_media_volume
    trigger:
      - platform: state
        entity_id: media_player.plex_plex_for_android_tv_living_room
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'playing' }}"
            sequence:
              - service: media_player.volume_set
                data:
                  volume_level: 0.5
                entity_id: media_player.sonos_living_room
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state != 'playing' }}"
            sequence:
              - service: media_player.volume_set
                data:
                  volume_level: 0.15
                entity_id: media_player.sonos_living_room
