automation:
  - alias: Set sonos volume on TV watching
    id: sonos_media_volume
    trigger:
      - platform: state
        entity_id: media_player.plex_plex_for_apple_tv_living_room
        to: "playing"
        id: to_playing
      - platform: state
        entity_id: media_player.plex_plex_for_apple_tv_living_room
        from: "playing"
        for:
          minutes: 5
        id: not_playing
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: to_playing
            sequence:
              - service: media_player.volume_set
                data:
                  volume_level: 0.18
                entity_id: media_player.sonos_living_room
          - conditions:
              - condition: trigger
                id: not_playing
            sequence:
              - service: media_player.volume_set
                data:
                  volume_level: 0.10
                entity_id: media_player.sonos_living_room

  - alias: Save power when not home
    id: media_energy_saver_not_home
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to:
          - armed_night
          - armed_vacation
        id: power_off
      - platform: state
        entity_id: sensor.current_hydro_time_of_use_state
        to:
          - Mid Peak
          - On Peak
        id: power_off
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to:
          - armed_away
        for:
          minutes: 30
        id: power_off
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to: disarmed
        id: power_on
      - platform: state
        entity_id: sensor.current_hydro_time_of_use_state
        to: Off Peak
        id: power_on
    action:
      choose:
        - conditions:
            - condition: trigger
              id: power_off
            - not:
                - condition: state
                  entity_id: media_player.apple_tv_living_room
                  state: "playing"
                - condition: state
                  entity_id: media_player.living_room_tv
                  state: "on"
          sequence:
            - service: homeassistant.turn_off
              entity_id: switch.entertainment_switch_relay
        - conditions:
            - condition: trigger
              id: power_on
            - not:
                - condition: template
                  value_template: '{{ "Peak" in states("sensor.current_hydro_time_of_use_state") }}'
          sequence:
            - service: homeassistant.turn_on
              entity_id: switch.entertainment_switch_relay
