automation:
  - alias: Morning Wake Up Sequence
    id: mornings_wake_up_sequence
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: "ios_wakeup_event"
      - platform: state
        entity_id: input_boolean.nap_mode
        to: "off"
    condition:
      - condition: state
        entity_id: group.adults
        state: "home"
      - condition: time
        after: "05:00:00"
        before: "09:00:00"
      - or:
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: 3.0
          - condition: numeric_state
            entity_id: sensor.tomorrow_io_home_cloud_cover
            above: 65
    action:
      - if:
          - condition: state
            entity_id: valve.water_shutoff
            state: "closed"
        then:
          - service: notify.mobile_app_michaels_iphone
            data:
              message: "🚰 Water is Off 🚰"
              data:
                tag: "water-alert"
                actions:
                  - action: "OPEN_WATER_VALVE"
                    title: "Open Water Valve"
                    activationMode: "background"
                    authenticationRequired: true
                    destructive: true
                    behavior: "default"
                push:
                  interruption-level: critical
                url: /dashboard-security/home
                clickAction: /dashboard-security/home
      - service: homeassistant.turn_on
        target:
          label_id: christmas_tree
        entity_id:
          - light.kitchen_island
      - wait_template: "{{ is_state('binary_sensor.living_room_occupancy', 'on') }}"
        timeout:
          hours: 1
        continue_on_timeout: false
      - if:
          - condition: state
            entity_id: person.mike
            state: "home"
          - condition: state
            entity_id: binary_sensor.michaels_iphone_focus
            state: "off"
        then:
          - service: light.turn_on
            target:
              entity_id:
                - light.kitchen_light
                - light.living_room_light
            data:
              brightness_pct: 28
              transition: 120
      - delay:
          hours: 3
