automation:
  - alias: Morning Wake Up Sequence
    id: morning_wake_up_sequence
    trigger:
      - platform: event
        event_type: "ios_wakeup_event"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: person.mike
                state: "home"
              - condition: numeric_state
                entity_id: sun.sun
                attribute: elevation
                below: 1.5
            sequence:
              - service: homeassistant.turn_on
                entity_id:
                  - switch.kitchen_island
                  - switch.christmas_tree
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 1.0
      - service: homeassistant.turn_on
        entity_id: group.exterior_lights
