automation:
  - alias: Morning Wake Up Sequence
    id: morning_wake_up_sequence
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: "ios_wakeup_event"
      - platform: state
        entity_id: input_boolean.nap_mode
        to: "off"
      - platform: state
        entity_id: binary_sensor.living_room_occupancy
        to: "on"
    condition:
      - condition: state
        entity_id: group.adults
        state: "home"
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 1.5
      - condition: time
        after: "05:00:00"
        before: "09:00:00"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.kitchen_island
          - switch.christmas_tree
      - wait_template: "{{ is_state('binary_sensor.living_room_occupancy', 'on') }}"
        timeout:
          hours: 1
        continue_on_timeout: false
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 1.5
      - service: light.turn_on
        target:
          entity_id:
            - light.kitchen_light
            - light.living_room_light
        data:
          brightness_pct: 28
          transition: 90
