input_boolean:
  nap_mode:
    name: Nap Mode
    icon: mdi:sleep
  girls_home_override:
    name: Girls Home Override
    icon: mdi:home-heart

homeassistant:
  customize:
    input_boolean.quite_mode:
      device_class: sound
    binary_sensor.nursery_door:
      device_class: door

scene:
  - name: nursery_led_on
    entities:
      light.nursery_led_strip:
        state: "on"
        brightness: 254
        color_temp: 311

  - name: nursery_led_on_low
    entities:
      light.nursery_led_strip:
        state: "on"
        brightness: 203
        rgb_color: [255, 127, 0]

  - name: baby_nap_on
    entities:
      switch.nursery_white_noise:
        state: "on"
      light.nursery_led_strip:
        state: "off"
      light.nursery_light:
        state: "off"
      fan.nursery_humidifier:
        state: "on"

  - name: baby_nap_off
    entities:
      switch.nursery_white_noise:
        state: "off"
      fan.nursery_fan:
        state: "off"
      fan.nursery_humidifier:
        state: "off"
      switch.nursery_power_loss_gate:
        state: "on"

script:
  tv_baby_monitor:
    alias: TV Baby Monitor
    sequence:
      - service: automation.trigger
        entity_id: automation.toggle_tv_monitor

automation:
  - alias: Nap Mode Button Toggle
    id: nursery_nap_mode_toggle
    mode: single
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: "00:15:8d:00:03:50:26:b5"
          command: "attribute_updated"
          args:
            value: 1
    action:
      - service: homeassistant.toggle
        entity_id:
          - input_boolean.nap_mode
      - delay:
          seconds: 1

  - alias: Nursery LED On
    mode: single
    max_exceeded: silent
    id: nursery_led_on
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_ieee: "00:0d:6f:ff:fe:a6:af:1d"
        command: "on"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.nursery_power_loss_gate
      - wait_template: '{{ not is_state("light.nursery_led_strip", "unavailable") }}'
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "off"
            sequence:
              - repeat:
                  sequence:
                    - service: scene.turn_on
                      entity_id: scene.nursery_led_on
                    - delay:
                        seconds: 1
                  until:
                    - condition: state
                      entity_id: light.nursery_led_strip
                      state: "on"
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "on"
            sequence:
              - repeat:
                  sequence:
                    - service: scene.turn_on
                      entity_id: scene.nursery_led_on_low
                    - delay:
                        seconds: 1
                  until:
                    - condition: state
                      entity_id: light.nursery_led_strip
                      state: "on"

  - alias: Nursery LED Off
    id: nursery_led_off
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: "00:0d:6f:ff:fe:a6:af:1d"
          command: "off"
      - platform: sun
        event: sunrise
        offset: "+02:00:00"
    action:
      - wait_template: '{{ not is_state("light.nursery_led_strip", "unavailable") }}'
      - service: light.turn_off
        data:
          entity_id:
            - light.nursery_led_strip

  - alias: Set Nap Accessories
    id: nursery_set_nap_accessories
    trigger:
      platform: state
      entity_id: input_boolean.nap_mode
    action:
      - choose:
          # Turning nap on
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "on"
            sequence:
              - service: scene.turn_on
                entity_id: scene.baby_nap_on
              - service: media_player.volume_set
                data:
                  volume_level: 0.15
                entity_id: media_player.sonos_living_room
          # Turning nap off
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "off"
            sequence:
              - choose:
                  - conditions:
                      - condition: time
                        after: "17:00:00"
                        before: "08:30:00"
                    sequence:
                      - service: scene.turn_on
                        entity_id: scene.baby_nap_off
                      - wait_template: '{{ not is_state("light.nursery_led_strip", "unavailable") }}'
                      - repeat:
                          sequence:
                            - service: scene.turn_on
                              entity_id: scene.nursery_led_on
                            - delay:
                                seconds: 1
                          until:
                            - condition: state
                              entity_id: light.nursery_led_strip
                              state: "on"
                default:
                  - service: scene.turn_on
                    entity_id: scene.baby_nap_off
                  - service: homeassistant.turn_on
                    entity_id: light.nursery_light

  - alias: Nursery Humidifer on evenings
    id: nursery_humidifer_evenings
    trigger:
      platform: state
      entity_id: input_boolean.nap_mode
      from: "off"
      to: "on"
    condition:
      - condition: time
        after: "18:00:00"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.nursery_humidifier

  - alias: Nursery Fan On if needed
    id: nursery_fan_temperature_conditional
    trigger:
      - platform: state
        entity_id: input_boolean.nap_mode
        to: "on"
      - platform: time
        at: "11:00:00"
      - platform: time
        at: "15:00:00"
      - platform: time
        at: "17:00:00"
    condition:
      - or:
          - condition: state
            entity_id: input_boolean.vacation_mode
            state: "off"
          - condition: state
            entity_id: input_boolean.girls_home_override
            state: "on"
      - or:
          - condition: numeric_state
            entity_id: weather.tomorrow_io_home_nowcast
            attribute: temperature
            above: 20
          - condition: numeric_state
            entity_id: sensor.kid_s_room_temperature #Acutal Room Temp
            above: 23
    action:
      - choose:
          # Manual trigger always turns on.
          - conditions: >
              {{ trigger.to_state.state == 'on' and
                 is_state('input_boolean.nap_mode', 'on') }}
            sequence:
              service: homeassistant.turn_on
              entity_id: fan.nursery_fan
          # If not a workday or override is turn on
          - conditions:
              - or:
                  - condition: state
                    entity_id: binary_sensor.workday_sensor
                    state: "off"
                  - condition: state
                    entity_id: input_boolean.girls_home_override
                    state: "on"
                  - condition: time
                    after: "14:00:00"
            sequence:
              service: homeassistant.turn_on
              entity_id: fan.nursery_fan

  - alias: Nursery Fan on if temperature rises
    id: nursery_fan_temperature_rise_conditional
    trigger:
      platform: numeric_state
      entity_id: sensor.kid_s_room_temperature
      above: 23
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "on"
      - condition: state
        entity_id: fan.nursery_fan
        state: "off"
    action:
      - service: homeassistant.turn_on
        entity_id: fan.nursery_fan

  - alias: Nursery Low Temperature Fan Off
    id: nursery_low_temp_fan_off
    trigger:
      - platform: numeric_state
        entity_id: sensor.kid_s_room_temperature
        below: 21
    action:
      - service: homeassistant.turn_off
        entity_id: fan.nursery_fan

  - alias: Nursery Temperature Warning
    id: nursery_temp_warning
    trigger:
      - platform: numeric_state
        entity_id: sensor.kid_s_room_temperature
        below: 18
        for:
          minutes: 10
      - platform: numeric_state
        entity_id: sensor.kid_s_room_temperature
        above: 25
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "on"
    action:
      - service: notify.adults
        data:
          title: "Nursery Temperature Warning"
          message: >
            Temperature {% if trigger.below != None %}Low{% else %}High{% endif %}: {{ trigger.to_state.state }}
          data:
            tag: "nursery-temp-warning"

  - alias: Turn nursery off if forgotten
    id: nursery_off_if_forgotten
    trigger:
      - platform: state
        entity_id: binary_sensor.kid_s_room
        to: "off"
        for:
          minutes: 30
      - platform: time
        at: "08:00:00"
    condition:
      - condition: time
        after: "07:30:00"
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "off"
      - or:
          - condition: state
            entity_id: light.nursery_light
            state: "on"
          - condition: state
            entity_id: light.nursery_led_strip
            state: "on"
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.nap_mode
        # Leave some light for 30 sec
        # if someone is in the room
      - service: homeassistant.turn_on
        entity_id: light.nursery_led_strip
      - delay: 10
      - service: homeassistant.turn_off
        entity_id: light.nursery_light
      - delay: 90
      - service: homeassistant.turn_off
        entity_id: light.nursery_led_strip
      - service: homeassistant.turn_off
        entity_id: switch.nursery_white_noise

  - alias: Turn off nursery accessories if forgotten
    id: nursery_turn_off_white_noise_forgotten
    trigger:
      - platform: state
        entity_id:
          - switch.nursery_white_noise
          - fan.nursery_humidifier
          - switch.nursery_fan
        to: "on"
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: switch.nap_mode
        state: "off"
    action:
      - service: homeassistant.turn_off
        target:
          entity_id: "{{ trigger.entity_id }}"

  - alias: Turn off nap mode via light switch
    id: nursery_nap_off_via_lightswitch
    trigger:
      - platform: state
        entity_id: light.nursery_light
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.nap_mode

  - alias: Notify if door left open during nap
    id: nursery_nap_on_door_open
    trigger:
      - platform: state
        entity_id: binary_sensor.nursery_door
        to: "on"
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "on"
    action:
      - service: notify.adults
        data:
          title: "Nursery Door Left Open"
          message: "Door is Open"
          data:
            tag: "nursery-door-open-warning"

  - alias: Quite mode when change table light on
    id: nusrey_quite_mode_change_table
    trigger:
      - platform: state
        entity_id: light.nursery_led_strip
        to: ~
    condition:
      - condition: time
        after: "09:00:00"
      - condition: template
        value_template: "{{ trigger.to_state.state in ['off', 'on'] }}"
    action:
      - service: homeassistant.turn_{{ trigger.to_state.state }}
        entity_id: input_boolean.quite_mode

  - alias: Turn on nap mode if forgotten
    id: nursery_nap_mode_on_forgotten
    trigger:
      - platform: state
        entity_id: binary_sensor.nursery_door
        to: "off"
        for:
          minutes: 1
    condition:
      # Bedtime
      - condition: time
        after: "19:00:00"
      - condition: state
        entity_id: light.nursery_light
        state: "off"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.nap_mode

  - alias: Nursey Door Open During Sleep
    id: nursery_door_open_during_sleep
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: binary_sensor.nursery_door
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "on"
        for:
          minutes: 10
      - condition: state
        entity_id: group.adults
        state: "home"
    action:
      - service: notify.adults
        data:
          title: "Nursery Door Opened!"
          message: >
            Someone has left the nursery
          data:
            tag: "nursery-escape-warning"
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.apple_tv_living_room
                state: "playing"
            sequence:
              - service: media_player.media_pause
                entity_id: media_player.apple_tv_living_room
      - delay:
          # Debounce this from happening
          # again quickly.
          minutes: 3

  - alias: Let the girls get out of bed
    id: nursery_let_girls_get_up
    trigger:
      - platform: time
        at: "07:10:00"
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "on"
      - or:
          - condition: state
            entity_id: group.adults
            state: "home"
          - condition: state
            entity_id: binary_sensor.guests_present
            state: "home"
    action:
      - wait_template: '{{ not is_state("light.nursery_led_strip", "unavailable") }}'
      - repeat:
          sequence:
            - service: scene.turn_on
              entity_id: scene.nursery_led_on
            - delay:
                seconds: 1
          until:
            - condition: state
              entity_id: light.nursery_led_strip
              state: "on"

  - alias: Reenable nursery light on power loss
    id: nusery_led_strip_reenable
    trigger:
      - platform: state
        entity_id: sensor.backupsxs1300g_status
        from: "Online"
      - platform: state
        entity_id: input_boolean.nap_mode
        to: "off"
        from: "on"
      - platform: time
        at: "07:09:30"
      - platform: time # On for bedtime
        at: "18:30:00"
    action:
      # Wait for the switch we want to turn on to be available
      - wait_template: '{{ not is_state("switch.nursery_power_loss_gate", "unavailable") }}'
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "off"
            sequence:
              - service: homeassistant.turn_on
                entity_id: switch.nursery_power_loss_gate
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "on"
              - condition: time
                after: "07:00:00"
                before: "08:00:00"
            sequence:
              - service: homeassistant.turn_on
                entity_id: switch.nursery_power_loss_gate

  - alias: Show Nursery Camera on TV automatically
    id: nursery_show_camera_automatically
    trigger:
      - platform: state
        entity_id: input_boolean.nap_mode
        to: "on"
    condition:
      not:
        - condition: state
          entity_id: media_player.apple_tv_living_room
          state: "playing"
    action:
      - service: homeassistant.turn_on
        entity_id: remote.apple_tv_living_room
      - service: remote.send_command
        target:
          entity_id: remote.apple_tv_living_room
        data:
          command: "wakeup"
      - delay:
          seconds: 30
      - event: homekit_faux_camera_event
      - delay:
          seconds: 5
      - service: remote.send_command
        target:
          entity_id: remote.apple_tv_living_room
        data:
          command: "home"

  - alias: Turn on kitchen lighting when bedtime starts
    id: nursery_turn_on_kitchen_lighting
    trigger:
      - platform: state
        entity_id: input_boolean.nap_mode
        to: "on"
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 1.5
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.kitchen_island

  - alias: Girls Light Control
    id: nursery_girls_light_control
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:03:ce:96:86
          command: click
          args:
            click_type: single
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "off"
    action:
      - service: homeassistant.toggle
        entity_id: light.nursery_light
