input_boolean:
  nap_mode:
    name: Nap Mode
    initial: off
    icon: mdi:sleep

homeassistant:
  customize:
    input_boolean.quite_mode:
      device_class: sound
    binary_sensor.nursery_door:
      device_class: door

scene:
  - name: nursery_led_on
    entities:
      light.nursery_led_strip:
        state: "on"
        brightness: 254
        color_temp: 311

  - name: nursery_led_on_low
    entities:
      light.nursery_led_strip:
        state: "on"
        brightness: 203
        rgb_color: [255, 127, 0]

  - name: baby_nap_on
    entities:
      switch.nursery_white_noise:
        state: "on"
      light.nursery_led_strip:
        state: "off"
      light.nursery_light:
        state: "off"

  - name: baby_nap_off
    entities:
      switch.nursery_white_noise:
        state: "off"
      switch.nursery_fan:
        state: "off"
      switch.nursery_humidifier:
        state: "off"

automation:
  - alias: Nap Mode Button Toggle
    id: nursery_nap_mode_toggle
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: "00:15:8d:00:03:50:26:b5"
          command: "attribute_updated"
          args:
            value: 1
    action:
      - service: homeassistant.toggle
        entity_id:
          - input_boolean.nap_mode
      - delay:
          seconds: 1

  - alias: Nursery LED On
    id: nursery_led_on
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_ieee: "00:0d:6f:ff:fe:a6:af:1d"
        command: "on"
    action:
      - wait_template: '{{ not is_state("light.nursery_led_strip", "unavailable") }}'
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "off"
            sequence:
              - service: scene.turn_on
                entity_id: scene.nursery_led_on
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "on"
            sequence:
              - service: scene.turn_on
                entity_id: scene.nursery_led_on_low

  - alias: Nursery LED Off
    id: nursery_led_off
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: "00:0d:6f:ff:fe:a6:af:1d"
          command: "off"
      - platform: sun
        event: sunrise
        offset: "+02:00:00"
    action:
      - wait_template: '{{ not is_state("light.nursery_led_strip", "unavailable") }}'
      - service: light.turn_off
        data:
          entity_id:
            - light.nursery_led_strip

  - alias: Set Nap Accessories
    id: nursery_set_nap_accessories
    trigger:
      platform: state
      entity_id: input_boolean.nap_mode
    action:
      - choose:
          # Turning nap on
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "on"
            sequence:
              - service: scene.turn_on
                entity_id: scene.baby_nap_on
          # Turning nap off
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "off"
            sequence:
              - choose:
                  - conditions:
                      - condition: time
                        before: "08:30:00"
                    sequence:
                      - service: scene.turn_on
                        entity_id: scene.baby_nap_off
                      - wait_template: '{{ not is_state("light.nursery_led_strip", "unavailable") }}'
                      - service: scene.turn_on
                        entity_id: scene.nursery_led_on
                default:
                  - service: scene.turn_on
                    entity_id: scene.baby_nap_off
                  - service: homeassistant.turn_on
                    entity_id: light.nursery_light

  - alias: Toggle TV Monitor
    id: nursery_toggle_tv_monitor
    trigger:
      platform: state
      entity_id: input_boolean.nap_mode
    condition:
      - condition: time
        after: "08:00:00"
    action:
      - wait_template: "{{ not is_state('media_player.living_room_mi_box_s', 'unavailable') }}"
        continue_on_timeout: false
        timeout: "00:20:00"
      - choose:
          # Turning nap on
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "on"
            sequence:
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: media_player.living_room_mi_box_s
                        state: "off"
                    sequence:
                      - service: androidtv.adb_command
                        data:
                          entity_id: media_player.living_room_mi_box_s
                          command: "POWER"
                      - service: androidtv.adb_command
                        data:
                          entity_id: media_player.living_room_mi_box_s
                          command: !secret baby_cam_adb_command
                      - delay: 2
                      - service: androidtv.adb_command
                        data:
                          entity_id: media_player.living_room_mi_box_s
                          command: "adb shell media volume --set 0"
                default:
                  - service: androidtv.adb_command
                    data:
                      entity_id: media_player.living_room_mi_box_s
                      command: !secret baby_cam_adb_command
                  - delay: 5
                  - service: androidtv.adb_command
                    data:
                      entity_id: media_player.living_room_mi_box_s
                      command: "adb shell media volume --set 0"
          # Turning nap off
          - conditions:
              - condition: state
                entity_id: input_boolean.nap_mode
                state: "off"
            sequence:
              - wait_template: "{{ not is_state('media_player.living_room_mi_box_s', 'unavailable') }}"
                continue_on_timeout: false
                timeout: "00:20:00"
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ not is_state('media_player.living_room_mi_box_s', 'off') }}"
                    sequence:
                      - service: androidtv.adb_command
                        data:
                          entity_id: media_player.living_room_mi_box_s
                          command: "HOME"
                      - delay: 2
                      - service: androidtv.adb_command
                        data:
                          entity_id: media_player.living_room_mi_box_s
                          command: "POWER"

  - alias: Nursery Humidifer on evenings
    id: nursery_humidifer_evenings
    trigger:
      platform: state
      entity_id: input_boolean.nap_mode
      from: "off"
      to: "on"
    condition:
      - condition: and
        conditions:
          - condition: time
            after: " 17:00:00"
          - condition: template
            # Only care about November - March
            value_template: "{{ now().month >= 11 or now().month <= 3 }}"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.nursery_humidifier

  - alias: Nursery Fan On if needed
    id: nursery_fan_temperature_conditional
    trigger:
      - platform: state
        entity_id: input_boolean.nap_mode
        from: "off"
        to: "on"
      - platform: time
        at: "11:00:00"
      - platform: time
        at: "15:00:00"
    action:
      service: homeassistant.turn_on
      entity_id: switch.nursery_fan
    condition:
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.temperature # Outside forecast
            above: 20
          - condition: numeric_state
            entity_id: sensor.kid_s_room_temperature #Acutal Room Temp
            above: 23

  - alias: Nursery Fan on if temperature rises
    id: nursery_fan_temperature_rise_conditional
    trigger:
      platform: numeric_state
      entity_id: sensor.kid_s_room_temperature
      above: 23
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "on"
      - condition: state
        entity_id: switch.nursery_fan
        state: "off"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.nursery_fan

  - alias: Nursery Low Temperature Fan Off
    id: nursery_low_temp_fan_off
    trigger:
      - platform: numeric_state
        entity_id: sensor.kid_s_room_temperature
        below: 21
    action:
      - service: homeassistant.turn_off
        entity_id: switch.nursery_fan

  - alias: Nursery Temperature Warning
    id: nursery_temp_warning
    trigger:
      - platform: numeric_state
        entity_id: sensor.kid_s_room_temperature
        below: 18
        for:
          minutes: 10
      - platform: numeric_state
        entity_id: sensor.kid_s_room_temperature
        above: 25
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "on"
    action:
      - service: notify.adults
        data:
          title: "Nursery Temperature Warning"
          message: >
            Temperature {% if trigger.below != None %}Low{% else %}High{% endif %}: {{ trigger.to_state.state }}
          data:
            tag: "nursery-temp-warning"

  - alias: Turn nursery off if forgotten
    id: nursery_off_if_forgotten
    trigger:
      - platform: state
        entity_id: binary_sensor.kid_s_room
        from: "on"
        to: "off"
    condition:
      - condition: time
        after: "08:30:00"
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "off"
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.nap_mode
      - service: homeassistant.turn_off
        entity_id: light.nursery_led_strip
      - delay: 10
      - service: homeassistant.turn_off
        entity_id: light.nursery_light

  - alias: Turn off nap mode via light switch
    id: nursery_nap_off_via_lightswitch
    trigger:
      - platform: state
        entity_id: light.nursery_light
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.nap_mode

  - alias: Notify if door open during nap
    id: nursery_nap_on_door_open
    trigger:
      - platform: state
        entity_id: binary_sensor.nursery_door
        to: "on"
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: input_boolean.nap_mode
        state: "on"
    action:
      - service: notify.adults
        data:
          title: "Nursery Door Left Open"
          data:
            tag: "nursery-door-open-warning"
