input_boolean:
  pupper_home:
    name: Pupper Home
    icon: mdi:dog

automation:
  - alias: Ask if Pupper Home after Dark
    id: ask_pupper_home
    triggers:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 5
    conditions:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "armed_away"
      - not:
          - condition: state
            entity_id: alarm_control_panel.alarmo
            state: "armed_vacation"
    actions:
      - variables:
          action_home: "{{ 'HOME_' ~ context.id }}"
          action_away: "{{ 'AWAY_' ~ context.id }}"
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "Is the pupper home alone?"
          data:
            actions:
              - action: "{{ action_home }}"
                title: "Pupper Home"
                activationMode: "background"
                authenticationRequired: true
                destructive: false
                behavior: "default"
              - action: "{{ action_away }}"
                title: "Not Home"
                activationMode: "background"
                authenticationRequired: true
                destructive: true
                behavior: "default"
      - wait_for_trigger:
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ action_home }}"
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              action: "{{ action_away }}"
      - choose:
          - conditions: "{{ wait.trigger.event.data.action == action_home }}"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.pupper_home
          - conditions: "{{ wait.trigger.event.data.action == action_away }}"
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.pupper_home

  - alias: Set light on for Pupper at dark
    id: set_pupper_light_on
    triggers:
      - platform: sun
        event: sunset
      - platform: state
        entity_id: alarm_control_panel.alarmo
        to: "armed_away"
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 2.0
      - condition: state
        entity_id: input_boolean.pupper_home
        state: "on"
    actions:
      - delay:
          minutes: 5
      - service: light.turn_on
        entity_id: light.kitchen_island
  
  - alias: Reset Pupper Home
    id: d0ee77f1-0e4f-40bd-8d03-a10fa95de594
    triggers:
      - platform: sun
        event: sunrise
    conditions:
      - condition: state
        entity_id: input_boolean.pupper_home
        state: "off"
      - condition: state
        entity_id: group.adults
        state: "home"
    actions:
      - service: input_boolean.turn_on
        entity_id: input_boolean.pupper_home
