automation:
  - alias: Reminder to turn on sentry mode at home in the driveway
    id: tesla_sentry_mode_home_reminder
    trigger:
      - platform: state
        entity_id: device_tracker.sparky_location
        to: "home"
        for:
          minutes: 15
    condition:
      - condition: state
        entity_id:
          - binary_sensor.sparky_charge_cable
          - switch.sparky_sentry_mode
        state: "off"
    action:
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "📷 Turn on sentry mode 📷"
          data:
            tag: "tesla-turn-on-sentry-mode"
            group: "tesla-notification"

  - alias: Disable Tesla Wifi in Driveway
    id: tesla_disable_wifi_in_driveway
    trigger:
      - platform: state
        entity_id: binary_sensor.sparky_charge_cable
        to: "on"
        id: plugged_in
      - platform: state
        entity_id: binary_sensor.sparky_charge_cable
        to: "off"
        id: unplugged
    condition:
      - condition: state
        entity_id: device_tracker.sparky_location
        state: "home"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: plugged_in
            sequence:
              - service: homeassistant.turn_on
                entity_id: switch.tesla
          - conditions:
              - condition: trigger
                id: unplugged
            sequence:
              - service: homeassistant.turn_off
                entity_id: switch.tesla
