mqtt:
  binary_sensor:
    - name: tesla_healthy
      state_topic: "teslamate/cars/1/healthy"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:heart-pulse

    - name: tesla_update_available
      state_topic: "teslamate/cars/1/update_available"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:alarm

    - name: tesla_locked
      device_class: lock
      state_topic: "teslamate/cars/1/locked"
      payload_on: "false"
      payload_off: "true"

    - name: tesla_sentry_mode
      state_topic: "teslamate/cars/1/sentry_mode"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:cctv

    - name: tesla_windows_open
      device_class: window
      state_topic: "teslamate/cars/1/windows_open"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:car-door

    - name: tesla_doors_open
      device_class: door
      state_topic: "teslamate/cars/1/doors_open"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:car-door

    - name: tesla_trunk_open
      device_class: opening
      state_topic: "teslamate/cars/1/trunk_open"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:car-side

    - name: tesla_frunk_open
      device_class: opening
      state_topic: "teslamate/cars/1/frunk_open"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:car-side

    - name: tesla_is_user_present
      device_class: presence
      state_topic: "teslamate/cars/1/is_user_present"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:human-greeting

    - name: tesla_is_climate_on
      state_topic: "teslamate/cars/1/is_climate_on"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:fan

    - name: tesla_is_preconditioning
      state_topic: "teslamate/cars/1/is_preconditioning"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:fan

    - name: tesla_plugged_in
      device_class: plug
      state_topic: "teslamate/cars/1/plugged_in"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:ev-station

    - name: tesla_charge_port_door_open
      device_class: opening
      state_topic: "teslamate/cars/1/charge_port_door_open"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:ev-plug-tesla

  sensor:
    - name: tesla_display_name
      state_topic: "teslamate/cars/1/display_name"
      icon: mdi:car

    - name: tesla_state
      state_topic: "teslamate/cars/1/state"
      icon: mdi:car-connected

    - name: tesla_since
      state_topic: "teslamate/cars/1/since"
      device_class: timestamp
      icon: mdi:clock-outline

    - name: tesla_version
      state_topic: "teslamate/cars/1/version"
      icon: mdi:alphabetical

    - name: tesla_update_version
      state_topic: "teslamate/cars/1/update_version"
      icon: mdi:alphabetical

    - name: tesla_model
      state_topic: "teslamate/cars/1/model"

    - name: tesla_trim_badging
      state_topic: "teslamate/cars/1/trim_badging"
      icon: mdi:shield-star-outline

    - name: tesla_exterior_color
      state_topic: "teslamate/cars/1/exterior_color"
      icon: mdi:palette

    - name: tesla_wheel_type
      state_topic: "teslamate/cars/1/wheel_type"

    - name: tesla_geofence
      state_topic: "teslamate/cars/1/geofence"
      icon: mdi:earth

    - name: tesla_latitude
      state_topic: "teslamate/cars/1/latitude"
      unit_of_measurement: °
      icon: mdi:crosshairs-gps

    - name: tesla_longitude
      state_topic: "teslamate/cars/1/longitude"
      unit_of_measurement: °
      icon: mdi:crosshairs-gps

    - name: tesla_power
      state_topic: "teslamate/cars/1/power"
      device_class: power
      unit_of_measurement: W
      icon: mdi:flash

    - name: tesla_speed
      state_topic: "teslamate/cars/1/speed"
      unit_of_measurement: "km/h"
      icon: mdi:speedometer

    - name: tesla_heading
      state_topic: "teslamate/cars/1/heading"
      unit_of_measurement: °
      icon: mdi:compass

    - name: tesla_elevation
      state_topic: "teslamate/cars/1/elevation"
      unit_of_measurement: m
      icon: mdi:image-filter-hdr

    - name: tesla_inside_temp
      state_topic: "teslamate/cars/1/inside_temp"
      device_class: temperature
      unit_of_measurement: °C
      icon: mdi:thermometer-lines

    - name: tesla_outside_temp
      state_topic: "teslamate/cars/1/outside_temp"
      device_class: temperature
      unit_of_measurement: °C
      icon: mdi:thermometer-lines

    - name: tesla_odometer
      state_topic: "teslamate/cars/1/odometer"
      unit_of_measurement: km
      icon: mdi:counter

    - name: tesla_est_battery_range_km
      state_topic: "teslamate/cars/1/est_battery_range_km"
      unit_of_measurement: km
      icon: mdi:gauge

    - name: tesla_rated_battery_range_km
      state_topic: "teslamate/cars/1/rated_battery_range_km"
      unit_of_measurement: km
      icon: mdi:gauge

    - name: tesla_ideal_battery_range_km
      state_topic: "teslamate/cars/1/ideal_battery_range_km"
      unit_of_measurement: km
      icon: mdi:gauge

    - name: tesla_battery_level
      state_topic: "teslamate/cars/1/battery_level"
      device_class: battery
      unit_of_measurement: "%"
      icon: mdi:battery-80

    - name: tesla_usable_battery_level
      state_topic: "teslamate/cars/1/usable_battery_level"
      unit_of_measurement: "%"
      icon: mdi:battery-80

    - name: tesla_charge_energy_added
      state_topic: "teslamate/cars/1/charge_energy_added"
      device_class: energy
      unit_of_measurement: kWh
      icon: mdi:battery-charging

    - name: tesla_charge_limit_soc
      state_topic: "teslamate/cars/1/charge_limit_soc"
      unit_of_measurement: "%"
      icon: mdi:battery-charging-100

    - name: tesla_charger_actual_current
      state_topic: "teslamate/cars/1/charger_actual_current"
      device_class: current
      unit_of_measurement: A
      icon: mdi:lightning-bolt

    - name: tesla_charger_phases
      state_topic: "teslamate/cars/1/charger_phases"
      icon: mdi:sine-wave

    - name: tesla_charger_power
      state_topic: "teslamate/cars/1/charger_power"
      device_class: power
      unit_of_measurement: kW
      icon: mdi:lightning-bolt

    - name: tesla_charger_voltage
      state_topic: "teslamate/cars/1/charger_voltage"
      device_class: voltage
      unit_of_measurement: V
      icon: mdi:lightning-bolt

    - name: tesla_scheduled_charging_start_time
      state_topic: "teslamate/cars/1/scheduled_charging_start_time"
      icon: mdi:clock-outline

    - name: tesla_time_to_full_charge
      state_topic: "teslamate/cars/1/time_to_full_charge"
      unit_of_measurement: h
      icon: mdi:clock-outline

    - name: tesla_shift_state
      state_topic: "teslamate/cars/1/shift_state"
      icon: mdi:car-shift-pattern

proximity:
  garage:
    zone: garage
    devices:
      - device_tracker.tesla_location
    unit_of_measurement: m

automation:
  - alias: Update Tesla location as MQTT location updates
    id: tesla_location_update_automation
    initial_state: on
    mode: single
    max_exceeded: silent
    trigger:
      - platform: mqtt
        topic: teslamate/cars/1/latitude
      - platform: mqtt
        topic: teslamate/cars/1/longitude
    action:
      - service: device_tracker.see
        data_template:
          dev_id: tesla_location
          gps:
            [
              "{{ states.sensor.tesla_latitude.state }}",
              "{{ states.sensor.tesla_longitude.state }}",
            ]

  - alias: Reminder to turn on sentry mode at home in the driveway
    id: tesla_sentry_mode_home_reminder
    trigger:
      - platform: state
        entity_id: sensor.tesla_state
        from: "driving"
        for:
          minutes: 15
    condition:
      - condition: state
        entity_id: device_tracker.tesla_location
        state: "home"
      - condition: state
        entity_id:
          - binary_sensor.tesla_plugged_in
          - binary_sensor.tesla_sentry_mode
        state: "off"
    action:
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "📷 Turn on sentry mode 📷"
          data:
            tag: "tesla-turn-on-sentry-mode"
            group: "tesla-notification"

  - alias: Close Garage daycare days
    id: tesla_close_garage_daycare_days
    trigger:
      - platform: numeric_state
        entity_id: proximity.garage
        above: 50
    condition:
      - condition: time
        after: "07:00:00"
        before: "09:00:00"
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: state
        entity_id: cover.garage
        state: "open"
    action:
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "️⬇️ Closing Garage Door ⬇️"
          data:
            group: "tesla-notification"
            tag: "tesla-close-garage-door"
            push:
              interruption-level: time-sensitive
      - service: cover.close_cover
        entity_id: cover.garage

  - alias: Open garage Daycare Days
    id: tesla_open_garage_daycare_days
    trigger:
      - platform: numeric_state
        entity_id: proximity.garage
        below: 50
    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: state
        entity_id: cover.garage
        state: "closed"
      - condition: time
        after: "16:00:00"
        before: "17:00:00"
      - not: # Garbage day, don't pull the car in
          - condition: time
            weekday:
              - "thu"
    action:
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "⬆️ Opening Garage Door ⬆️"
          data:
            tag: "tesla-open-garage-door"
            group: "tesla-notification"
            push:
              interruption-level: time-sensitive
      - service: cover.open_cover
        entity_id: cover.garage

  - alias: Disable Tesla Wifi in Driveway
    id: tesla_disable_wifi_in_driveway
    trigger:
      - platform: state
        entity_id: binary_sensor.tesla_plugged_in
        to: "on"
        id: plugged_in
      - platform: state
        entity_id: binary_sensor.tesla_plugged_in
        to: "off"
        id: unplugged
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: plugged_in
            sequence:
              - service: homeassistant.turn_on
                entity_id: switch.tesla
          - conditions:
              - condition: trigger
                id: unplugged
            sequence:
              - service: homeassistant.turn_off
                entity_id: switch.tesla
