automation:
  - alias: Evening Convenience Control
    id: upstairs_evening_convenience_control
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        to: "down_double"
        entity_id:
          - sensor.main_bath_light_action
          - sensor.main_stairs_action
          - sensor.upstairs_hall_action
    condition:
      - condition: time
        after: "21:00:00"
    actions:
      - event: goodnight_event
