automation:
  - alias: Vacation mode
    id: vacation_mode_depart
    mode: single
    max_exceeded: silent
    trigger:
      - platform: numeric_state
        entity_id: sensor.home_nearest_distance
        above: 55000
    condition:
      - condition: state
        entity_id: device_tracker.faux_girls_home
        state: "not_home"
      - condition: state
        entity_id: binary_sensor.guests_present
        state: "off"
    action:
      - service: select.select_option
        entity_id: select.my_ecobee_current_mode
        data:
          option: away
      - service: light.turn_off
        continue_on_error: true
        target:
          floor_id:
            - top_floor
            - main_floor
            - basement
      - service: cover.close_cover
        entity_id: cover.garage
      - service: lock.lock
        entity_id:
          - lock.front_door
          - lock.side_door
      - service: alarm_control_panel.alarm_arm_vacation
        target:
          entity_id: alarm_control_panel.alarmo

  - alias: Returning from vacation
    id: vacation_mode_return
    mode: single
    max_exceeded: silent
    trigger:
      - platform: numeric_state
        entity_id: sensor.home_nearest_distance
        below: 50000
      - platform: state
        entity_id: sensor.home_nearest_direction_of_travel
        to: "arrived"
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "armed_vacation"
    action:
      - service: select.select_option
        entity_id: select.my_ecobee_current_mode
        data:
          option: home
      - service: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.alarmo

  - alias: Vacation Lighting
    mode: single
    max_exceeded: silent
    id: vacation_lighting
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 1.0
        id: light_on
      - platform: time
        at: "22:00:00"
        id: light_off
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "armed_vacation"
    action:
      - delay:
          minutes: "{{ (range(0, 25)|random|int) }}"
      - choose:
          - conditions:
              - condition: trigger
                id: light_on
            sequence:
              - service: homeassistant.turn_on
                entity_id: light.kitchen_island
              - delay:
                  minutes: "{{ (range(0, 10)|random|int) }}"
              - service: homeassistant.turn_on
                entity_id:
                  - switch.basement_hall
                  - light.basement_room_light_dimmer
          - conditions:
              - condition: trigger
                id: light_off
            sequence:
              - service: homeassistant.turn_off
                entity_id:
                  - switch.basement_hall
                  - light.basement_room_light_dimmer
              - delay:
                  minutes: "{{ (range(0, 35)|random|int) }}"
              - service: homeassistant.turn_off
                entity_id: light.kitchen_island
