input_boolean:
  vacation_mode:
    name: Vacation Mode
    icon: mdi:palm-tree

automation:
  - alias: Vacation mode
    id: vacation_mode_depart
    trigger:
      - platform: numeric_state
        entity_id: proximity.home
        above: 55000
    condition:
      - condition: state
        entity_id: device_tracker.faux_girls_home
        state: "not_home"
      - condition: state
        entity_id: binary_sensor.guests_present
        state: "off"
    action:
      - service: select.select_option
        entity_id: select.my_ecobee_current_mode
        data:
          option: away
      - service: light.turn_off
        continue_on_error: true
        target:
          area_id:
            - 490ec53ba1bc411a96655d0e3492e7d7 # Basement
            - e153ba2916a6441a8e5dbc47d58b9a73 # living room
          entity_id:
            - light.living_room_light
            - light.kitchen_island
            - light.kitchen_light
            - light.nursery_light
            - switch.nursery_fan
            - light.nursery_led_strip
            - switch.nursery_white_noise
            - switch.master_white_noise
            - switch.spare_bedroom_fan
      - service: cover.close_cover
        entity_id: cover.garage
      - service: lock.lock
        entity_id:
          - lock.front_door
          - lock.side_door
      - service: homeassistant.turn_on
        entity_id:
          - input_boolean.vacation_mode

  - alias: Returning from vacation
    id: vacation_mode_return
    trigger:
      - platform: numeric_state
        entity_id: proximity.home
        below: 50000
      - platform: state
        entity_id: proximity.home
        attribute: dir_of_travel
        to: "arrived"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - service: select.select_option
        entity_id: select.my_ecobee_current_mode
        data:
          option: home
      - service: homeassistant.turn_off
        entity_id:
          - input_boolean.vacation_mode

  - alias: Vacation Lighting
    mode: single
    max_exceeded: silent
    id: vacation_lighting
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 1.0
        id: light_on
      - platform: time
        at: "22:00:00"
        id: light_off
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - delay:
          minutes: "{{ (range(0, 25)|random|int) }}"
      - choose:
          - conditions:
              - condition: trigger
                id: light_on
            sequence:
              - service: homeassistant.turn_on
                entity_id: light.kitchen_island
              - delay:
                  minutes: "{{ (range(0, 10)|random|int) }}"
              - service: homeassistant.turn_on
                entity_id:
                  - switch.basement_hall
                  - light.basement_room_light_dimmer
          - conditions:
              - condition: trigger
                id: light_off
            sequence:
              - service: homeassistant.turn_off
                entity_id:
                  - switch.basement_hall
                  - light.basement_room_light_dimmer
              - delay:
                  minutes: "{{ (range(0, 35)|random|int) }}"
              - service: homeassistant.turn_off
                entity_id: light.kitchen_island
