automation:
  - alias: Tiff Work Notifications
    id: work_tiff_travel_notifications
    trigger:
      - platform: zone
        entity_id:
          - device_tracker.tiffanys_iphone
        zone: zone.tiff_work
        event: enter
        variables:
          msg: Tiff has arrived at work 🏢
      - platform: zone
        entity_id:
          - device_tracker.tiffanys_iphone
        zone: zone.tiff_work
        event: leave
        variables:
          msg: Tiff has left work 🏡
    condition:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - alias: "condition alias (name)"
        condition: time
        after: "06:00:00"
        before: "19:00:00"
    action:
      - service: notify.mobile_app_michaels_iphone
        data:
          message: "{{ msg }}"
